using System.Text.RegularExpressions;

namespace SIL.Motif.Tests.App;

internal enum InteractiveControlFamily
{
    Action,
    Link,
    Filter,
    TextEntry,
    Choice,
    Check,
    Radio,
    Disclosure,
    List,
    MatrixCell,
    SelectableText,
    Mark,
    Grid,
    Tree,
    Morpheme,
    Progress,
    FocusableSurface,
    ContentSurface,
    Occurrence,
    Summary,
    StaticText,
    Collection,
    Container,
}

internal sealed record MarkupControlDeclaration(string Source, string MarkupType, int Count);

internal sealed record GeneratedControlFamily(
    string Key,
    InteractiveControlFamily Family,
    string Source,
    string Marker);

internal sealed record ReportedSceneGap(
    string Test,
    string Scene,
    InteractiveControlFamily Family,
    string Reason);

internal static class InteractiveControlManifest
{
    private static readonly Regex MarkupElement = new("<(?<name>[A-Za-z_][A-Za-z0-9_:-]*)(?=[\\s/>])");

    public static IReadOnlyDictionary<string, InteractiveControlFamily> MarkupFamilies { get; } =
        new Dictionary<string, InteractiveControlFamily>(StringComparer.Ordinal)
        {
            ["Button"] = InteractiveControlFamily.Action,
            ["ToggleButton"] = InteractiveControlFamily.Check,
            ["HyperlinkButton"] = InteractiveControlFamily.Link,
            ["SplitButton"] = InteractiveControlFamily.Action,
            ["MenuItem"] = InteractiveControlFamily.Action,
            ["TextBox"] = InteractiveControlFamily.TextEntry,
            ["ComboBox"] = InteractiveControlFamily.Choice,
            ["NumericUpDown"] = InteractiveControlFamily.TextEntry,
            ["CheckBox"] = InteractiveControlFamily.Check,
            ["RadioButton"] = InteractiveControlFamily.Radio,
            ["Expander"] = InteractiveControlFamily.Disclosure,
            ["ListBox"] = InteractiveControlFamily.List,
            ["DataGrid"] = InteractiveControlFamily.Grid,
            ["TreeView"] = InteractiveControlFamily.Tree,
            ["views:MatrixCell"] = InteractiveControlFamily.MatrixCell,
            ["views:FilterChip"] = InteractiveControlFamily.Filter,
            ["views:CopyableTextBlock"] = InteractiveControlFamily.SelectableText,
            ["views:TraceNotationToken"] = InteractiveControlFamily.Action,
            ["controls:OpinionMark"] = InteractiveControlFamily.Mark,
            ["controls:UnreadMark"] = InteractiveControlFamily.Mark,
            ["views:MorphemeRow"] = InteractiveControlFamily.Morpheme,
            ["Border"] = InteractiveControlFamily.FocusableSurface,
            ["StackPanel"] = InteractiveControlFamily.Container,
            ["UserControl"] = InteractiveControlFamily.Container,
        };

    public static IReadOnlyList<MarkupControlDeclaration> MarkupDeclarations { get; } =
    [
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "Button", 5),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "SplitButton", 1),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "TextBox", 1),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "ComboBox", 1),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "NumericUpDown", 1),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "Expander", 1),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "ListBox", 2),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "views:MatrixCell", 1),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "views:FilterChip", 2),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "views:CopyableTextBlock", 11),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "controls:OpinionMark", 2),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "Border", 5),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "StackPanel", 14),
        new("src/SIL.Motif.App/Views/ComparePanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/CrashWindow.axaml", "Button", 4),
        new("src/SIL.Motif.App/Views/CrashWindow.axaml", "HyperlinkButton", 1),
        new("src/SIL.Motif.App/Views/CrashWindow.axaml", "Expander", 1),
        new("src/SIL.Motif.App/Views/CrashWindow.axaml", "StackPanel", 3),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "Button", 7),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "TextBox", 3),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "ComboBox", 1),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "Expander", 6),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "TreeView", 1),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "views:CopyableTextBlock", 69),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "views:MorphemeRow", 1),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "Border", 5),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "StackPanel", 27),
        new("src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/DifferencePanel.axaml", "ListBox", 2),
        new("src/SIL.Motif.App/Views/DifferencePanel.axaml", "views:CopyableTextBlock", 20),
        new("src/SIL.Motif.App/Views/DifferencePanel.axaml", "Border", 4),
        new("src/SIL.Motif.App/Views/DifferencePanel.axaml", "StackPanel", 9),
        new("src/SIL.Motif.App/Views/DifferencePanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/ExpertTracePanel.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/ExpertTracePanel.axaml", "ComboBox", 1),
        new("src/SIL.Motif.App/Views/ExpertTracePanel.axaml", "CheckBox", 1),
        new("src/SIL.Motif.App/Views/ExpertTracePanel.axaml", "Expander", 2),
        new("src/SIL.Motif.App/Views/ExpertTracePanel.axaml", "views:CopyableTextBlock", 3),
        new("src/SIL.Motif.App/Views/ExpertTracePanel.axaml", "views:TraceNotationToken", 6),
        new("src/SIL.Motif.App/Views/ExpertTracePanel.axaml", "Border", 2),
        new("src/SIL.Motif.App/Views/ExpertTracePanel.axaml", "StackPanel", 12),
        new("src/SIL.Motif.App/Views/ExpertTracePanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/GrammarPanel.axaml", "Button", 9),
        new("src/SIL.Motif.App/Views/GrammarPanel.axaml", "ToggleButton", 1),
        new("src/SIL.Motif.App/Views/GrammarPanel.axaml", "HyperlinkButton", 1),
        new("src/SIL.Motif.App/Views/GrammarPanel.axaml", "views:FilterChip", 4),
        new("src/SIL.Motif.App/Views/GrammarPanel.axaml", "views:CopyableTextBlock", 20),
        new("src/SIL.Motif.App/Views/GrammarPanel.axaml", "Border", 6),
        new("src/SIL.Motif.App/Views/GrammarPanel.axaml", "StackPanel", 21),
        new("src/SIL.Motif.App/Views/GrammarPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/HandoffPanel.axaml", "Button", 6),
        new("src/SIL.Motif.App/Views/HandoffPanel.axaml", "Expander", 1),
        new("src/SIL.Motif.App/Views/HandoffPanel.axaml", "views:CopyableTextBlock", 27),
        new("src/SIL.Motif.App/Views/HandoffPanel.axaml", "Border", 10),
        new("src/SIL.Motif.App/Views/HandoffPanel.axaml", "StackPanel", 11),
        new("src/SIL.Motif.App/Views/HandoffPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/HelpPopupView.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/HelpPopupView.axaml", "Border", 1),
        new("src/SIL.Motif.App/Views/HelpPopupView.axaml", "StackPanel", 1),
        new("src/SIL.Motif.App/Views/HelpPopupView.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/Inspector.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/Inspector.axaml", "HyperlinkButton", 6),
        new("src/SIL.Motif.App/Views/Inspector.axaml", "views:CopyableTextBlock", 34),
        new("src/SIL.Motif.App/Views/Inspector.axaml", "Border", 9),
        new("src/SIL.Motif.App/Views/Inspector.axaml", "StackPanel", 14),
        new("src/SIL.Motif.App/Views/Inspector.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/ListedWordCard.axaml", "views:CopyableTextBlock", 1),
        new("src/SIL.Motif.App/Views/ListedWordCard.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/ListWordCard.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/ListWordCard.axaml", "views:CopyableTextBlock", 1),
        new("src/SIL.Motif.App/Views/ListWordCard.axaml", "StackPanel", 1),
        new("src/SIL.Motif.App/Views/ListWordCard.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/MainWindow.axaml", "Button", 13),
        new("src/SIL.Motif.App/Views/MainWindow.axaml", "HyperlinkButton", 1),
        new("src/SIL.Motif.App/Views/MainWindow.axaml", "ListBox", 1),
        new("src/SIL.Motif.App/Views/MainWindow.axaml", "views:CopyableTextBlock", 10),
        new("src/SIL.Motif.App/Views/MainWindow.axaml", "Border", 6),
        new("src/SIL.Motif.App/Views/MainWindow.axaml", "StackPanel", 15),
        new("src/SIL.Motif.App/Views/MatrixCell.axaml", "Border", 1),
        new("src/SIL.Motif.App/Views/MatrixCell.axaml", "StackPanel", 2),
        new("src/SIL.Motif.App/Views/MatrixCell.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/MiniMatrix.axaml", "HyperlinkButton", 1),
        new("src/SIL.Motif.App/Views/MiniMatrix.axaml", "views:MatrixCell", 1),
        new("src/SIL.Motif.App/Views/MiniMatrix.axaml", "Border", 1),
        new("src/SIL.Motif.App/Views/MiniMatrix.axaml", "StackPanel", 4),
        new("src/SIL.Motif.App/Views/MiniMatrix.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/ParsePrompt.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/ParsePrompt.axaml", "views:CopyableTextBlock", 1),
        new("src/SIL.Motif.App/Views/ParsePrompt.axaml", "StackPanel", 1),
        new("src/SIL.Motif.App/Views/ParsePrompt.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/RefusalBlock.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/RefusalBlock.axaml", "Expander", 1),
        new("src/SIL.Motif.App/Views/RefusalBlock.axaml", "views:CopyableTextBlock", 2),
        new("src/SIL.Motif.App/Views/RefusalBlock.axaml", "StackPanel", 1),
        new("src/SIL.Motif.App/Views/RefusalBlock.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "Button", 42),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "HyperlinkButton", 1),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "ComboBox", 2),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "CheckBox", 1),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "Expander", 2),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "views:FilterChip", 8),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "views:CopyableTextBlock", 46),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "controls:OpinionMark", 3),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "controls:UnreadMark", 1),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "views:MorphemeRow", 3),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "Border", 16),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "StackPanel", 49),
        new("src/SIL.Motif.App/Views/ResultsInTextPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/ReviewPanel.axaml", "Button", 8),
        new("src/SIL.Motif.App/Views/ReviewPanel.axaml", "HyperlinkButton", 3),
        new("src/SIL.Motif.App/Views/ReviewPanel.axaml", "views:CopyableTextBlock", 32),
        new("src/SIL.Motif.App/Views/ReviewPanel.axaml", "Border", 12),
        new("src/SIL.Motif.App/Views/ReviewPanel.axaml", "StackPanel", 19),
        new("src/SIL.Motif.App/Views/ReviewPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/SelectionPanel.axaml", "TextBox", 2),
        new("src/SIL.Motif.App/Views/SelectionPanel.axaml", "Button", 2),
        new("src/SIL.Motif.App/Views/SelectionPanel.axaml", "NumericUpDown", 3),
        new("src/SIL.Motif.App/Views/SelectionPanel.axaml", "CheckBox", 4),
        new("src/SIL.Motif.App/Views/SelectionPanel.axaml", "Expander", 2),
        new("src/SIL.Motif.App/Views/SelectionPanel.axaml", "ListBox", 1),
        new("src/SIL.Motif.App/Views/SelectionPanel.axaml", "views:CopyableTextBlock", 9),
        new("src/SIL.Motif.App/Views/SelectionPanel.axaml", "StackPanel", 7),
        new("src/SIL.Motif.App/Views/SelectionPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/SetupDialog.axaml", "Button", 6),
        new("src/SIL.Motif.App/Views/SetupDialog.axaml", "TextBox", 1),
        new("src/SIL.Motif.App/Views/SetupDialog.axaml", "NumericUpDown", 1),
        new("src/SIL.Motif.App/Views/SetupDialog.axaml", "CheckBox", 2),
        new("src/SIL.Motif.App/Views/SetupDialog.axaml", "Border", 7),
        new("src/SIL.Motif.App/Views/SetupDialog.axaml", "StackPanel", 7),
        new("src/SIL.Motif.App/Views/SetupDialog.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "HyperlinkButton", 1),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "TextBox", 1),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "ComboBox", 1),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "DataGrid", 1),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "views:FilterChip", 2),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "views:CopyableTextBlock", 12),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "Border", 3),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "StackPanel", 3),
        new("src/SIL.Motif.App/Views/StatisticsPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/TextsListsPanel.axaml", "Button", 4),
        new("src/SIL.Motif.App/Views/TextsListsPanel.axaml", "ComboBox", 1),
        new("src/SIL.Motif.App/Views/TextsListsPanel.axaml", "ListBox", 1),
        new("src/SIL.Motif.App/Views/TextsListsPanel.axaml", "views:CopyableTextBlock", 4),
        new("src/SIL.Motif.App/Views/TextsListsPanel.axaml", "StackPanel", 2),
        new("src/SIL.Motif.App/Views/TextsListsPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/TextWordsPanel.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/TextWordsPanel.axaml", "TextBox", 1),
        new("src/SIL.Motif.App/Views/TextWordsPanel.axaml", "ListBox", 1),
        new("src/SIL.Motif.App/Views/TextWordsPanel.axaml", "views:FilterChip", 7),
        new("src/SIL.Motif.App/Views/TextWordsPanel.axaml", "views:CopyableTextBlock", 5),
        new("src/SIL.Motif.App/Views/TextWordsPanel.axaml", "StackPanel", 2),
        new("src/SIL.Motif.App/Views/TextWordsPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/TraceAnalysesView.axaml", "HyperlinkButton", 1),
        new("src/SIL.Motif.App/Views/TraceAnalysesView.axaml", "Expander", 3),
        new("src/SIL.Motif.App/Views/TraceAnalysesView.axaml", "views:CopyableTextBlock", 21),
        new("src/SIL.Motif.App/Views/TraceAnalysesView.axaml", "Border", 2),
        new("src/SIL.Motif.App/Views/TraceAnalysesView.axaml", "StackPanel", 5),
        new("src/SIL.Motif.App/Views/TraceAnalysesView.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/TryWordPanel.axaml", "Button", 13),
        new("src/SIL.Motif.App/Views/TryWordPanel.axaml", "HyperlinkButton", 1),
        new("src/SIL.Motif.App/Views/TryWordPanel.axaml", "TextBox", 1),
        new("src/SIL.Motif.App/Views/TryWordPanel.axaml", "TreeView", 1),
        new("src/SIL.Motif.App/Views/TryWordPanel.axaml", "views:CopyableTextBlock", 26),
        new("src/SIL.Motif.App/Views/TryWordPanel.axaml", "Border", 7),
        new("src/SIL.Motif.App/Views/TryWordPanel.axaml", "StackPanel", 14),
        new("src/SIL.Motif.App/Views/TryWordPanel.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/WordRow.axaml", "HyperlinkButton", 3),
        new("src/SIL.Motif.App/Views/WordRow.axaml", "CheckBox", 1),
        new("src/SIL.Motif.App/Views/WordRow.axaml", "views:CopyableTextBlock", 14),
        new("src/SIL.Motif.App/Views/WordRow.axaml", "controls:OpinionMark", 1),
        new("src/SIL.Motif.App/Views/WordRow.axaml", "Border", 7),
        new("src/SIL.Motif.App/Views/WordRow.axaml", "StackPanel", 6),
        new("src/SIL.Motif.App/Views/WordRow.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/WordRowCard.axaml", "views:CopyableTextBlock", 6),
        new("src/SIL.Motif.App/Views/WordRowCard.axaml", "views:MorphemeRow", 3),
        new("src/SIL.Motif.App/Views/WordRowCard.axaml", "StackPanel", 3),
        new("src/SIL.Motif.App/Views/WordRowCard.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/WordRowHeader.axaml", "views:CopyableTextBlock", 8),
        new("src/SIL.Motif.App/Views/WordRowHeader.axaml", "Border", 3),
        new("src/SIL.Motif.App/Views/WordRowHeader.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/Pages/AiHandoffPage.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/Pages/AiHandoffPage.axaml", "views:CopyableTextBlock", 1),
        new("src/SIL.Motif.App/Views/Pages/AiHandoffPage.axaml", "Border", 1),
        new("src/SIL.Motif.App/Views/Pages/AiHandoffPage.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/Pages/OverviewPage.axaml", "Button", 2),
        new("src/SIL.Motif.App/Views/Pages/OverviewPage.axaml", "HyperlinkButton", 6),
        new("src/SIL.Motif.App/Views/Pages/OverviewPage.axaml", "Expander", 1),
        new("src/SIL.Motif.App/Views/Pages/OverviewPage.axaml", "views:CopyableTextBlock", 21),
        new("src/SIL.Motif.App/Views/Pages/OverviewPage.axaml", "Border", 13),
        new("src/SIL.Motif.App/Views/Pages/OverviewPage.axaml", "StackPanel", 18),
        new("src/SIL.Motif.App/Views/Pages/OverviewPage.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/Pages/TextsPage.axaml", "Button", 8),
        new("src/SIL.Motif.App/Views/Pages/TextsPage.axaml", "HyperlinkButton", 1),
        new("src/SIL.Motif.App/Views/Pages/TextsPage.axaml", "views:CopyableTextBlock", 2),
        new("src/SIL.Motif.App/Views/Pages/TextsPage.axaml", "Border", 1),
        new("src/SIL.Motif.App/Views/Pages/TextsPage.axaml", "StackPanel", 5),
        new("src/SIL.Motif.App/Views/Pages/TextsPage.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/Pages/TimingPage.axaml", "Button", 19),
        new("src/SIL.Motif.App/Views/Pages/TimingPage.axaml", "TextBox", 1),
        new("src/SIL.Motif.App/Views/Pages/TimingPage.axaml", "ComboBox", 2),
        new("src/SIL.Motif.App/Views/Pages/TimingPage.axaml", "NumericUpDown", 3),
        new("src/SIL.Motif.App/Views/Pages/TimingPage.axaml", "Expander", 1),
        new("src/SIL.Motif.App/Views/Pages/TimingPage.axaml", "views:CopyableTextBlock", 43),
        new("src/SIL.Motif.App/Views/Pages/TimingPage.axaml", "Border", 14),
        new("src/SIL.Motif.App/Views/Pages/TimingPage.axaml", "StackPanel", 25),
        new("src/SIL.Motif.App/Views/Pages/TimingPage.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/Pages/TryAWordPage.axaml", "UserControl", 1),
        new("src/SIL.Motif.App/Views/Pages/WarningsPage.axaml", "Button", 1),
        new("src/SIL.Motif.App/Views/Pages/WarningsPage.axaml", "views:CopyableTextBlock", 2),
        new("src/SIL.Motif.App/Views/Pages/WarningsPage.axaml", "Border", 1),
        new("src/SIL.Motif.App/Views/Pages/WarningsPage.axaml", "StackPanel", 1),
        new("src/SIL.Motif.App/Views/Pages/WarningsPage.axaml", "UserControl", 1),
    ];

    public static IReadOnlyList<GeneratedControlFamily> GeneratedFamilies { get; } =
    [
        new("word occurrence and card", InteractiveControlFamily.Occurrence,
            "src/SIL.Motif.App/Views/ResultsInTextPanel.axaml.cs", "OnTokenKeyDown"),
        new("opened help links", InteractiveControlFamily.Link,
            "src/SIL.Motif.App/Views/HelpPopupView.axaml", "md:MarkdownRenderer"),
        new("rendered Help content host", InteractiveControlFamily.Container,
            "src/SIL.Motif.App/Views/HelpPopupView.axaml", "md:MarkdownRenderer"),
        new("diagnostic owned window", InteractiveControlFamily.Container,
            "src/SIL.Motif.App/Views/DiagnosticWindow.axaml.cs", "new DiagnosticPanel"),
        new("statistics grid headers and rows", InteractiveControlFamily.Grid,
            "src/SIL.Motif.App/Views/StatisticsPanel.axaml", "DataGridTemplateColumn"),
        new("morpheme keyboard popup", InteractiveControlFamily.Morpheme,
            "src/SIL.Motif.App/Views/MorphemeRow.cs", "block.KeyDown"),
        new("nested project menu entries", InteractiveControlFamily.Action,
            "src/SIL.Motif.App/Views/MainWindow.axaml", "Open recent"),
        new("outcome summary and legend", InteractiveControlFamily.Summary,
            "src/SIL.Motif.App/Views/OutcomeBar.cs", "public sealed class OutcomeBar"),
        new("timing kind summary bar", InteractiveControlFamily.Summary,
            "src/SIL.Motif.App/Views/TimingKindBar.cs", "public sealed class TimingKindBar"),
        new("project summary surface", InteractiveControlFamily.ContentSurface,
            "src/SIL.Motif.App/Views/Pages/OverviewPage.axaml", "AutomationProperties.Name=\"Project summary\""),
        new("overview metric words", InteractiveControlFamily.StaticText,
            "src/SIL.Motif.App/Views/Pages/OverviewPage.axaml",
            "AutomationProperties.AutomationId=\"{x:Static app:AutomationIds.OverviewSpeed}\""),
        new("project history rows", InteractiveControlFamily.Collection,
            "src/SIL.Motif.App/Views/Pages/OverviewPage.axaml", "ItemsControl ItemsSource=\"{Binding History.Entries}"),
        new("inspector breadcrumb", InteractiveControlFamily.Collection,
            "src/SIL.Motif.App/Views/Inspector.axaml", "AutomationProperties.Name=\"Breadcrumb\""),
        new("diagnostic parser effort rows", InteractiveControlFamily.Collection,
            "src/SIL.Motif.App/Views/DiagnosticPanel.axaml", "AutomationProperties.Name=\"Parser effort rows\""),
        new("assessment progress bar", InteractiveControlFamily.Progress,
            "src/SIL.Motif.App/Views/MainWindow.axaml", "AutomationProperties.Name=\"Parse all words progress\""),
        new("WordRow read-state marker", InteractiveControlFamily.Mark,
            "src/SIL.Motif.App/Views/WordRow.axaml", "AutomationProperties.Name=\"{Binding UnreadText}\""),
        new("Matrix selection summary", InteractiveControlFamily.Container,
            "src/SIL.Motif.App/Views/ComparePanel.axaml", "AutomationProperties.Name=\"{Binding Compare.SelectionText}\""),
    ];

    public static IReadOnlyList<ReportedSceneGap> ReportedSceneGaps { get; } =
    [
        new(nameof(SIL.Motif.Tests.App.Smoke.FirstProjectSmokeTests.AFirstProjectOpensCapturesSetsUpAndShowsItsFirstRun),
            "completed Overview", InteractiveControlFamily.Mark,
            "The Overview's Time-only scene still realizes a No parse mark before its runtime owner is confirmed."),
        new(nameof(SIL.Motif.Tests.App.Smoke.FirstProjectSmokeTests.AFirstProjectOpensCapturesSetsUpAndShowsItsFirstRun),
            "completed Overview", InteractiveControlFamily.Morpheme,
            "The Overview's Time-only scene still realizes morpheme details before their runtime owner is confirmed."),
    ];

    public static IReadOnlyList<InteractiveControlFamily> ClassifyMarkup(string markupType) =>
        MarkupFamilies.TryGetValue(markupType, out var family) ? [family] : [];

    public static int CountDeclarations(string markup, string markupType) =>
        MarkupElement.Matches(markup)
            .Count(match => string.Equals(match.Groups["name"].Value, markupType, StringComparison.Ordinal));
}
