<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SIL.Motif.Help</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SIL.Motif.Tests.Cli" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\help\**\*">
      <LogicalName>help/%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
