// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: LexEntry.DialectLabels (rel/seq CmPossibility, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>LexEntry.DialectLabels</c> operation kinds.</summary>
public static class LexEntryDialectLabelsOperationKinds
{
    public const string AddRefDialectLabels = "lexical/lexEntry/addRefDialectLabels";
    public const string RemoveRefDialectLabels = "lexical/lexEntry/removeRefDialectLabels";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefDialectLabels);
        OperationKindRegistry.Register(RemoveRefDialectLabels);
        OperationHandlerRegistry.Register(AddRefDialectLabels, LexEntryDialectLabelsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefDialectLabels, LexEntryDialectLabelsRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="LexEntryDialectLabelsOperationKinds.AddRefDialectLabels"/>
/// and <see cref="LexEntryDialectLabelsOperationKinds.RemoveRefDialectLabels"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class LexEntryDialectLabelsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="LexEntryDialectLabelsOperationKinds.AddRefDialectLabels"/>: resolves the
/// referenced ICmPossibility and adds it to <c>lexEntry.DialectLabelsRS</c> (a no-op if already
/// present).</summary>
public static class LexEntryDialectLabelsAddRefLowering
{
    public static void Apply(LcmCache cache, ILexEntry lexEntry, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<ICmPossibility>(
            cache, lexEntry.DialectLabelsRS, memberId, LexEntryDialectLabelsOperationKinds.AddRefDialectLabels);
}

/// <summary>Lowers <see cref="LexEntryDialectLabelsOperationKinds.RemoveRefDialectLabels"/>: resolves the
/// referenced ICmPossibility and removes it from <c>lexEntry.DialectLabelsRS</c> (a no-op if
/// absent).</summary>
public static class LexEntryDialectLabelsRemoveRefLowering
{
    public static void Apply(LcmCache cache, ILexEntry lexEntry, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<ICmPossibility>(
            cache, lexEntry.DialectLabelsRS, memberId, LexEntryDialectLabelsOperationKinds.RemoveRefDialectLabels);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="LexEntryDialectLabelsOperationKinds.AddRefDialectLabels"/> operation.</summary>
internal sealed class LexEntryDialectLabelsAddRefHandler : IOperationHandler
{
    internal static readonly LexEntryDialectLabelsAddRefHandler Instance = new();
    private LexEntryDialectLabelsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryDialectLabelsOperationKinds.AddRefDialectLabels}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryDialectLabelsOperationKinds.AddRefDialectLabels}' requires 'after'.");
        }

        var memberId = LexEntryDialectLabelsMemberPayload.Parse(after, LexEntryDialectLabelsOperationKinds.AddRefDialectLabels);

        var (id, lexEntry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryDialectLabelsOperationKinds.AddRefDialectLabels);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntry.DialectLabelsRS);
        LexEntryDialectLabelsAddRefLowering.Apply(cache, lexEntry, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntry.DialectLabelsRS);

        return new ExpectedEffect(id, SnapshotFields.LexEntryDialectLabels, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryDialectLabelsOperationKinds.AddRefDialectLabels);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntry.DialectLabelsRS);
        return new ExpectedEffect(id, SnapshotFields.LexEntryDialectLabels, current, current);
    }
}

/// <summary>The <see cref="LexEntryDialectLabelsOperationKinds.RemoveRefDialectLabels"/> counterpart to
/// <see cref="LexEntryDialectLabelsAddRefHandler"/>.</summary>
internal sealed class LexEntryDialectLabelsRemoveRefHandler : IOperationHandler
{
    internal static readonly LexEntryDialectLabelsRemoveRefHandler Instance = new();
    private LexEntryDialectLabelsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryDialectLabelsOperationKinds.RemoveRefDialectLabels}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryDialectLabelsOperationKinds.RemoveRefDialectLabels}' requires 'after'.");
        }

        var memberId = LexEntryDialectLabelsMemberPayload.Parse(after, LexEntryDialectLabelsOperationKinds.RemoveRefDialectLabels);

        var (id, lexEntry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryDialectLabelsOperationKinds.RemoveRefDialectLabels);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntry.DialectLabelsRS);
        LexEntryDialectLabelsRemoveRefLowering.Apply(cache, lexEntry, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntry.DialectLabelsRS);

        return new ExpectedEffect(id, SnapshotFields.LexEntryDialectLabels, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntry) = TargetResolution.Resolve<ILexEntry>(cache, operation, LexEntryDialectLabelsOperationKinds.RemoveRefDialectLabels);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntry.DialectLabelsRS);
        return new ExpectedEffect(id, SnapshotFields.LexEntryDialectLabels, current, current);
    }
}
