// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source rows (Scope=in, DeclaringClass=MoAlloAdhocProhib): MoAlloAdhocProhib.FirstAllomorph (MoForm, rel/atomic), MoAlloAdhocProhib.Allomorphs (MoForm, rel/seq), MoAlloAdhocProhib.RestOfAllos (MoForm, rel/seq).
// </auto-generated>
using System.Collections.Generic;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.LCModel;

namespace SIL.Motif.Runner.Snapshotting;

/// <summary>
/// Reads a real <c>IMoAlloAdhocProhib</c>'s in-scope slice-2 relation/owning-atomic fields into
/// the LibLCM-free <see cref="ObjectSnapshot"/> projection. Sibling to the slice-1
/// <c>MoAlloAdhocProhibSnapshotter</c>; see this file's own remarks (RelationsSnapshotterEmitter.cs,
/// SIL.Motif.Generator) for why the two are not merged.
/// </summary>
public static class MoAlloAdhocProhibRelationsSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IMoAlloAdhocProhib moAlloAdhocProhib)
    {
        var canonicalId = CanonicalId.FromGuid(moAlloAdhocProhib.Guid);
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        AddIfPopulated(fields, SnapshotFields.MoAlloAdhocProhibFirstAllomorph, ReferenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.FirstAllomorphRA));
        AddIfPopulated(fields, SnapshotFields.MoAlloAdhocProhibAllomorphs, ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.AllomorphsRS));
        AddIfPopulated(fields, SnapshotFields.MoAlloAdhocProhibRestOfAllos, ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.RestOfAllosRS));

        return new ObjectSnapshot(canonicalId, fields);
    }

    private static void AddIfPopulated(
        Dictionary<string, IReadOnlyDictionary<string, string>> fields,
        string fieldName,
        IReadOnlyDictionary<string, string> alternatives)
    {
        if (alternatives.Count > 0)
            fields[fieldName] = alternatives;
    }
}
