// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source rows (Scope=in, DeclaringClass=PhSimpleContextNC): PhSimpleContextNC.FeatureStructure (PhNaturalClass, rel/atomic), PhSimpleContextNC.PlusConstr (PhFeatureConstraint, rel/seq), PhSimpleContextNC.MinusConstr (PhFeatureConstraint, rel/seq).
// </auto-generated>
using System.Collections.Generic;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.LCModel;

namespace SIL.Motif.Runner.Snapshotting;

/// <summary>
/// Reads a real <c>IPhSimpleContextNC</c>'s in-scope slice-2 relation/owning-atomic fields into
/// the LibLCM-free <see cref="ObjectSnapshot"/> projection. Sibling to the slice-1
/// <c>PhSimpleContextNCSnapshotter</c>; see this file's own remarks (RelationsSnapshotterEmitter.cs,
/// SIL.Motif.Generator) for why the two are not merged.
/// </summary>
public static class PhSimpleContextNCRelationsSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IPhSimpleContextNC phSimpleContextNC)
    {
        var canonicalId = CanonicalId.FromGuid(phSimpleContextNC.Guid);
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        AddIfPopulated(fields, SnapshotFields.PhSimpleContextNCFeatureStructure, ReferenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.FeatureStructureRA));
        AddIfPopulated(fields, SnapshotFields.PhSimpleContextNCPlusConstr, ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.PlusConstrRS));
        AddIfPopulated(fields, SnapshotFields.PhSimpleContextNCMinusConstr, ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.MinusConstrRS));

        return new ObjectSnapshot(canonicalId, fields);
    }

    private static void AddIfPopulated(
        Dictionary<string, IReadOnlyDictionary<string, string>> fields,
        string fieldName,
        IReadOnlyDictionary<string, string> alternatives)
    {
        if (alternatives.Count > 0)
            fields[fieldName] = alternatives;
    }
}
