// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: FsClosedValue.Value (rel/atomic FsSymFeatVal, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>FsClosedValue.Value</c> operation kinds.</summary>
public static class FsClosedValueValueOperationKinds
{
    public const string SetValue = "grammar/fsClosedValue/setValue";
    public const string ClearValue = "grammar/fsClosedValue/clearValue";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetValue);
        OperationKindRegistry.Register(ClearValue);
        OperationHandlerRegistry.Register(SetValue, FsClosedValueValueSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearValue, FsClosedValueValueClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsClosedValueValueOperationKinds.SetValue"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class FsClosedValueValueSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsClosedValueValueOperationKinds.SetValue);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsClosedValueValueOperationKinds.SetValue);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", FsClosedValueValueOperationKinds.SetValue);
    }
}

/// <summary>The <c>after</c> payload for <see cref="FsClosedValueValueOperationKinds.ClearValue"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class FsClosedValueValueClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, FsClosedValueValueOperationKinds.ClearValue);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, FsClosedValueValueOperationKinds.ClearValue);
    }
}

/// <summary>Lowers <see cref="FsClosedValueValueOperationKinds.SetValue"/>: resolves the
/// referenced IFsSymFeatVal and assigns it to <c>fsClosedValue.ValueRA</c>.</summary>
public static class FsClosedValueValueSetLowering
{
    public static void Apply(LcmCache cache, IFsClosedValue fsClosedValue, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<IFsSymFeatVal>(
            cache, value => fsClosedValue.ValueRA = value, refId, FsClosedValueValueOperationKinds.SetValue);
}

/// <summary>Lowers <see cref="FsClosedValueValueOperationKinds.ClearValue"/>: detaches
/// <c>fsClosedValue.ValueRA</c>.</summary>
public static class FsClosedValueValueClearLowering
{
    public static void Apply(IFsClosedValue fsClosedValue) =>
        ReferenceFieldLowering.ApplyClear<IFsSymFeatVal>(value => fsClosedValue.ValueRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="FsClosedValueValueOperationKinds.SetValue"/> operation.</summary>
internal sealed class FsClosedValueValueSetHandler : IOperationHandler
{
    internal static readonly FsClosedValueValueSetHandler Instance = new();
    private FsClosedValueValueSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsClosedValueValueOperationKinds.SetValue}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsClosedValueValueOperationKinds.SetValue}' requires 'after'.");
        }

        var refId = FsClosedValueValueSetPayload.Parse(after);

        var (id, fsClosedValue) = TargetResolution.Resolve<IFsClosedValue>(cache, operation, FsClosedValueValueOperationKinds.SetValue);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(fsClosedValue.ValueRA);
        FsClosedValueValueSetLowering.Apply(cache, fsClosedValue, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(fsClosedValue.ValueRA);

        return new ExpectedEffect(id, SnapshotFields.FsClosedValueValue, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsClosedValue) = TargetResolution.Resolve<IFsClosedValue>(cache, operation, FsClosedValueValueOperationKinds.SetValue);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(fsClosedValue.ValueRA);
        return new ExpectedEffect(id, SnapshotFields.FsClosedValueValue, current, current);
    }
}

/// <summary>The <see cref="FsClosedValueValueOperationKinds.ClearValue"/> counterpart to
/// <see cref="FsClosedValueValueSetHandler"/>.</summary>
internal sealed class FsClosedValueValueClearHandler : IOperationHandler
{
    internal static readonly FsClosedValueValueClearHandler Instance = new();
    private FsClosedValueValueClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsClosedValueValueOperationKinds.ClearValue}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsClosedValueValueOperationKinds.ClearValue}' requires 'after'.");
        }

        FsClosedValueValueClearPayload.Parse(after);

        var (id, fsClosedValue) = TargetResolution.Resolve<IFsClosedValue>(cache, operation, FsClosedValueValueOperationKinds.ClearValue);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(fsClosedValue.ValueRA);
        FsClosedValueValueClearLowering.Apply(fsClosedValue);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(fsClosedValue.ValueRA);

        return new ExpectedEffect(id, SnapshotFields.FsClosedValueValue, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsClosedValue) = TargetResolution.Resolve<IFsClosedValue>(cache, operation, FsClosedValueValueOperationKinds.ClearValue);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(fsClosedValue.ValueRA);
        return new ExpectedEffect(id, SnapshotFields.FsClosedValueValue, current, current);
    }
}
