// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the move operation kind for an ordered owning field.</summary>
public static class LexEntryAlternateFormsOperationKinds
{
    public const string MoveAlternateForms = "lexical/lexEntry/moveAlternateForms";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(MoveAlternateForms);
        OperationHandlerRegistry.Register(MoveAlternateForms, LexEntryAlternateFormsMoveHandler.Instance);
    }
}

/// <summary>Parses the member identity addressed by a move operation.</summary>
public static class LexEntryAlternateFormsMovePayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, LexEntryAlternateFormsOperationKinds.MoveAlternateForms);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, LexEntryAlternateFormsOperationKinds.MoveAlternateForms);
        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", LexEntryAlternateFormsOperationKinds.MoveAlternateForms);
    }
}

/// <summary>Moves an existing member by identity inside its ordered owning sequence.</summary>
public static class LexEntryAlternateFormsMoveLowering
{
    public static void Apply(ILexEntry owner, CanonicalId memberId, Placement placement) =>
        ReferenceSequenceFieldLowering.ApplyMove(
            owner.AlternateFormsOS, memberId, placement, LexEntryAlternateFormsOperationKinds.MoveAlternateForms);
}

internal sealed class LexEntryAlternateFormsMoveHandler : IOperationHandler
{
    internal static readonly LexEntryAlternateFormsMoveHandler Instance = new();
    private LexEntryAlternateFormsMoveHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation,
        List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{ LexEntryAlternateFormsOperationKinds.MoveAlternateForms }' requires 'target'.");
        if (operation.After is not { } after)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{ LexEntryAlternateFormsOperationKinds.MoveAlternateForms }' requires 'after'.");
        if (operation.Placement is not { } placement)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{ LexEntryAlternateFormsOperationKinds.MoveAlternateForms }' requires 'placement'.");

        var memberId = LexEntryAlternateFormsMovePayload.Parse(after);
        var (id, owner) = TargetResolution.Resolve<ILexEntry>(cache, operation,
            LexEntryAlternateFormsOperationKinds.MoveAlternateForms);
        touchedTargets.Add(id);
        var before = SIL.Motif.Runner.Snapshotting.ReferenceSequenceFieldSnapshotting.ReadAlternatives(owner.AlternateFormsOS);
        LexEntryAlternateFormsMoveLowering.Apply(owner, memberId, placement);
        var afterValue = SIL.Motif.Runner.Snapshotting.ReferenceSequenceFieldSnapshotting.ReadAlternatives(owner.AlternateFormsOS);
        return new ExpectedEffect(id, SnapshotFields.LexEntryAlternateForms, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, owner) = TargetResolution.Resolve<ILexEntry>(cache, operation,
            LexEntryAlternateFormsOperationKinds.MoveAlternateForms);
        var current = SIL.Motif.Runner.Snapshotting.ReferenceSequenceFieldSnapshotting.ReadAlternatives(owner.AlternateFormsOS);
        return new ExpectedEffect(id, SnapshotFields.LexEntryAlternateForms, current, current);
    }
}
