// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffixTemplate.Name (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflAffixTemplate.Name</c> operation kinds.</summary>
public static class MoInflAffixTemplateNameOperationKinds
{
    public const string SetName = "grammar/moInflAffixTemplate/setName";
    public const string ClearName = "grammar/moInflAffixTemplate/clearName";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetName);
        OperationKindRegistry.Register(ClearName);
        OperationHandlerRegistry.Register(SetName, MoInflAffixTemplateNameSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearName, MoInflAffixTemplateNameClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixTemplateNameOperationKinds.SetName"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffixTemplateNameSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixTemplateNameOperationKinds.SetName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixTemplateNameOperationKinds.SetName);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", MoInflAffixTemplateNameOperationKinds.SetName);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", MoInflAffixTemplateNameOperationKinds.SetName);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixTemplateNameOperationKinds.ClearName"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class MoInflAffixTemplateNameClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixTemplateNameOperationKinds.ClearName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixTemplateNameOperationKinds.ClearName);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", MoInflAffixTemplateNameOperationKinds.ClearName);
    }
}

/// <summary>Lowers <see cref="MoInflAffixTemplateNameOperationKinds.SetName"/>: sets one
/// writing-system alternative of <c>moInflAffixTemplate.Name</c>.</summary>
public static class MoInflAffixTemplateNameSetLowering
{
    public static void Apply(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, moInflAffixTemplate.Name, writingSystemTag, text, MoInflAffixTemplateNameOperationKinds.SetName);
}

/// <summary>Lowers <see cref="MoInflAffixTemplateNameOperationKinds.ClearName"/>: clears one
/// writing-system alternative of <c>moInflAffixTemplate.Name</c>.</summary>
public static class MoInflAffixTemplateNameClearLowering
{
    public static void Apply(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, moInflAffixTemplate.Name, writingSystemTag, MoInflAffixTemplateNameOperationKinds.ClearName);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffixTemplateNameOperationKinds.SetName"/> operation.</summary>
internal sealed class MoInflAffixTemplateNameSetHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplateNameSetHandler Instance = new();
    private MoInflAffixTemplateNameSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateNameOperationKinds.SetName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateNameOperationKinds.SetName}' requires 'after'.");
        }

        var (writingSystemTag, text) = MoInflAffixTemplateNameSetPayload.Parse(after);

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateNameOperationKinds.SetName);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixTemplate);
        MoInflAffixTemplateNameSetLowering.Apply(cache, moInflAffixTemplate, writingSystemTag, text);
        var afterValue = ReadField(cache, moInflAffixTemplate);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateNameOperationKinds.SetName);
        var current = ReadField(cache, moInflAffixTemplate);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate) =>
        MoInflAffixTemplateAuthoringSnapshotter.Snapshot(cache, moInflAffixTemplate).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixTemplateName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="MoInflAffixTemplateNameOperationKinds.ClearName"/> counterpart to
/// <see cref="MoInflAffixTemplateNameSetHandler"/>.</summary>
internal sealed class MoInflAffixTemplateNameClearHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplateNameClearHandler Instance = new();
    private MoInflAffixTemplateNameClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateNameOperationKinds.ClearName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplateNameOperationKinds.ClearName}' requires 'after'.");
        }

        var writingSystemTag = MoInflAffixTemplateNameClearPayload.Parse(after);

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateNameOperationKinds.ClearName);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixTemplate);
        MoInflAffixTemplateNameClearLowering.Apply(cache, moInflAffixTemplate, writingSystemTag);
        var afterValue = ReadField(cache, moInflAffixTemplate);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplateNameOperationKinds.ClearName);
        var current = ReadField(cache, moInflAffixTemplate);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplateName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate) =>
        MoInflAffixTemplateAuthoringSnapshotter.Snapshot(cache, moInflAffixTemplate).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixTemplateName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
