// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffixSlot.Name (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInflAffixSlot.Name</c> operation kinds.</summary>
public static class MoInflAffixSlotNameOperationKinds
{
    public const string SetName = "grammar/moInflAffixSlot/setName";
    public const string ClearName = "grammar/moInflAffixSlot/clearName";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetName);
        OperationKindRegistry.Register(ClearName);
        OperationHandlerRegistry.Register(SetName, MoInflAffixSlotNameSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearName, MoInflAffixSlotNameClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixSlotNameOperationKinds.SetName"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffixSlotNameSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixSlotNameOperationKinds.SetName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixSlotNameOperationKinds.SetName);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", MoInflAffixSlotNameOperationKinds.SetName);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", MoInflAffixSlotNameOperationKinds.SetName);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="MoInflAffixSlotNameOperationKinds.ClearName"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class MoInflAffixSlotNameClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, MoInflAffixSlotNameOperationKinds.ClearName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, MoInflAffixSlotNameOperationKinds.ClearName);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", MoInflAffixSlotNameOperationKinds.ClearName);
    }
}

/// <summary>Lowers <see cref="MoInflAffixSlotNameOperationKinds.SetName"/>: sets one
/// writing-system alternative of <c>moInflAffixSlot.Name</c>.</summary>
public static class MoInflAffixSlotNameSetLowering
{
    public static void Apply(LcmCache cache, IMoInflAffixSlot moInflAffixSlot, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, moInflAffixSlot.Name, writingSystemTag, text, MoInflAffixSlotNameOperationKinds.SetName);
}

/// <summary>Lowers <see cref="MoInflAffixSlotNameOperationKinds.ClearName"/>: clears one
/// writing-system alternative of <c>moInflAffixSlot.Name</c>.</summary>
public static class MoInflAffixSlotNameClearLowering
{
    public static void Apply(LcmCache cache, IMoInflAffixSlot moInflAffixSlot, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, moInflAffixSlot.Name, writingSystemTag, MoInflAffixSlotNameOperationKinds.ClearName);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffixSlotNameOperationKinds.SetName"/> operation.</summary>
internal sealed class MoInflAffixSlotNameSetHandler : IOperationHandler
{
    internal static readonly MoInflAffixSlotNameSetHandler Instance = new();
    private MoInflAffixSlotNameSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixSlotNameOperationKinds.SetName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixSlotNameOperationKinds.SetName}' requires 'after'.");
        }

        var (writingSystemTag, text) = MoInflAffixSlotNameSetPayload.Parse(after);

        var (id, moInflAffixSlot) = TargetResolution.Resolve<IMoInflAffixSlot>(cache, operation, MoInflAffixSlotNameOperationKinds.SetName);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixSlot);
        MoInflAffixSlotNameSetLowering.Apply(cache, moInflAffixSlot, writingSystemTag, text);
        var afterValue = ReadField(cache, moInflAffixSlot);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixSlotName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixSlot) = TargetResolution.Resolve<IMoInflAffixSlot>(cache, operation, MoInflAffixSlotNameOperationKinds.SetName);
        var current = ReadField(cache, moInflAffixSlot);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixSlotName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixSlot moInflAffixSlot) =>
        MoInflAffixSlotAuthoringSnapshotter.Snapshot(cache, moInflAffixSlot).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixSlotName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="MoInflAffixSlotNameOperationKinds.ClearName"/> counterpart to
/// <see cref="MoInflAffixSlotNameSetHandler"/>.</summary>
internal sealed class MoInflAffixSlotNameClearHandler : IOperationHandler
{
    internal static readonly MoInflAffixSlotNameClearHandler Instance = new();
    private MoInflAffixSlotNameClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixSlotNameOperationKinds.ClearName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixSlotNameOperationKinds.ClearName}' requires 'after'.");
        }

        var writingSystemTag = MoInflAffixSlotNameClearPayload.Parse(after);

        var (id, moInflAffixSlot) = TargetResolution.Resolve<IMoInflAffixSlot>(cache, operation, MoInflAffixSlotNameOperationKinds.ClearName);
        touchedTargets.Add(id);

        var before = ReadField(cache, moInflAffixSlot);
        MoInflAffixSlotNameClearLowering.Apply(cache, moInflAffixSlot, writingSystemTag);
        var afterValue = ReadField(cache, moInflAffixSlot);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixSlotName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixSlot) = TargetResolution.Resolve<IMoInflAffixSlot>(cache, operation, MoInflAffixSlotNameOperationKinds.ClearName);
        var current = ReadField(cache, moInflAffixSlot);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixSlotName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IMoInflAffixSlot moInflAffixSlot) =>
        MoInflAffixSlotAuthoringSnapshotter.Snapshot(cache, moInflAffixSlot).AlternativesFields
            .TryGetValue(SnapshotFields.MoInflAffixSlotName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
