// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Creates a member with an authored identity inside the caller's unit of work.</summary>
public static class PartOfSpeechAffixSlotsOperationKinds
{
    public const string Create = "grammar/partOfSpeech/createAffixSlots";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IPartOfSpeech>(
            Create, SnapshotFields.PartOfSpeechAffixSlots, owner => owner.AffixSlotsOC.Cast<ICmObject>().ToArray(),
            (cache, owner, guid, index, concreteClass) =>
            {
                var child = cache.ServiceLocator.GetInstance<IMoInflAffixSlotFactory>().Create(guid);
                        owner.AffixSlotsOC.Add(child);
            }, false, false, Array.Empty<string>(), "MoInflAffixSlot", true));
    }
}
