// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names creation and move operation kinds for this owned field.</summary>
public static class PartOfSpeechAffixTemplatesOperationKinds
{
    public const string Create = "grammar/partOfSpeech/createAffixTemplates";
    public const string MoveAffixTemplates = "grammar/partOfSpeech/moveAffixTemplates";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IPartOfSpeech>(
            Create, SnapshotFields.PartOfSpeechAffixTemplates, owner => owner.AffixTemplatesOS.Cast<ICmObject>().ToArray(),
            (cache, owner, guid, index, concreteClass) =>
            {
                var child = cache.ServiceLocator.GetInstance<IMoInflAffixTemplateFactory>().Create(guid);
                        owner.AffixTemplatesOS.Insert(index, child);
            }, true, false, Array.Empty<string>(), "MoInflAffixTemplate", true));
        OperationKindRegistry.Register(MoveAffixTemplates);
        OperationHandlerRegistry.Register(MoveAffixTemplates, PartOfSpeechAffixTemplatesMoveHandler.Instance);
    }
}

/// <summary>Parses the member identity addressed by a move operation.</summary>
public static class PartOfSpeechAffixTemplatesMovePayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PartOfSpeechAffixTemplatesOperationKinds.MoveAffixTemplates);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PartOfSpeechAffixTemplatesOperationKinds.MoveAffixTemplates);
        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", PartOfSpeechAffixTemplatesOperationKinds.MoveAffixTemplates);
    }
}

/// <summary>Moves an existing member by identity inside its ordered owning sequence.</summary>
public static class PartOfSpeechAffixTemplatesMoveLowering
{
    public static void Apply(IPartOfSpeech owner, CanonicalId memberId, Placement placement) =>
        ReferenceSequenceFieldLowering.ApplyMove(
            owner.AffixTemplatesOS, memberId, placement, PartOfSpeechAffixTemplatesOperationKinds.MoveAffixTemplates);
}

internal sealed class PartOfSpeechAffixTemplatesMoveHandler : IOperationHandler
{
    internal static readonly PartOfSpeechAffixTemplatesMoveHandler Instance = new();
    private PartOfSpeechAffixTemplatesMoveHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation,
        List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{ PartOfSpeechAffixTemplatesOperationKinds.MoveAffixTemplates }' requires 'target'.");
        if (operation.After is not { } after)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{ PartOfSpeechAffixTemplatesOperationKinds.MoveAffixTemplates }' requires 'after'.");
        if (operation.Placement is not { } placement)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{ PartOfSpeechAffixTemplatesOperationKinds.MoveAffixTemplates }' requires 'placement'.");

        var memberId = PartOfSpeechAffixTemplatesMovePayload.Parse(after);
        var (id, owner) = TargetResolution.Resolve<IPartOfSpeech>(cache, operation,
            PartOfSpeechAffixTemplatesOperationKinds.MoveAffixTemplates);
        touchedTargets.Add(id);
        var before = SIL.Motif.Runner.Snapshotting.ReferenceSequenceFieldSnapshotting.ReadAlternatives(owner.AffixTemplatesOS);
        PartOfSpeechAffixTemplatesMoveLowering.Apply(owner, memberId, placement);
        var afterValue = SIL.Motif.Runner.Snapshotting.ReferenceSequenceFieldSnapshotting.ReadAlternatives(owner.AffixTemplatesOS);
        return new ExpectedEffect(id, SnapshotFields.PartOfSpeechAffixTemplates, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, owner) = TargetResolution.Resolve<IPartOfSpeech>(cache, operation,
            PartOfSpeechAffixTemplatesOperationKinds.MoveAffixTemplates);
        var current = SIL.Motif.Runner.Snapshotting.ReferenceSequenceFieldSnapshotting.ReadAlternatives(owner.AffixTemplatesOS);
        return new ExpectedEffect(id, SnapshotFields.PartOfSpeechAffixTemplates, current, current);
    }
}
