// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using SIL.LCModel;
using SIL.LCModel.Core.Text;
using SIL.LCModel.Core.KernelInterfaces;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Runner.Composers;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>The parser-visible environment string, rather than the unused structured context graph.</summary>
public static class PhEnvironmentStringRepresentationOperationKinds
{
    public const string Set = "grammar/phEnvironment/setStringRepresentation";
    public const string Clear = "grammar/phEnvironment/clearStringRepresentation";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Set);
        OperationKindRegistry.Register(Clear);
        OperationHandlerRegistry.Register(Set, new EnvironmentStringHandler(false));
        OperationHandlerRegistry.Register(Clear, new EnvironmentStringHandler(true));
    }
}

internal sealed class EnvironmentStringHandler(bool clear) : IOperationHandler
{
    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        var after = operation.After ?? throw new InvalidOperationException("Environment string requires after.");
        ClosedPayloadParsing.RequireObject(after, operation.Kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, clear ? Array.Empty<string>() : new[] { "ws", "text", "left", "right" }, operation.Kind);
        var (id, environment) = TargetResolution.Resolve<IPhEnvironment>(cache, operation, operation.Kind);
        var before = Read(environment);
        if (clear) environment.StringRepresentation = null;
        else
        {
            var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", operation.Kind);
            var text = ClosedPayloadParsing.GetRequiredString(after, "text", operation.Kind);
            var left = AuthorEnvironmentIntentParser.Contexts(after, "left");
            var right = AuthorEnvironmentIntentParser.Contexts(after, "right");
            if (left.Length + right.Length == 0 || text != AuthorEnvironmentComposer.RenderPattern(cache, left, right))
                throw new InvalidOperationException("Environment references no longer match the authored string; author a fresh intent.");
            var handle = cache.WritingSystemFactory.GetWsFromStr(ws);
            if (handle != cache.DefaultVernWs)
                throw new InvalidOperationException("Environment string must use the first vernacular writing system.");
            environment.StringRepresentation = TsStringUtils.MakeString(text, handle);
        }
        touchedTargets.Add(id);
        return new ExpectedEffect(id, SnapshotFields.PhEnvironmentStringRepresentation, before, Read(environment));
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, environment) = TargetResolution.Resolve<IPhEnvironment>(cache, operation, operation.Kind);
        var current = Read(environment);
        return new ExpectedEffect(id, SnapshotFields.PhEnvironmentStringRepresentation, current, current);
    }

    private static Dictionary<string, string> Read(IPhEnvironment environment) =>
        string.IsNullOrEmpty(environment.StringRepresentation?.Text) ? new() : new()
        {
            ["text"] = environment.StringRepresentation.get_NormalizedForm(FwNormalizationMode.knmNFSC).Text,
        };
}
