// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhEnvironment.Name (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhEnvironment.Name</c> operation kinds.</summary>
public static class PhEnvironmentNameOperationKinds
{
    public const string SetName = "grammar/phEnvironment/setName";
    public const string ClearName = "grammar/phEnvironment/clearName";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetName);
        OperationKindRegistry.Register(ClearName);
        OperationHandlerRegistry.Register(SetName, PhEnvironmentNameSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearName, PhEnvironmentNameClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhEnvironmentNameOperationKinds.SetName"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class PhEnvironmentNameSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhEnvironmentNameOperationKinds.SetName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhEnvironmentNameOperationKinds.SetName);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", PhEnvironmentNameOperationKinds.SetName);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", PhEnvironmentNameOperationKinds.SetName);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhEnvironmentNameOperationKinds.ClearName"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class PhEnvironmentNameClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhEnvironmentNameOperationKinds.ClearName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhEnvironmentNameOperationKinds.ClearName);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", PhEnvironmentNameOperationKinds.ClearName);
    }
}

/// <summary>Lowers <see cref="PhEnvironmentNameOperationKinds.SetName"/>: sets one
/// writing-system alternative of <c>phEnvironment.Name</c>.</summary>
public static class PhEnvironmentNameSetLowering
{
    public static void Apply(LcmCache cache, IPhEnvironment phEnvironment, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, phEnvironment.Name, writingSystemTag, text, PhEnvironmentNameOperationKinds.SetName);
}

/// <summary>Lowers <see cref="PhEnvironmentNameOperationKinds.ClearName"/>: clears one
/// writing-system alternative of <c>phEnvironment.Name</c>.</summary>
public static class PhEnvironmentNameClearLowering
{
    public static void Apply(LcmCache cache, IPhEnvironment phEnvironment, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, phEnvironment.Name, writingSystemTag, PhEnvironmentNameOperationKinds.ClearName);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhEnvironmentNameOperationKinds.SetName"/> operation.</summary>
internal sealed class PhEnvironmentNameSetHandler : IOperationHandler
{
    internal static readonly PhEnvironmentNameSetHandler Instance = new();
    private PhEnvironmentNameSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhEnvironmentNameOperationKinds.SetName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhEnvironmentNameOperationKinds.SetName}' requires 'after'.");
        }

        var (writingSystemTag, text) = PhEnvironmentNameSetPayload.Parse(after);

        var (id, phEnvironment) = TargetResolution.Resolve<IPhEnvironment>(cache, operation, PhEnvironmentNameOperationKinds.SetName);
        touchedTargets.Add(id);

        var before = ReadField(cache, phEnvironment);
        PhEnvironmentNameSetLowering.Apply(cache, phEnvironment, writingSystemTag, text);
        var afterValue = ReadField(cache, phEnvironment);

        return new ExpectedEffect(id, SnapshotFields.PhEnvironmentName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phEnvironment) = TargetResolution.Resolve<IPhEnvironment>(cache, operation, PhEnvironmentNameOperationKinds.SetName);
        var current = ReadField(cache, phEnvironment);
        return new ExpectedEffect(id, SnapshotFields.PhEnvironmentName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhEnvironment phEnvironment) =>
        PhEnvironmentAuthoringSnapshotter.Snapshot(cache, phEnvironment).AlternativesFields
            .TryGetValue(SnapshotFields.PhEnvironmentName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="PhEnvironmentNameOperationKinds.ClearName"/> counterpart to
/// <see cref="PhEnvironmentNameSetHandler"/>.</summary>
internal sealed class PhEnvironmentNameClearHandler : IOperationHandler
{
    internal static readonly PhEnvironmentNameClearHandler Instance = new();
    private PhEnvironmentNameClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhEnvironmentNameOperationKinds.ClearName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhEnvironmentNameOperationKinds.ClearName}' requires 'after'.");
        }

        var writingSystemTag = PhEnvironmentNameClearPayload.Parse(after);

        var (id, phEnvironment) = TargetResolution.Resolve<IPhEnvironment>(cache, operation, PhEnvironmentNameOperationKinds.ClearName);
        touchedTargets.Add(id);

        var before = ReadField(cache, phEnvironment);
        PhEnvironmentNameClearLowering.Apply(cache, phEnvironment, writingSystemTag);
        var afterValue = ReadField(cache, phEnvironment);

        return new ExpectedEffect(id, SnapshotFields.PhEnvironmentName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phEnvironment) = TargetResolution.Resolve<IPhEnvironment>(cache, operation, PhEnvironmentNameOperationKinds.ClearName);
        var current = ReadField(cache, phEnvironment);
        return new ExpectedEffect(id, SnapshotFields.PhEnvironmentName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhEnvironment phEnvironment) =>
        PhEnvironmentAuthoringSnapshotter.Snapshot(cache, phEnvironment).AlternativesFields
            .TryGetValue(SnapshotFields.PhEnvironmentName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
