// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhNaturalClass.Name (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhNaturalClass.Name</c> operation kinds.</summary>
public static class PhNaturalClassNameOperationKinds
{
    public const string SetName = "grammar/phNaturalClass/setName";
    public const string ClearName = "grammar/phNaturalClass/clearName";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetName);
        OperationKindRegistry.Register(ClearName);
        OperationHandlerRegistry.Register(SetName, PhNaturalClassNameSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearName, PhNaturalClassNameClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhNaturalClassNameOperationKinds.SetName"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class PhNaturalClassNameSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhNaturalClassNameOperationKinds.SetName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhNaturalClassNameOperationKinds.SetName);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", PhNaturalClassNameOperationKinds.SetName);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", PhNaturalClassNameOperationKinds.SetName);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhNaturalClassNameOperationKinds.ClearName"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class PhNaturalClassNameClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhNaturalClassNameOperationKinds.ClearName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhNaturalClassNameOperationKinds.ClearName);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", PhNaturalClassNameOperationKinds.ClearName);
    }
}

/// <summary>Lowers <see cref="PhNaturalClassNameOperationKinds.SetName"/>: sets one
/// writing-system alternative of <c>phNaturalClass.Name</c>.</summary>
public static class PhNaturalClassNameSetLowering
{
    public static void Apply(LcmCache cache, IPhNaturalClass phNaturalClass, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, phNaturalClass.Name, writingSystemTag, text, PhNaturalClassNameOperationKinds.SetName);
}

/// <summary>Lowers <see cref="PhNaturalClassNameOperationKinds.ClearName"/>: clears one
/// writing-system alternative of <c>phNaturalClass.Name</c>.</summary>
public static class PhNaturalClassNameClearLowering
{
    public static void Apply(LcmCache cache, IPhNaturalClass phNaturalClass, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, phNaturalClass.Name, writingSystemTag, PhNaturalClassNameOperationKinds.ClearName);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhNaturalClassNameOperationKinds.SetName"/> operation.</summary>
internal sealed class PhNaturalClassNameSetHandler : IOperationHandler
{
    internal static readonly PhNaturalClassNameSetHandler Instance = new();
    private PhNaturalClassNameSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNaturalClassNameOperationKinds.SetName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNaturalClassNameOperationKinds.SetName}' requires 'after'.");
        }

        var (writingSystemTag, text) = PhNaturalClassNameSetPayload.Parse(after);

        var (id, phNaturalClass) = TargetResolution.Resolve<IPhNaturalClass>(cache, operation, PhNaturalClassNameOperationKinds.SetName);
        touchedTargets.Add(id);

        var before = ReadField(cache, phNaturalClass);
        PhNaturalClassNameSetLowering.Apply(cache, phNaturalClass, writingSystemTag, text);
        var afterValue = ReadField(cache, phNaturalClass);

        return new ExpectedEffect(id, SnapshotFields.PhNaturalClassName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phNaturalClass) = TargetResolution.Resolve<IPhNaturalClass>(cache, operation, PhNaturalClassNameOperationKinds.SetName);
        var current = ReadField(cache, phNaturalClass);
        return new ExpectedEffect(id, SnapshotFields.PhNaturalClassName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhNaturalClass phNaturalClass) =>
        PhNaturalClassAuthoringSnapshotter.Snapshot(cache, phNaturalClass).AlternativesFields
            .TryGetValue(SnapshotFields.PhNaturalClassName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="PhNaturalClassNameOperationKinds.ClearName"/> counterpart to
/// <see cref="PhNaturalClassNameSetHandler"/>.</summary>
internal sealed class PhNaturalClassNameClearHandler : IOperationHandler
{
    internal static readonly PhNaturalClassNameClearHandler Instance = new();
    private PhNaturalClassNameClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNaturalClassNameOperationKinds.ClearName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhNaturalClassNameOperationKinds.ClearName}' requires 'after'.");
        }

        var writingSystemTag = PhNaturalClassNameClearPayload.Parse(after);

        var (id, phNaturalClass) = TargetResolution.Resolve<IPhNaturalClass>(cache, operation, PhNaturalClassNameOperationKinds.ClearName);
        touchedTargets.Add(id);

        var before = ReadField(cache, phNaturalClass);
        PhNaturalClassNameClearLowering.Apply(cache, phNaturalClass, writingSystemTag);
        var afterValue = ReadField(cache, phNaturalClass);

        return new ExpectedEffect(id, SnapshotFields.PhNaturalClassName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phNaturalClass) = TargetResolution.Resolve<IPhNaturalClass>(cache, operation, PhNaturalClassNameOperationKinds.ClearName);
        var current = ReadField(cache, phNaturalClass);
        return new ExpectedEffect(id, SnapshotFields.PhNaturalClassName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhNaturalClass phNaturalClass) =>
        PhNaturalClassAuthoringSnapshotter.Snapshot(cache, phNaturalClass).AlternativesFields
            .TryGetValue(SnapshotFields.PhNaturalClassName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
