// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Creates a member with an authored identity inside the caller's unit of work.</summary>
public static class PhPhonemeSetBoundaryMarkersOperationKinds
{
    public const string Create = "grammar/phPhonemeSet/createBoundaryMarkers";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IPhPhonemeSet>(
            Create, SnapshotFields.PhPhonemeSetBoundaryMarkers, owner => owner.BoundaryMarkersOC.Cast<ICmObject>().ToArray(),
            (cache, owner, guid, index, concreteClass) =>
            {
                var child = cache.ServiceLocator.GetInstance<IPhBdryMarkerFactory>().Create(guid);
                        owner.BoundaryMarkersOC.Add(child);
                        foreach (var code in child.CodesOS.ToArray()) child.CodesOS.Remove(code);
            }, false, false, Array.Empty<string>(), "PhBdryMarker", true));
    }
}
