// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Creates a member with an authored identity inside the caller's unit of work.</summary>
public static class PhPhonDataEnvironmentsOperationKinds
{
    public const string Create = "grammar/phPhonData/createEnvironments";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IPhPhonData>(
            Create, SnapshotFields.PhPhonDataEnvironments, owner => owner.EnvironmentsOS.Cast<ICmObject>().ToArray(),
            (cache, owner, guid, index, concreteClass) =>
            {
                var child = cache.ServiceLocator.GetInstance<IPhEnvironmentFactory>().Create(guid);
                        owner.EnvironmentsOS.Insert(index, child);
            }, true, false, Array.Empty<string>(), "PhEnvironment", true));
    }
}
