// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Creates a member with an authored identity inside the caller's unit of work.</summary>
public static class PhPhonemeFeaturesOperationKinds
{
    public const string Create = "grammar/phPhoneme/createFeatures";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IPhPhoneme>(
            Create, SnapshotFields.PhPhonemeFeatures, owner => owner.FeaturesOA is { } child ? new ICmObject[] { child } : Array.Empty<ICmObject>(),
            (cache, owner, guid, index, concreteClass) =>
            {
                var child = cache.ServiceLocator.GetInstance<IFsFeatStrucFactory>().Create(guid);
                        owner.FeaturesOA = child;
            }, false, true, Array.Empty<string>(), "FsFeatStruc", true));
    }
}
