// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Creates a member with an authored identity inside the caller's unit of work.</summary>
public static class PhPhonDataNaturalClassesOperationKinds
{
    public const string Create = "grammar/phPhonData/createNaturalClasses";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IPhPhonData>(
            Create, SnapshotFields.PhPhonDataNaturalClasses, owner => owner.NaturalClassesOS.Cast<ICmObject>().ToArray(),
            (cache, owner, guid, index, concreteClass) =>
            {
                IPhNaturalClass child = concreteClass switch
                        {
                            "PhNCSegments" => cache.ServiceLocator.GetInstance<IPhNCSegmentsFactory>().Create(guid),
                            "PhNCFeatures" => cache.ServiceLocator.GetInstance<IPhNCFeaturesFactory>().Create(guid),
                            _ => throw new InvalidOperationException("Natural class must be PhNCSegments or PhNCFeatures."),
                        };
                        owner.NaturalClassesOS.Insert(index, child);
            }, true, false, new[] { "PhNCSegments", "PhNCFeatures" }, "PhNaturalClass", true));
    }
}
