// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names creation and move operation kinds for this owned field.</summary>
public static class PhPhonDataPhonRulesOperationKinds
{
    public const string Create = "grammar/phPhonData/createPhonRules";
    public const string MovePhonRules = "grammar/phPhonData/movePhonRules";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IPhPhonData>(
            Create, SnapshotFields.PhPhonDataPhonRules, owner => owner.PhonRulesOS.Cast<ICmObject>().ToArray(),
            (cache, owner, guid, index, concreteClass) =>
            {
                var child = cache.ServiceLocator.GetInstance<IPhRegularRuleFactory>().Create(guid);
                        child.Disabled = true;
                        owner.PhonRulesOS.Insert(index, child);
            }, true, false, new[] { "PhRegularRule" }, "PhSegmentRule", true));
        OperationKindRegistry.Register(MovePhonRules);
        OperationHandlerRegistry.Register(MovePhonRules, PhPhonDataPhonRulesMoveHandler.Instance);
    }
}

/// <summary>Parses the member identity addressed by a move operation.</summary>
public static class PhPhonDataPhonRulesMovePayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhPhonDataPhonRulesOperationKinds.MovePhonRules);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhPhonDataPhonRulesOperationKinds.MovePhonRules);
        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", PhPhonDataPhonRulesOperationKinds.MovePhonRules);
    }
}

/// <summary>Moves an existing member by identity inside its ordered owning sequence.</summary>
public static class PhPhonDataPhonRulesMoveLowering
{
    public static void Apply(IPhPhonData owner, CanonicalId memberId, Placement placement) =>
        ReferenceSequenceFieldLowering.ApplyMove(
            owner.PhonRulesOS, memberId, placement, PhPhonDataPhonRulesOperationKinds.MovePhonRules);
}

internal sealed class PhPhonDataPhonRulesMoveHandler : IOperationHandler
{
    internal static readonly PhPhonDataPhonRulesMoveHandler Instance = new();
    private PhPhonDataPhonRulesMoveHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation,
        List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{ PhPhonDataPhonRulesOperationKinds.MovePhonRules }' requires 'target'.");
        if (operation.After is not { } after)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{ PhPhonDataPhonRulesOperationKinds.MovePhonRules }' requires 'after'.");
        if (operation.Placement is not { } placement)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{ PhPhonDataPhonRulesOperationKinds.MovePhonRules }' requires 'placement'.");

        var memberId = PhPhonDataPhonRulesMovePayload.Parse(after);
        var (id, owner) = TargetResolution.Resolve<IPhPhonData>(cache, operation,
            PhPhonDataPhonRulesOperationKinds.MovePhonRules);
        touchedTargets.Add(id);
        var before = SIL.Motif.Runner.Snapshotting.ReferenceSequenceFieldSnapshotting.ReadAlternatives(owner.PhonRulesOS);
        PhPhonDataPhonRulesMoveLowering.Apply(owner, memberId, placement);
        var afterValue = SIL.Motif.Runner.Snapshotting.ReferenceSequenceFieldSnapshotting.ReadAlternatives(owner.PhonRulesOS);
        return new ExpectedEffect(id, SnapshotFields.PhPhonDataPhonRules, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, owner) = TargetResolution.Resolve<IPhPhonData>(cache, operation,
            PhPhonDataPhonRulesOperationKinds.MovePhonRules);
        var current = SIL.Motif.Runner.Snapshotting.ReferenceSequenceFieldSnapshotting.ReadAlternatives(owner.PhonRulesOS);
        return new ExpectedEffect(id, SnapshotFields.PhPhonDataPhonRules, current, current);
    }
}
