// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhSegmentRule.Name (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhSegmentRule.Name</c> operation kinds.</summary>
public static class PhSegmentRuleNameOperationKinds
{
    public const string SetName = "grammar/phSegmentRule/setName";
    public const string ClearName = "grammar/phSegmentRule/clearName";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetName);
        OperationKindRegistry.Register(ClearName);
        OperationHandlerRegistry.Register(SetName, PhSegmentRuleNameSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearName, PhSegmentRuleNameClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhSegmentRuleNameOperationKinds.SetName"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class PhSegmentRuleNameSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhSegmentRuleNameOperationKinds.SetName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhSegmentRuleNameOperationKinds.SetName);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", PhSegmentRuleNameOperationKinds.SetName);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", PhSegmentRuleNameOperationKinds.SetName);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhSegmentRuleNameOperationKinds.ClearName"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class PhSegmentRuleNameClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhSegmentRuleNameOperationKinds.ClearName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhSegmentRuleNameOperationKinds.ClearName);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", PhSegmentRuleNameOperationKinds.ClearName);
    }
}

/// <summary>Lowers <see cref="PhSegmentRuleNameOperationKinds.SetName"/>: sets one
/// writing-system alternative of <c>phSegmentRule.Name</c>.</summary>
public static class PhSegmentRuleNameSetLowering
{
    public static void Apply(LcmCache cache, IPhSegmentRule phSegmentRule, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, phSegmentRule.Name, writingSystemTag, text, PhSegmentRuleNameOperationKinds.SetName);
}

/// <summary>Lowers <see cref="PhSegmentRuleNameOperationKinds.ClearName"/>: clears one
/// writing-system alternative of <c>phSegmentRule.Name</c>.</summary>
public static class PhSegmentRuleNameClearLowering
{
    public static void Apply(LcmCache cache, IPhSegmentRule phSegmentRule, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, phSegmentRule.Name, writingSystemTag, PhSegmentRuleNameOperationKinds.ClearName);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhSegmentRuleNameOperationKinds.SetName"/> operation.</summary>
internal sealed class PhSegmentRuleNameSetHandler : IOperationHandler
{
    internal static readonly PhSegmentRuleNameSetHandler Instance = new();
    private PhSegmentRuleNameSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleNameOperationKinds.SetName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleNameOperationKinds.SetName}' requires 'after'.");
        }

        var (writingSystemTag, text) = PhSegmentRuleNameSetPayload.Parse(after);

        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleNameOperationKinds.SetName);
        touchedTargets.Add(id);

        var before = ReadField(cache, phSegmentRule);
        PhSegmentRuleNameSetLowering.Apply(cache, phSegmentRule, writingSystemTag, text);
        var afterValue = ReadField(cache, phSegmentRule);

        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleNameOperationKinds.SetName);
        var current = ReadField(cache, phSegmentRule);
        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhSegmentRule phSegmentRule) =>
        PhSegmentRuleAuthoringSnapshotter.Snapshot(cache, phSegmentRule).AlternativesFields
            .TryGetValue(SnapshotFields.PhSegmentRuleName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="PhSegmentRuleNameOperationKinds.ClearName"/> counterpart to
/// <see cref="PhSegmentRuleNameSetHandler"/>.</summary>
internal sealed class PhSegmentRuleNameClearHandler : IOperationHandler
{
    internal static readonly PhSegmentRuleNameClearHandler Instance = new();
    private PhSegmentRuleNameClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleNameOperationKinds.ClearName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleNameOperationKinds.ClearName}' requires 'after'.");
        }

        var writingSystemTag = PhSegmentRuleNameClearPayload.Parse(after);

        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleNameOperationKinds.ClearName);
        touchedTargets.Add(id);

        var before = ReadField(cache, phSegmentRule);
        PhSegmentRuleNameClearLowering.Apply(cache, phSegmentRule, writingSystemTag);
        var afterValue = ReadField(cache, phSegmentRule);

        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleNameOperationKinds.ClearName);
        var current = ReadField(cache, phSegmentRule);
        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhSegmentRule phSegmentRule) =>
        PhSegmentRuleAuthoringSnapshotter.Snapshot(cache, phSegmentRule).AlternativesFields
            .TryGetValue(SnapshotFields.PhSegmentRuleName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
