// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Creates a member with an authored identity inside the caller's unit of work.</summary>
public static class PhSegRuleRHSLeftContextOperationKinds
{
    public const string Create = "grammar/phSegRuleRHS/createLeftContext";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IPhSegRuleRHS>(
            Create, SnapshotFields.PhSegRuleRHSLeftContext, owner => owner.LeftContextOA is { } child ? new ICmObject[] { child } : Array.Empty<ICmObject>(),
            (cache, owner, guid, index, concreteClass) =>
            {
                IPhPhonContext child = concreteClass switch
                        {
                            "PhSimpleContextSeg" => cache.ServiceLocator.GetInstance<IPhSimpleContextSegFactory>().Create(guid),
                            "PhSimpleContextNC" => cache.ServiceLocator.GetInstance<IPhSimpleContextNCFactory>().Create(guid),
                            "PhSimpleContextBdry" => cache.ServiceLocator.GetInstance<IPhSimpleContextBdryFactory>().Create(guid),
                            "PhSequenceContext" => cache.ServiceLocator.GetInstance<IPhSequenceContextFactory>().Create(guid),
                            _ => throw new InvalidOperationException("Left context must be a supported simple or sequence context."),
                        };
                        owner.LeftContextOA = child;
            }, false, true, new[] { "PhSimpleContextSeg", "PhSimpleContextNC", "PhSimpleContextBdry", "PhSequenceContext" }, "PhPhonContext", true));
    }
}
