// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Creates a member with an authored identity inside the caller's unit of work.</summary>
public static class PhSegRuleRHSStrucChangeOperationKinds
{
    public const string Create = "grammar/phSegRuleRHS/createStrucChange";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IPhSegRuleRHS>(
            Create, SnapshotFields.PhSegRuleRHSStrucChange, owner => owner.StrucChangeOS.Cast<ICmObject>().ToArray(),
            (cache, owner, guid, index, concreteClass) =>
            {
                IPhSimpleContext child = concreteClass switch
                        {
                            "PhSimpleContextSeg" => cache.ServiceLocator.GetInstance<IPhSimpleContextSegFactory>().Create(guid),
                            "PhSimpleContextNC" => cache.ServiceLocator.GetInstance<IPhSimpleContextNCFactory>().Create(guid),
                            "PhSimpleContextBdry" => cache.ServiceLocator.GetInstance<IPhSimpleContextBdryFactory>().Create(guid),
                            _ => throw new InvalidOperationException("Structural change must be a supported simple context."),
                        };
                        owner.StrucChangeOS.Insert(index, child);
            }, true, false, new[] { "PhSimpleContextSeg", "PhSimpleContextNC", "PhSimpleContextBdry" }, "PhSimpleContext", true));
    }
}
