// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhSegmentRule.Direction (basic Integer, Verbs=set|clear; allowed values:
//   0 (LeftToRightIterative), 1 (RightToLeftIterative), 2 (Simultaneous)).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhSegmentRule.Direction</c> operation kinds.</summary>
public static class PhSegmentRuleDirectionOperationKinds
{
    public const string SetDirection = "grammar/phSegmentRule/setDirection";
    public const string ClearDirection = "grammar/phSegmentRule/clearDirection";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetDirection);
        OperationKindRegistry.Register(ClearDirection);
        OperationHandlerRegistry.Register(SetDirection, PhSegmentRuleDirectionSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearDirection, PhSegmentRuleDirectionClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhSegmentRuleDirectionOperationKinds.SetDirection"/>:
/// <c>{ "value": &lt;integer&gt; }</c>, where <c>value</c> must be one of
/// 0 (LeftToRightIterative), 1 (RightToLeftIterative), 2 (Simultaneous). Closed: any other property is rejected, and a <c>value</c>
/// outside that set is rejected here rather than clamped by LibLCM's own validation, which this
/// operation deliberately does not rely on.</summary>
public static class PhSegmentRuleDirectionSetPayload
{
    private static readonly string[] AllowedProperties = { "value" };
    private static readonly int[] AllowedValues = { 0, 1, 2 };

    public static int Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhSegmentRuleDirectionOperationKinds.SetDirection);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhSegmentRuleDirectionOperationKinds.SetDirection);

        var value = ClosedPayloadParsing.GetRequiredInteger(after, "value", PhSegmentRuleDirectionOperationKinds.SetDirection);
        if (Array.IndexOf(AllowedValues, value) < 0)
        {
            throw new ContractParseException(
                $"'{PhSegmentRuleDirectionOperationKinds.SetDirection}' operation 'after.value' ({value}) must be one of 0 (LeftToRightIterative), 1 (RightToLeftIterative), 2 (Simultaneous).");
        }

        return value;
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhSegmentRuleDirectionOperationKinds.ClearDirection"/>:
/// <c>{}</c>. Closed: any property at all is rejected — there is exactly one value to clear
/// to.</summary>
public static class PhSegmentRuleDirectionClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhSegmentRuleDirectionOperationKinds.ClearDirection);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhSegmentRuleDirectionOperationKinds.ClearDirection);
    }
}

/// <summary>Lowers <see cref="PhSegmentRuleDirectionOperationKinds.SetDirection"/>: the one LibLCM
/// write it performs, <c>phSegmentRule.Direction = value</c>.</summary>
public static class PhSegmentRuleDirectionSetLowering
{
    public static void Apply(IPhSegmentRule phSegmentRule, int value) => phSegmentRule.Direction = value;
}

/// <summary>Lowers <see cref="PhSegmentRuleDirectionOperationKinds.ClearDirection"/>: writes the enum's
/// zero member, <c>0</c> (LeftToRightIterative). Clearing this field retracts whatever judgement was
/// recorded; it does not erase the field, which has no absent state to erase to.</summary>
public static class PhSegmentRuleDirectionClearLowering
{
    public static void Apply(IPhSegmentRule phSegmentRule) => phSegmentRule.Direction = 0;
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhSegmentRuleDirectionOperationKinds.SetDirection"/> operation.</summary>
internal sealed class PhSegmentRuleDirectionSetHandler : IOperationHandler
{
    internal static readonly PhSegmentRuleDirectionSetHandler Instance = new();
    private PhSegmentRuleDirectionSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleDirectionOperationKinds.SetDirection}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleDirectionOperationKinds.SetDirection}' requires 'after'.");
        }

        var desired = PhSegmentRuleDirectionSetPayload.Parse(after);

        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleDirectionOperationKinds.SetDirection);
        touchedTargets.Add(id);

        var before = ReadField(cache, phSegmentRule);
        PhSegmentRuleDirectionSetLowering.Apply(phSegmentRule, desired);
        var afterValue = ReadField(cache, phSegmentRule);

        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleDirection, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleDirectionOperationKinds.SetDirection);
        var current = ReadField(cache, phSegmentRule);
        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleDirection, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhSegmentRule phSegmentRule) =>
        PhSegmentRuleDirectionSnapshotter.Snapshot(cache, phSegmentRule).AlternativesFields
            .TryGetValue(SnapshotFields.PhSegmentRuleDirection, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="PhSegmentRuleDirectionOperationKinds.ClearDirection"/> counterpart to
/// <see cref="PhSegmentRuleDirectionSetHandler"/>.</summary>
internal sealed class PhSegmentRuleDirectionClearHandler : IOperationHandler
{
    internal static readonly PhSegmentRuleDirectionClearHandler Instance = new();
    private PhSegmentRuleDirectionClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleDirectionOperationKinds.ClearDirection}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleDirectionOperationKinds.ClearDirection}' requires 'after'.");
        }

        PhSegmentRuleDirectionClearPayload.Parse(after);

        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleDirectionOperationKinds.ClearDirection);
        touchedTargets.Add(id);

        var before = ReadField(cache, phSegmentRule);
        PhSegmentRuleDirectionClearLowering.Apply(phSegmentRule);
        var afterValue = ReadField(cache, phSegmentRule);

        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleDirection, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleDirectionOperationKinds.ClearDirection);
        var current = ReadField(cache, phSegmentRule);
        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleDirection, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhSegmentRule phSegmentRule) =>
        PhSegmentRuleDirectionSnapshotter.Snapshot(cache, phSegmentRule).AlternativesFields
            .TryGetValue(SnapshotFields.PhSegmentRuleDirection, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
