// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhTerminalUnit.Name (basic MultiUnicode, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhTerminalUnit.Name</c> operation kinds.</summary>
public static class PhTerminalUnitNameOperationKinds
{
    public const string SetName = "grammar/phTerminalUnit/setName";
    public const string ClearName = "grammar/phTerminalUnit/clearName";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetName);
        OperationKindRegistry.Register(ClearName);
        OperationHandlerRegistry.Register(SetName, PhTerminalUnitNameSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearName, PhTerminalUnitNameClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhTerminalUnitNameOperationKinds.SetName"/>:
/// <c>{ "ws": "...", "text": "..." }</c>. Closed: any other property is rejected.</summary>
public static class PhTerminalUnitNameSetPayload
{
    private static readonly string[] AllowedProperties = { "ws", "text" };

    public static (string WritingSystemTag, string Text) Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhTerminalUnitNameOperationKinds.SetName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhTerminalUnitNameOperationKinds.SetName);

        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", PhTerminalUnitNameOperationKinds.SetName);
        var text = ClosedPayloadParsing.GetRequiredString(after, "text", PhTerminalUnitNameOperationKinds.SetName);
        return (ws, text);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhTerminalUnitNameOperationKinds.ClearName"/>:
/// <c>{ "ws": "..." }</c>. Closed: any other property (in particular <c>text</c>) is rejected.</summary>
public static class PhTerminalUnitNameClearPayload
{
    private static readonly string[] AllowedProperties = { "ws" };

    public static string Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhTerminalUnitNameOperationKinds.ClearName);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhTerminalUnitNameOperationKinds.ClearName);

        return ClosedPayloadParsing.GetRequiredString(after, "ws", PhTerminalUnitNameOperationKinds.ClearName);
    }
}

/// <summary>Lowers <see cref="PhTerminalUnitNameOperationKinds.SetName"/>: sets one
/// writing-system alternative of <c>phTerminalUnit.Name</c>.</summary>
public static class PhTerminalUnitNameSetLowering
{
    public static void Apply(LcmCache cache, IPhTerminalUnit phTerminalUnit, string writingSystemTag, string text) =>
        MultiAlternativesFieldLowering.ApplySet(
            cache, phTerminalUnit.Name, writingSystemTag, text, PhTerminalUnitNameOperationKinds.SetName);
}

/// <summary>Lowers <see cref="PhTerminalUnitNameOperationKinds.ClearName"/>: clears one
/// writing-system alternative of <c>phTerminalUnit.Name</c>.</summary>
public static class PhTerminalUnitNameClearLowering
{
    public static void Apply(LcmCache cache, IPhTerminalUnit phTerminalUnit, string writingSystemTag) =>
        MultiAlternativesFieldLowering.ApplyClear(
            cache, phTerminalUnit.Name, writingSystemTag, PhTerminalUnitNameOperationKinds.ClearName);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhTerminalUnitNameOperationKinds.SetName"/> operation.</summary>
internal sealed class PhTerminalUnitNameSetHandler : IOperationHandler
{
    internal static readonly PhTerminalUnitNameSetHandler Instance = new();
    private PhTerminalUnitNameSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhTerminalUnitNameOperationKinds.SetName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhTerminalUnitNameOperationKinds.SetName}' requires 'after'.");
        }

        var (writingSystemTag, text) = PhTerminalUnitNameSetPayload.Parse(after);

        var (id, phTerminalUnit) = TargetResolution.Resolve<IPhTerminalUnit>(cache, operation, PhTerminalUnitNameOperationKinds.SetName);
        touchedTargets.Add(id);

        var before = ReadField(cache, phTerminalUnit);
        PhTerminalUnitNameSetLowering.Apply(cache, phTerminalUnit, writingSystemTag, text);
        var afterValue = ReadField(cache, phTerminalUnit);

        return new ExpectedEffect(id, SnapshotFields.PhTerminalUnitName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phTerminalUnit) = TargetResolution.Resolve<IPhTerminalUnit>(cache, operation, PhTerminalUnitNameOperationKinds.SetName);
        var current = ReadField(cache, phTerminalUnit);
        return new ExpectedEffect(id, SnapshotFields.PhTerminalUnitName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhTerminalUnit phTerminalUnit) =>
        PhTerminalUnitAuthoringSnapshotter.Snapshot(cache, phTerminalUnit).AlternativesFields
            .TryGetValue(SnapshotFields.PhTerminalUnitName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="PhTerminalUnitNameOperationKinds.ClearName"/> counterpart to
/// <see cref="PhTerminalUnitNameSetHandler"/>.</summary>
internal sealed class PhTerminalUnitNameClearHandler : IOperationHandler
{
    internal static readonly PhTerminalUnitNameClearHandler Instance = new();
    private PhTerminalUnitNameClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhTerminalUnitNameOperationKinds.ClearName}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhTerminalUnitNameOperationKinds.ClearName}' requires 'after'.");
        }

        var writingSystemTag = PhTerminalUnitNameClearPayload.Parse(after);

        var (id, phTerminalUnit) = TargetResolution.Resolve<IPhTerminalUnit>(cache, operation, PhTerminalUnitNameOperationKinds.ClearName);
        touchedTargets.Add(id);

        var before = ReadField(cache, phTerminalUnit);
        PhTerminalUnitNameClearLowering.Apply(cache, phTerminalUnit, writingSystemTag);
        var afterValue = ReadField(cache, phTerminalUnit);

        return new ExpectedEffect(id, SnapshotFields.PhTerminalUnitName, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phTerminalUnit) = TargetResolution.Resolve<IPhTerminalUnit>(cache, operation, PhTerminalUnitNameOperationKinds.ClearName);
        var current = ReadField(cache, phTerminalUnit);
        return new ExpectedEffect(id, SnapshotFields.PhTerminalUnitName, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhTerminalUnit phTerminalUnit) =>
        PhTerminalUnitAuthoringSnapshotter.Snapshot(cache, phTerminalUnit).AlternativesFields
            .TryGetValue(SnapshotFields.PhTerminalUnitName, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
