// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;

namespace SIL.Motif.Runner.Operations;

/// <summary>Creates a member with an authored identity inside the caller's unit of work.</summary>
public static class StTextParagraphsOperationKinds
{
    public const string Create = "system/stText/createParagraphs";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Create);
        OperationHandlerRegistry.Register(Create, new OwningCreateHandler<IStText>(
            Create, SnapshotFields.StTextParagraphs, owner => owner.ParagraphsOS.Cast<ICmObject>().ToArray(),
            (cache, owner, guid, index, concreteClass) =>
            {
                IStPara child = concreteClass switch
                        {
                            "StTxtPara" => cache.ServiceLocator.GetInstance<IStTxtParaFactory>().Create(guid),
                            _ => throw new InvalidOperationException("Paragraph must be StTxtPara."),
                        };
                        owner.ParagraphsOS.Insert(index, child);
            }, true, false, new[] { "StTxtPara" }, "StPara", true));
    }
}
