// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source rows (Scope=in, Kind=basic, Sig=Integer, Verbs=set, DeclaringClass=PhSegmentRule):
//   PhSegmentRule.Direction (Integer).
// </auto-generated>
using System.Collections.Generic;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.LCModel;

namespace SIL.Motif.Runner.Snapshotting;

/// <summary>
/// Reads a real <c>IPhSegmentRule</c>'s basic-Integer-enum fields into the
/// LibLCM-free <see cref="ObjectSnapshot"/> projection.
/// </summary>
public static class PhSegmentRuleDirectionSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IPhSegmentRule phSegmentRule)
    {
        var canonicalId = CanonicalId.FromGuid(phSegmentRule.Guid);
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        fields[SnapshotFields.PhSegmentRuleDirection] = IntegerFieldAlternatives.ToAlternatives(phSegmentRule.Direction);

        return new ObjectSnapshot(canonicalId, fields);
    }
}
