namespace SIL.Motif.Generator.Emit;

/// <summary>
/// Emits one <c>Operations/Generated/{DeclaringClass}{FieldName}.g.cs</c> file for a Boolean basic
/// field. Payload shape (a documented choice, not pinned by any prior test): every payload in this
/// catalog is a JSON object so the closed-schema "reject unknown properties" check is meaningful
/// uniformly — <c>set</c> carries <c>{ "value": &lt;bool&gt; }</c>; <c>clear</c> carries <c>{}</c>
/// and resets the field to its CLR default, <c>false</c>, the closest Boolean analog of "omission
/// means absent" for a type with no null state.
/// </summary>
public static class BooleanFieldEmitter
{
    public static string Render(BasicFieldSpec spec)
    {
        var prefix = spec.SnapshotFieldConstant;
        var varName = spec.Construct;
        var activationGuard = spec.DeclaringClass == "PhSegmentRule" && spec.FieldName == "Disabled";

        return Template
            .Replace("__PREFIX__", prefix)
            .Replace("__DECLARINGCLASS__", spec.DeclaringClass)
            .Replace("__FIELDNAME__", spec.FieldName)
            .Replace("__SIG__", spec.Sig)
            .Replace("__SETKIND__", spec.SetKind)
            .Replace("__CLEARKIND__", spec.ClearKind)
            .Replace("__TARGETIFACE__", spec.TargetInterface)
            .Replace("__VAR__", varName)
            .Replace("__SNAPSHOTTER__", spec.DeclaringClass + "Snapshotter")
            .Replace("__SNAPSHOTFIELD__", "SnapshotFields." + prefix)
            .Replace("__SETGUARD__", activationGuard
                ? $"if (!desired) RegularRuleActivationGuard.RequireComplete({varName});\n                "
                : string.Empty)
            .Replace("__CLEARGUARD__", activationGuard
                ? $"RegularRuleActivationGuard.RequireComplete({varName});\n                "
                : string.Empty);
    }

    private const string Template = """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command.
        //   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
        //   manifest or MasterLCModel.xml change, and check in the result.
        //
        //   Source: __DECLARINGCLASS__.__FIELDNAME__ (basic __SIG__, Verbs=set|clear).
        // </auto-generated>
        using System;
        using System.Collections.Generic;
        using System.Runtime.CompilerServices;
        using System.Text.Json;
        using SIL.Motif.Contract.Ids;
        using SIL.Motif.Contract.Model;
        using SIL.Motif.Contract.Parsing;
        using SIL.Motif.Model.Effects;
        using SIL.Motif.Model.Snapshot;
        using SIL.Motif.Runner.Snapshotting;
        using SIL.LCModel;

        namespace SIL.Motif.Runner.Operations;

        /// <summary>Names the two <c>__DECLARINGCLASS__.__FIELDNAME__</c> operation kinds.</summary>
        public static class __PREFIX__OperationKinds
        {
            public const string Set__FIELDNAME__ = "__SETKIND__";
            public const string Clear__FIELDNAME__ = "__CLEARKIND__";

            [ModuleInitializer]
            internal static void Register()
            {
                OperationKindRegistry.Register(Set__FIELDNAME__);
                OperationKindRegistry.Register(Clear__FIELDNAME__);
                OperationHandlerRegistry.Register(Set__FIELDNAME__, __PREFIX__SetHandler.Instance);
                OperationHandlerRegistry.Register(Clear__FIELDNAME__, __PREFIX__ClearHandler.Instance);
            }
        }

        /// <summary>The <c>after</c> payload for <see cref="__PREFIX__OperationKinds.Set__FIELDNAME__"/>:
        /// <c>{ "value": true|false }</c>. Closed: any other property is rejected.</summary>
        public static class __PREFIX__SetPayload
        {
            private static readonly string[] AllowedProperties = { "value" };

            public static bool Parse(JsonElement after)
            {
                ClosedPayloadParsing.RequireObject(after, __PREFIX__OperationKinds.Set__FIELDNAME__);
                ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, __PREFIX__OperationKinds.Set__FIELDNAME__);

                return ClosedPayloadParsing.GetRequiredBoolean(after, "value", __PREFIX__OperationKinds.Set__FIELDNAME__);
            }
        }

        /// <summary>The <c>after</c> payload for <see cref="__PREFIX__OperationKinds.Clear__FIELDNAME__"/>:
        /// <c>{}</c>. Closed: any property at all is rejected — there is exactly one value to clear.</summary>
        public static class __PREFIX__ClearPayload
        {
            private static readonly string[] AllowedProperties = Array.Empty<string>();

            public static void Parse(JsonElement after)
            {
                ClosedPayloadParsing.RequireObject(after, __PREFIX__OperationKinds.Clear__FIELDNAME__);
                ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, __PREFIX__OperationKinds.Clear__FIELDNAME__);
            }
        }

        /// <summary>Lowers <see cref="__PREFIX__OperationKinds.Set__FIELDNAME__"/>: the one LibLCM
        /// write it performs, <c>__VAR__.__FIELDNAME__ = value</c>.</summary>
        public static class __PREFIX__SetLowering
        {
            public static void Apply(__TARGETIFACE__ __VAR__, bool value) => __VAR__.__FIELDNAME__ = value;
        }

        /// <summary>Lowers <see cref="__PREFIX__OperationKinds.Clear__FIELDNAME__"/>: resets
        /// <c>__VAR__.__FIELDNAME__</c> to <c>false</c>.</summary>
        public static class __PREFIX__ClearLowering
        {
            public static void Apply(__TARGETIFACE__ __VAR__) => __VAR__.__FIELDNAME__ = false;
        }

        /// <summary>Resolves, snapshots, lowers, and re-snapshots one
        /// <see cref="__PREFIX__OperationKinds.Set__FIELDNAME__"/> operation.</summary>
        internal sealed class __PREFIX__SetHandler : IOperationHandler
        {
            internal static readonly __PREFIX__SetHandler Instance = new();
            private __PREFIX__SetHandler() { }

            public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
            {
                if (operation.Target is not { })
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.Set__FIELDNAME__}' requires 'target'.");
                }

                if (operation.After is not { } after)
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.Set__FIELDNAME__}' requires 'after'.");
                }

                var desired = __PREFIX__SetPayload.Parse(after);

                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.Set__FIELDNAME__);
                touchedTargets.Add(id);

                var before = ReadField(cache, __VAR__);
                __SETGUARD____PREFIX__SetLowering.Apply(__VAR__, desired);
                var afterValue = ReadField(cache, __VAR__);

                return new ExpectedEffect(id, __SNAPSHOTFIELD__, before, afterValue);
            }

            public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
            {
                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.Set__FIELDNAME__);
                var current = ReadField(cache, __VAR__);
                return new ExpectedEffect(id, __SNAPSHOTFIELD__, current, current);
            }

            private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, __TARGETIFACE__ __VAR__) =>
                __SNAPSHOTTER__.Snapshot(cache, __VAR__).AlternativesFields
                    .TryGetValue(__SNAPSHOTFIELD__, out var alternatives)
                    ? alternatives
                    : new Dictionary<string, string>();
        }

        /// <summary>The <see cref="__PREFIX__OperationKinds.Clear__FIELDNAME__"/> counterpart to
        /// <see cref="__PREFIX__SetHandler"/>.</summary>
        internal sealed class __PREFIX__ClearHandler : IOperationHandler
        {
            internal static readonly __PREFIX__ClearHandler Instance = new();
            private __PREFIX__ClearHandler() { }

            public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
            {
                if (operation.Target is not { })
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.Clear__FIELDNAME__}' requires 'target'.");
                }

                if (operation.After is not { } after)
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.Clear__FIELDNAME__}' requires 'after'.");
                }

                __PREFIX__ClearPayload.Parse(after);

                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.Clear__FIELDNAME__);
                touchedTargets.Add(id);

                var before = ReadField(cache, __VAR__);
                __CLEARGUARD____PREFIX__ClearLowering.Apply(__VAR__);
                var afterValue = ReadField(cache, __VAR__);

                return new ExpectedEffect(id, __SNAPSHOTFIELD__, before, afterValue);
            }

            public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
            {
                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.Clear__FIELDNAME__);
                var current = ReadField(cache, __VAR__);
                return new ExpectedEffect(id, __SNAPSHOTFIELD__, current, current);
            }

            private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, __TARGETIFACE__ __VAR__) =>
                __SNAPSHOTTER__.Snapshot(cache, __VAR__).AlternativesFields
                    .TryGetValue(__SNAPSHOTFIELD__, out var alternatives)
                    ? alternatives
                    : new Dictionary<string, string>();
        }

        """;
}
