namespace SIL.Motif.Generator.Emit;

/// <summary>
/// Emits one <c>Operations/Generated4/{DeclaringClass}{FieldName}.g.cs</c> file for a basic-Integer-enum
/// field: two kind constants, two closed payload parsers — the <c>set</c> one also range-checking the
/// value against the field's <see cref="IntegerEnumFieldSpec.EnumMembers"/> — two lowering methods, and
/// two <see cref="Runner.Operations.IOperationHandler"/> implementations. The direct analogue of
/// <see cref="BooleanFieldEmitter"/>, generalized to any target class/field of this shape.
/// </summary>
/// <remarks>
/// The range check is the point of this shape existing separately from <see cref="BooleanFieldEmitter"/>:
/// LibLCM's own <c>WfiWordform.ValidateSpellingStatus</c> exists but a caller must not depend on it to
/// silently fix an out-of-range value, so the generated payload parser throws on one before it ever
/// reaches a lowering call. <c>clear</c> writes the enum's zero member, which is guaranteed to be one
/// of the confirmed values — so the two verbs cannot disagree about what is legal.
/// </remarks>
public static class IntegerEnumFieldEmitter
{
    public static string Render(IntegerEnumFieldSpec spec)
    {
        var prefix = spec.SnapshotFieldConstant; // e.g. "WfiWordformSpellingStatus"
        var varName = spec.Construct; // e.g. "wfiWordform" -- lowerFirst(DeclaringClass)
        var allowedValuesLiteral = string.Join(", ", spec.EnumMembers.Select(m => m.Value));
        var allowedValuesDescription = string.Join(", ", spec.EnumMembers.Select(m => $"{m.Value} ({m.Name})"));

        return Template
            .Replace("__PREFIX__", prefix)
            .Replace("__DECLARINGCLASS__", spec.DeclaringClass)
            .Replace("__FIELDNAME__", spec.FieldName)
            .Replace("__SIG__", spec.Sig)
            .Replace("__SETKIND__", spec.SetKind)
            .Replace("__CLEARKIND__", spec.ClearKind)
            .Replace("__TARGETIFACE__", spec.TargetInterface)
            .Replace("__VAR__", varName)
            .Replace("__SNAPSHOTTER__", spec.SnapshotterTypeName ?? spec.DeclaringClass + "Snapshotter")
            .Replace("__SNAPSHOTFIELD__", "SnapshotFields." + prefix)
            .Replace("__ALLOWEDVALUESLITERAL__", allowedValuesLiteral)
            .Replace("__ALLOWEDVALUESDESCRIPTION__", allowedValuesDescription)
            .Replace("__ZEROMEMBER__", spec.ZeroMemberName);
    }

    private const string Template = """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command.
        //   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
        //   manifest or MasterLCModel.xml change, and check in the result.
        //
        //   Source: __DECLARINGCLASS__.__FIELDNAME__ (basic __SIG__, Verbs=set|clear; allowed values:
        //   __ALLOWEDVALUESDESCRIPTION__).
        // </auto-generated>
        using System;
        using System.Collections.Generic;
        using System.Runtime.CompilerServices;
        using System.Text.Json;
        using SIL.Motif.Contract.Ids;
        using SIL.Motif.Contract.Model;
        using SIL.Motif.Contract.Parsing;
        using SIL.Motif.Model.Effects;
        using SIL.Motif.Model.Snapshot;
        using SIL.Motif.Runner.Snapshotting;
        using SIL.LCModel;

        namespace SIL.Motif.Runner.Operations;

        /// <summary>Names the two <c>__DECLARINGCLASS__.__FIELDNAME__</c> operation kinds.</summary>
        public static class __PREFIX__OperationKinds
        {
            public const string Set__FIELDNAME__ = "__SETKIND__";
            public const string Clear__FIELDNAME__ = "__CLEARKIND__";

            [ModuleInitializer]
            internal static void Register()
            {
                OperationKindRegistry.Register(Set__FIELDNAME__);
                OperationKindRegistry.Register(Clear__FIELDNAME__);
                OperationHandlerRegistry.Register(Set__FIELDNAME__, __PREFIX__SetHandler.Instance);
                OperationHandlerRegistry.Register(Clear__FIELDNAME__, __PREFIX__ClearHandler.Instance);
            }
        }

        /// <summary>The <c>after</c> payload for <see cref="__PREFIX__OperationKinds.Set__FIELDNAME__"/>:
        /// <c>{ "value": &lt;integer&gt; }</c>, where <c>value</c> must be one of
        /// __ALLOWEDVALUESDESCRIPTION__. Closed: any other property is rejected, and a <c>value</c>
        /// outside that set is rejected here rather than clamped by LibLCM's own validation, which this
        /// operation deliberately does not rely on.</summary>
        public static class __PREFIX__SetPayload
        {
            private static readonly string[] AllowedProperties = { "value" };
            private static readonly int[] AllowedValues = { __ALLOWEDVALUESLITERAL__ };

            public static int Parse(JsonElement after)
            {
                ClosedPayloadParsing.RequireObject(after, __PREFIX__OperationKinds.Set__FIELDNAME__);
                ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, __PREFIX__OperationKinds.Set__FIELDNAME__);

                var value = ClosedPayloadParsing.GetRequiredInteger(after, "value", __PREFIX__OperationKinds.Set__FIELDNAME__);
                if (Array.IndexOf(AllowedValues, value) < 0)
                {
                    throw new ContractParseException(
                        $"'{__PREFIX__OperationKinds.Set__FIELDNAME__}' operation 'after.value' ({value}) must be one of __ALLOWEDVALUESDESCRIPTION__.");
                }

                return value;
            }
        }

        /// <summary>The <c>after</c> payload for <see cref="__PREFIX__OperationKinds.Clear__FIELDNAME__"/>:
        /// <c>{}</c>. Closed: any property at all is rejected — there is exactly one value to clear
        /// to.</summary>
        public static class __PREFIX__ClearPayload
        {
            private static readonly string[] AllowedProperties = Array.Empty<string>();

            public static void Parse(JsonElement after)
            {
                ClosedPayloadParsing.RequireObject(after, __PREFIX__OperationKinds.Clear__FIELDNAME__);
                ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, __PREFIX__OperationKinds.Clear__FIELDNAME__);
            }
        }

        /// <summary>Lowers <see cref="__PREFIX__OperationKinds.Set__FIELDNAME__"/>: the one LibLCM
        /// write it performs, <c>__VAR__.__FIELDNAME__ = value</c>.</summary>
        public static class __PREFIX__SetLowering
        {
            public static void Apply(__TARGETIFACE__ __VAR__, int value) => __VAR__.__FIELDNAME__ = value;
        }

        /// <summary>Lowers <see cref="__PREFIX__OperationKinds.Clear__FIELDNAME__"/>: writes the enum's
        /// zero member, <c>0</c> (__ZEROMEMBER__). Clearing this field retracts whatever judgement was
        /// recorded; it does not erase the field, which has no absent state to erase to.</summary>
        public static class __PREFIX__ClearLowering
        {
            public static void Apply(__TARGETIFACE__ __VAR__) => __VAR__.__FIELDNAME__ = 0;
        }

        /// <summary>Resolves, snapshots, lowers, and re-snapshots one
        /// <see cref="__PREFIX__OperationKinds.Set__FIELDNAME__"/> operation.</summary>
        internal sealed class __PREFIX__SetHandler : IOperationHandler
        {
            internal static readonly __PREFIX__SetHandler Instance = new();
            private __PREFIX__SetHandler() { }

            public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
            {
                if (operation.Target is not { })
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.Set__FIELDNAME__}' requires 'target'.");
                }

                if (operation.After is not { } after)
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.Set__FIELDNAME__}' requires 'after'.");
                }

                var desired = __PREFIX__SetPayload.Parse(after);

                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.Set__FIELDNAME__);
                touchedTargets.Add(id);

                var before = ReadField(cache, __VAR__);
                __PREFIX__SetLowering.Apply(__VAR__, desired);
                var afterValue = ReadField(cache, __VAR__);

                return new ExpectedEffect(id, __SNAPSHOTFIELD__, before, afterValue);
            }

            public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
            {
                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.Set__FIELDNAME__);
                var current = ReadField(cache, __VAR__);
                return new ExpectedEffect(id, __SNAPSHOTFIELD__, current, current);
            }

            private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, __TARGETIFACE__ __VAR__) =>
                __SNAPSHOTTER__.Snapshot(cache, __VAR__).AlternativesFields
                    .TryGetValue(__SNAPSHOTFIELD__, out var alternatives)
                    ? alternatives
                    : new Dictionary<string, string>();
        }

        /// <summary>The <see cref="__PREFIX__OperationKinds.Clear__FIELDNAME__"/> counterpart to
        /// <see cref="__PREFIX__SetHandler"/>.</summary>
        internal sealed class __PREFIX__ClearHandler : IOperationHandler
        {
            internal static readonly __PREFIX__ClearHandler Instance = new();
            private __PREFIX__ClearHandler() { }

            public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
            {
                if (operation.Target is not { })
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.Clear__FIELDNAME__}' requires 'target'.");
                }

                if (operation.After is not { } after)
                {
                    throw new InvalidOperationException(
                        $"Operation '{operation.OperationId.Value}' of kind '{__PREFIX__OperationKinds.Clear__FIELDNAME__}' requires 'after'.");
                }

                __PREFIX__ClearPayload.Parse(after);

                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.Clear__FIELDNAME__);
                touchedTargets.Add(id);

                var before = ReadField(cache, __VAR__);
                __PREFIX__ClearLowering.Apply(__VAR__);
                var afterValue = ReadField(cache, __VAR__);

                return new ExpectedEffect(id, __SNAPSHOTFIELD__, before, afterValue);
            }

            public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
            {
                var (id, __VAR__) = TargetResolution.Resolve<__TARGETIFACE__>(cache, operation, __PREFIX__OperationKinds.Clear__FIELDNAME__);
                var current = ReadField(cache, __VAR__);
                return new ExpectedEffect(id, __SNAPSHOTFIELD__, current, current);
            }

            private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, __TARGETIFACE__ __VAR__) =>
                __SNAPSHOTTER__.Snapshot(cache, __VAR__).AlternativesFields
                    .TryGetValue(__SNAPSHOTFIELD__, out var alternatives)
                    ? alternatives
                    : new Dictionary<string, string>();
        }

        """;
}
