using System.Text;

namespace SIL.Motif.Generator.Emit;

/// <summary>
/// Emits one <c>Snapshotting/Generated4/{DeclaringClass}Snapshotter.g.cs</c> file: reads every
/// basic-Integer-enum field of one declaring class (<see cref="Slice4FieldSelector"/>) into the
/// same <see cref="Runner.Snapshotting"/>-shaped <c>ObjectSnapshot</c> that <see cref="SnapshotterEmitter"/>
/// produces for slices 1-3, but through <see cref="Model.Snapshot.IntegerFieldAlternatives"/> rather than
/// the MultiUnicode/MultiString/Boolean paths that emitter's rows never need for this shape.
/// </summary>
/// <remarks>
/// A separate, narrower emitter rather than widening <see cref="SnapshotterEmitter"/> to a fourth branch:
/// slices 1-3's checked-in output is pinned byte-for-byte by their own
/// <c>GeneratedFilesAreUpToDateTests</c>-style drift guards, so a change made for a shape they never emit
/// has no business touching the file that produces their bytes.
/// </remarks>
public static class IntegerEnumSnapshotterEmitter
{
    /// <summary>Emits snapshots for fields on one LibLCM interface.</summary>
    /// <param name="declaringClass">The LibLCM interface name without its <c>I</c> prefix.</param>
    /// <param name="fieldsForClass">The enum fields emitted for that interface.</param>
    /// <param name="snapshotterTypeName">An alternate class name when a sibling field emitter owns the default name.</param>
    public static string Render(
        string declaringClass,
        IReadOnlyList<IntegerEnumFieldSpec> fieldsForClass,
        string? snapshotterTypeName = null)
    {
        var targetInterface = "I" + declaringClass;
        var varName = fieldsForClass[0].Construct;
        var body = new StringBuilder();

        foreach (var field in fieldsForClass)
        {
            var constant = "SnapshotFields." + field.SnapshotFieldConstant;
            body.AppendLine(
                $"        fields[{constant}] = IntegerFieldAlternatives.ToAlternatives({varName}.{field.FieldName});");
        }

        var sourceRowsComment = string.Join(", ", fieldsForClass.Select(f => $"{f.DeclaringClass}.{f.FieldName} ({f.Sig})"));

        return Template
            .Replace("__DECLARINGCLASS__", declaringClass)
            .Replace("__SNAPSHOTTER__", snapshotterTypeName ?? declaringClass + "Snapshotter")
            .Replace("__TARGETIFACE__", targetInterface)
            .Replace("__VAR__", varName)
            .Replace("__SOURCEROWS__", sourceRowsComment)
            .Replace("__BODY__", body.ToString().TrimEnd('\r', '\n'));
    }

    private const string Template = """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command.
        //   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
        //   manifest or MasterLCModel.xml change, and check in the result.
        //
        //   Source rows (Scope=in, Kind=basic, Sig=Integer, Verbs=set, DeclaringClass=__DECLARINGCLASS__):
        //   __SOURCEROWS__.
        // </auto-generated>
        using System.Collections.Generic;
        using SIL.Motif.Contract.Ids;
        using SIL.Motif.Model.Snapshot;
        using SIL.LCModel;

        namespace SIL.Motif.Runner.Snapshotting;

        /// <summary>
        /// Reads a real <c>__TARGETIFACE__</c>'s basic-Integer-enum fields into the
        /// LibLCM-free <see cref="ObjectSnapshot"/> projection.
        /// </summary>
        public static class __SNAPSHOTTER__
        {
            public static ObjectSnapshot Snapshot(LcmCache cache, __TARGETIFACE__ __VAR__)
            {
                var canonicalId = CanonicalId.FromGuid(__VAR__.Guid);
                var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();

        __BODY__

                return new ObjectSnapshot(canonicalId, fields);
            }
        }

        """;
}
