namespace SIL.Motif.Generator.Emit;

public static class RedundantZeroAffixDeleteEmitter
{
    public const string OutputPath = "src/SIL.Motif.Runner/Operations/GeneratedRetirement/RetireRedundantZeroAffixOperationKinds.g.cs";

    public static string Render() => """
        // <auto-generated>
        //   Produced by SIL.Motif.Generator's `emit` command.
        //   This delete kind is intentionally limited to the redundant zero-affix entry graph.
        // </auto-generated>
        namespace SIL.Motif.Runner.Operations;

        public static partial class RetireRedundantZeroAffixOperationKinds
        {
            public const string DeleteGraph = "lexical/lexEntry/deleteRedundantZeroAffixGraph";
        }
        """;
}

public static class RedundantZeroAffixDeleteCatalogWriter
{
    public static IReadOnlyList<GeneratedCatalogWriter.WrittenFile> WriteAll(string repoRoot)
    {
        var path = Path.Combine(repoRoot, RedundantZeroAffixDeleteEmitter.OutputPath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, RedundantZeroAffixDeleteEmitter.Render().Replace("\r\n", "\n"));
        return [new GeneratedCatalogWriter.WrittenFile(RedundantZeroAffixDeleteEmitter.OutputPath)];
    }
}
