namespace SIL.Motif.Generator.Emit;

public static class StringFieldEmitter
{
    public static string Render(BasicFieldSpec spec) => Template
        .Replace("__PREFIX__", spec.SnapshotFieldConstant)
        .Replace("__CLASS__", spec.DeclaringClass)
        .Replace("__FIELD__", spec.FieldName)
        .Replace("__SET__", spec.SetKind)
        .Replace("__CLEAR__", spec.ClearKind)
        .Replace("__VAR__", spec.Construct)
        .Replace("__IFACE__", spec.TargetInterface)
        .Replace("__SNAPSHOT__", spec.DeclaringClass + "Snapshotter")
        .Replace("__SNAPSHOT_FIELD__", "SnapshotFields." + spec.SnapshotFieldConstant);

    public static string RenderSnapshotter(
        string declaringClass, IReadOnlyList<BasicFieldSpec> specs, IReadOnlyList<string>? extraLines = null)
    {
        var lines = string.Join("\n", specs.Select(spec =>
            $"        AddIfPopulated(fields, SnapshotFields.{spec.SnapshotFieldConstant}, " +
            $"StringFieldSnapshotting.ReadAlternatives(cache, {spec.Construct}.{spec.FieldName}));")
            .Concat(extraLines ?? []));
        return SnapshotterTemplate.Replace("__CLASS__", declaringClass)
            .Replace("__IFACE__", "I" + declaringClass)
            .Replace("__VAR__", specs[0].Construct)
            .Replace("__BODY__", lines);
    }

    private const string Template = """
        // <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
        using System;
        using System.Collections.Generic;
        using System.Runtime.CompilerServices;
        using System.Text.Json;
        using SIL.LCModel;
        using SIL.LCModel.Core.KernelInterfaces;
        using SIL.Motif.Contract.Ids;
        using SIL.Motif.Contract.Model;
        using SIL.Motif.Contract.Parsing;
        using SIL.Motif.Model.Effects;
        using SIL.Motif.Model.Snapshot;
        using SIL.Motif.Runner.Snapshotting;

        namespace SIL.Motif.Runner.Operations;

        public static class __PREFIX__OperationKinds
        {
            public const string Set = "__SET__";
            public const string Clear = "__CLEAR__";

            [ModuleInitializer]
            internal static void Register()
            {
                OperationKindRegistry.Register(Set);
                OperationKindRegistry.Register(Clear);
                OperationHandlerRegistry.Register(Set, new __PREFIX__Handler(false));
                OperationHandlerRegistry.Register(Clear, new __PREFIX__Handler(true));
            }
        }

        internal sealed class __PREFIX__Handler(bool clear) : IOperationHandler
        {
            public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation,
                List<CanonicalId> touchedTargets)
            {
                var kind = clear ? __PREFIX__OperationKinds.Clear : __PREFIX__OperationKinds.Set;
                var after = operation.After ?? throw new InvalidOperationException($"'{kind}' requires after.");
                ClosedPayloadParsing.RequireObject(after, kind);
                ClosedPayloadParsing.RejectUnknownProperties(after, clear ? new[] { "ws" } : new[] { "ws", "text" }, kind);
                var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", kind);
                var text = clear ? string.Empty : ClosedPayloadParsing.GetRequiredString(after, "text", kind);
                var (id, __VAR__) = TargetResolution.Resolve<__IFACE__>(cache, operation, kind);
                var before = Read(cache, __VAR__);
                __VAR__.__FIELD__ = StringFieldLowering.Create(cache, ws, text, kind);
                touchedTargets.Add(id);
                return new ExpectedEffect(id, __SNAPSHOT_FIELD__, before, Read(cache, __VAR__));
            }

            public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
            {
                var kind = clear ? __PREFIX__OperationKinds.Clear : __PREFIX__OperationKinds.Set;
                var (id, __VAR__) = TargetResolution.Resolve<__IFACE__>(cache, operation, kind);
                var current = Read(cache, __VAR__);
                return new ExpectedEffect(id, __SNAPSHOT_FIELD__, current, current);
            }

            private static IReadOnlyDictionary<string, string> Read(LcmCache cache, __IFACE__ __VAR__) =>
                StringFieldSnapshotting.ReadAlternatives(cache, __VAR__.__FIELD__);
        }

        """;

    private const string SnapshotterTemplate = """
        // <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
        using System.Collections.Generic;
        using SIL.LCModel;
        using SIL.Motif.Contract.Ids;
        using SIL.Motif.Model.Snapshot;
        using SIL.Motif.Runner.Operations;

        namespace SIL.Motif.Runner.Snapshotting;

        public static class __CLASS__Snapshotter
        {
            public static ObjectSnapshot Snapshot(LcmCache cache, __IFACE__ __VAR__)
            {
                var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();
        __BODY__
                return new ObjectSnapshot(CanonicalId.FromGuid(__VAR__.Guid), fields);
            }

            private static void AddIfPopulated(
                Dictionary<string, IReadOnlyDictionary<string, string>> fields,
                string fieldName, IReadOnlyDictionary<string, string> value)
            {
                if (value.Count > 0) fields[fieldName] = value;
            }
        }

        """;
}
