// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System.Collections.Generic;
using SIL.LCModel;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Operations;

namespace SIL.Motif.Runner.Snapshotting;

public static class StTxtParaSnapshotter
{
    public static ObjectSnapshot Snapshot(LcmCache cache, IStTxtPara stTxtPara)
    {
        var fields = new Dictionary<string, IReadOnlyDictionary<string, string>>();
        AddIfPopulated(fields, SnapshotFields.StTxtParaContents, StringFieldSnapshotting.ReadAlternatives(cache, stTxtPara.Contents));
        return new ObjectSnapshot(CanonicalId.FromGuid(stTxtPara.Guid), fields);
    }

    private static void AddIfPopulated(
        Dictionary<string, IReadOnlyDictionary<string, string>> fields,
        string fieldName, IReadOnlyDictionary<string, string> value)
    {
        if (value.Count > 0) fields[fieldName] = value;
    }
}
