// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
// </auto-generated>
namespace SIL.Motif.Model.Snapshot;

public static partial class SnapshotFields
{
    /// <summary>A <c>RnGenericRec</c>'s <c>MotifHumanJudgment</c> reserved custom String field.</summary>
    public const string RnGenericRecMotifHumanJudgment = "system/rnGenericRec/motifHumanJudgment";

    /// <summary>A <c>RnGenericRec</c>'s <c>Title</c> basic String field.</summary>
    public const string RnGenericRecTitle = "system/rnGenericRec/title";

    /// <summary>A <c>RnGenericRec</c>'s <c>Type</c> rel/atomic CmPossibility field.</summary>
    public const string RnGenericRecType = "system/rnGenericRec/type";

    /// <summary>A <c>StTxtPara</c>'s <c>Contents</c> basic String field.</summary>
    public const string StTxtParaContents = "analysis/stTxtPara/contents";
}
