// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
// </auto-generated>
namespace SIL.Motif.Model.Snapshot;

public static partial class SnapshotFields
{
    /// <summary>A <c>FsClosedValue</c>'s <c>Value</c> rel atomic field.</summary>
    public const string FsClosedValueValue = "grammar/fsClosedValue/value";

    /// <summary>A <c>MoInflAffixSlot</c>'s <c>Name</c> basic MultiUnicode field.</summary>
    public const string MoInflAffixSlotName = "grammar/moInflAffixSlot/name";

    /// <summary>A <c>MoInflAffixTemplate</c>'s <c>Name</c> basic MultiUnicode field.</summary>
    public const string MoInflAffixTemplateName = "grammar/moInflAffixTemplate/name";

    /// <summary>A <c>PartOfSpeech</c>'s <c>AffixSlots</c> owning MoInflAffixSlot field.</summary>
    public const string PartOfSpeechAffixSlots = "grammar/partOfSpeech/affixSlots";

    /// <summary>A <c>PartOfSpeech</c>'s <c>AffixTemplates</c> owning MoInflAffixTemplate field.</summary>
    public const string PartOfSpeechAffixTemplates = "grammar/partOfSpeech/affixTemplates";

    /// <summary>A <c>PhEnvironment</c>'s <c>Name</c> basic MultiUnicode field.</summary>
    public const string PhEnvironmentName = "grammar/phEnvironment/name";

    /// <summary>A <c>PhEnvironment</c>'s <c>StringRepresentation</c> basic String field.</summary>
    public const string PhEnvironmentStringRepresentation = "grammar/phEnvironment/stringRepresentation";

    /// <summary>A <c>PhNCFeatures</c>'s <c>Features</c> owning FsFeatStruc field.</summary>
    public const string PhNCFeaturesFeatures = "grammar/phNCFeatures/features";

    /// <summary>A <c>PhNaturalClass</c>'s <c>Name</c> basic MultiUnicode field.</summary>
    public const string PhNaturalClassName = "grammar/phNaturalClass/name";

    /// <summary>A <c>PhPhonData</c>'s <c>Contexts</c> owning PhContextOrVar field.</summary>
    public const string PhPhonDataContexts = "grammar/phPhonData/contexts";

    /// <summary>A <c>PhPhonData</c>'s <c>Environments</c> owning PhEnvironment field.</summary>
    public const string PhPhonDataEnvironments = "grammar/phPhonData/environments";

    /// <summary>A <c>PhPhonData</c>'s <c>NaturalClasses</c> owning PhNaturalClass field.</summary>
    public const string PhPhonDataNaturalClasses = "grammar/phPhonData/naturalClasses";

    /// <summary>A <c>PhPhonData</c>'s <c>PhonRules</c> owning PhSegmentRule field.</summary>
    public const string PhPhonDataPhonRules = "grammar/phPhonData/phonRules";

    /// <summary>A <c>PhPhonData</c>'s <c>PhonemeSets</c> owning PhPhonemeSet field.</summary>
    public const string PhPhonDataPhonemeSets = "grammar/phPhonData/phonemeSets";

    /// <summary>A <c>PhPhoneme</c>'s <c>Features</c> owning FsFeatStruc field.</summary>
    public const string PhPhonemeFeatures = "grammar/phPhoneme/features";

    /// <summary>A <c>PhPhonemeSet</c>'s <c>BoundaryMarkers</c> owning PhBdryMarker field.</summary>
    public const string PhPhonemeSetBoundaryMarkers = "grammar/phPhonemeSet/boundaryMarkers";

    /// <summary>A <c>PhPhonemeSet</c>'s <c>Phonemes</c> owning PhPhoneme field.</summary>
    public const string PhPhonemeSetPhonemes = "grammar/phPhonemeSet/phonemes";

    /// <summary>A <c>PhRegularRule</c>'s <c>RightHandSides</c> owning PhSegRuleRHS field.</summary>
    public const string PhRegularRuleRightHandSides = "grammar/phRegularRule/rightHandSides";

    /// <summary>A <c>PhSegRuleRHS</c>'s <c>LeftContext</c> owning PhPhonContext field.</summary>
    public const string PhSegRuleRHSLeftContext = "grammar/phSegRuleRHS/leftContext";

    /// <summary>A <c>PhSegRuleRHS</c>'s <c>RightContext</c> owning PhPhonContext field.</summary>
    public const string PhSegRuleRHSRightContext = "grammar/phSegRuleRHS/rightContext";

    /// <summary>A <c>PhSegRuleRHS</c>'s <c>StrucChange</c> owning PhSimpleContext field.</summary>
    public const string PhSegRuleRHSStrucChange = "grammar/phSegRuleRHS/strucChange";

    /// <summary>A <c>PhSegmentRule</c>'s <c>Direction</c> basic Integer field.</summary>
    public const string PhSegmentRuleDirection = "grammar/phSegmentRule/direction";

    /// <summary>A <c>PhSegmentRule</c>'s <c>Name</c> basic MultiUnicode field.</summary>
    public const string PhSegmentRuleName = "grammar/phSegmentRule/name";

    /// <summary>A <c>PhSegmentRule</c>'s <c>StrucDesc</c> owning PhSimpleContext field.</summary>
    public const string PhSegmentRuleStrucDesc = "grammar/phSegmentRule/strucDesc";

    /// <summary>A <c>PhTerminalUnit</c>'s <c>Codes</c> owning PhCode field.</summary>
    public const string PhTerminalUnitCodes = "grammar/phTerminalUnit/codes";

    /// <summary>A <c>PhTerminalUnit</c>'s <c>Name</c> basic MultiUnicode field.</summary>
    public const string PhTerminalUnitName = "grammar/phTerminalUnit/name";

    /// <summary>A <c>RnGenericRec</c>'s <c>Description</c> owning StText field.</summary>
    public const string RnGenericRecDescription = "system/rnGenericRec/description";

    /// <summary>A <c>RnResearchNbk</c>'s <c>Records</c> owning RnGenericRec field.</summary>
    public const string RnResearchNbkRecords = "system/rnResearchNbk/records";

    /// <summary>A <c>StText</c>'s <c>Paragraphs</c> owning StPara field.</summary>
    public const string StTextParagraphs = "system/stText/paragraphs";
}
