// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: RnGenericRec.Type (rel/atomic CmPossibility, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>RnGenericRec.Type</c> operation kinds.</summary>
public static class RnGenericRecTypeOperationKinds
{
    public const string SetType = "system/rnGenericRec/setType";
    public const string ClearType = "system/rnGenericRec/clearType";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetType);
        OperationKindRegistry.Register(ClearType);
        OperationHandlerRegistry.Register(SetType, RnGenericRecTypeSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearType, RnGenericRecTypeClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="RnGenericRecTypeOperationKinds.SetType"/>:
/// <c>{ "ref": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class RnGenericRecTypeSetPayload
{
    private static readonly string[] AllowedProperties = { "ref" };

    public static CanonicalId Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, RnGenericRecTypeOperationKinds.SetType);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, RnGenericRecTypeOperationKinds.SetType);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "ref", RnGenericRecTypeOperationKinds.SetType);
    }
}

/// <summary>The <c>after</c> payload for <see cref="RnGenericRecTypeOperationKinds.ClearType"/>:
/// <c>{}</c>. Closed: any property at all is rejected -- there is exactly one value to clear.</summary>
public static class RnGenericRecTypeClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, RnGenericRecTypeOperationKinds.ClearType);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, RnGenericRecTypeOperationKinds.ClearType);
    }
}

/// <summary>Lowers <see cref="RnGenericRecTypeOperationKinds.SetType"/>: resolves the
/// referenced ICmPossibility and assigns it to <c>rnGenericRec.TypeRA</c>.</summary>
public static class RnGenericRecTypeSetLowering
{
    public static void Apply(LcmCache cache, IRnGenericRec rnGenericRec, CanonicalId refId) =>
        ReferenceFieldLowering.ApplySet<ICmPossibility>(
            cache, value => rnGenericRec.TypeRA = value, refId, RnGenericRecTypeOperationKinds.SetType);
}

/// <summary>Lowers <see cref="RnGenericRecTypeOperationKinds.ClearType"/>: detaches
/// <c>rnGenericRec.TypeRA</c>.</summary>
public static class RnGenericRecTypeClearLowering
{
    public static void Apply(IRnGenericRec rnGenericRec) =>
        ReferenceFieldLowering.ApplyClear<ICmPossibility>(value => rnGenericRec.TypeRA = value);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="RnGenericRecTypeOperationKinds.SetType"/> operation.</summary>
internal sealed class RnGenericRecTypeSetHandler : IOperationHandler
{
    internal static readonly RnGenericRecTypeSetHandler Instance = new();
    private RnGenericRecTypeSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{RnGenericRecTypeOperationKinds.SetType}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{RnGenericRecTypeOperationKinds.SetType}' requires 'after'.");
        }

        var refId = RnGenericRecTypeSetPayload.Parse(after);

        var (id, rnGenericRec) = TargetResolution.Resolve<IRnGenericRec>(cache, operation, RnGenericRecTypeOperationKinds.SetType);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(rnGenericRec.TypeRA);
        RnGenericRecTypeSetLowering.Apply(cache, rnGenericRec, refId);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(rnGenericRec.TypeRA);

        return new ExpectedEffect(id, SnapshotFields.RnGenericRecType, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, rnGenericRec) = TargetResolution.Resolve<IRnGenericRec>(cache, operation, RnGenericRecTypeOperationKinds.SetType);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(rnGenericRec.TypeRA);
        return new ExpectedEffect(id, SnapshotFields.RnGenericRecType, current, current);
    }
}

/// <summary>The <see cref="RnGenericRecTypeOperationKinds.ClearType"/> counterpart to
/// <see cref="RnGenericRecTypeSetHandler"/>.</summary>
internal sealed class RnGenericRecTypeClearHandler : IOperationHandler
{
    internal static readonly RnGenericRecTypeClearHandler Instance = new();
    private RnGenericRecTypeClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{RnGenericRecTypeOperationKinds.ClearType}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{RnGenericRecTypeOperationKinds.ClearType}' requires 'after'.");
        }

        RnGenericRecTypeClearPayload.Parse(after);

        var (id, rnGenericRec) = TargetResolution.Resolve<IRnGenericRec>(cache, operation, RnGenericRecTypeOperationKinds.ClearType);
        touchedTargets.Add(id);

        var before = ReferenceFieldSnapshotting.ReadAlternatives(rnGenericRec.TypeRA);
        RnGenericRecTypeClearLowering.Apply(rnGenericRec);
        var afterValue = ReferenceFieldSnapshotting.ReadAlternatives(rnGenericRec.TypeRA);

        return new ExpectedEffect(id, SnapshotFields.RnGenericRecType, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, rnGenericRec) = TargetResolution.Resolve<IRnGenericRec>(cache, operation, RnGenericRecTypeOperationKinds.ClearType);
        var current = ReferenceFieldSnapshotting.ReadAlternatives(rnGenericRec.TypeRA);
        return new ExpectedEffect(id, SnapshotFields.RnGenericRecType, current, current);
    }
}
