// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.LCModel;
using SIL.LCModel.Core.KernelInterfaces;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;

namespace SIL.Motif.Runner.Operations;

public static class RnGenericRecTitleOperationKinds
{
    public const string Set = "system/rnGenericRec/setTitle";
    public const string Clear = "system/rnGenericRec/clearTitle";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Set);
        OperationKindRegistry.Register(Clear);
        OperationHandlerRegistry.Register(Set, new RnGenericRecTitleHandler(false));
        OperationHandlerRegistry.Register(Clear, new RnGenericRecTitleHandler(true));
    }
}

internal sealed class RnGenericRecTitleHandler(bool clear) : IOperationHandler
{
    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation,
        List<CanonicalId> touchedTargets)
    {
        var kind = clear ? RnGenericRecTitleOperationKinds.Clear : RnGenericRecTitleOperationKinds.Set;
        var after = operation.After ?? throw new InvalidOperationException($"'{kind}' requires after.");
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, clear ? new[] { "ws" } : new[] { "ws", "text" }, kind);
        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", kind);
        var text = clear ? string.Empty : ClosedPayloadParsing.GetRequiredString(after, "text", kind);
        var (id, rnGenericRec) = TargetResolution.Resolve<IRnGenericRec>(cache, operation, kind);
        var before = Read(cache, rnGenericRec);
        rnGenericRec.Title = StringFieldLowering.Create(cache, ws, text, kind);
        touchedTargets.Add(id);
        return new ExpectedEffect(id, SnapshotFields.RnGenericRecTitle, before, Read(cache, rnGenericRec));
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var kind = clear ? RnGenericRecTitleOperationKinds.Clear : RnGenericRecTitleOperationKinds.Set;
        var (id, rnGenericRec) = TargetResolution.Resolve<IRnGenericRec>(cache, operation, kind);
        var current = Read(cache, rnGenericRec);
        return new ExpectedEffect(id, SnapshotFields.RnGenericRecTitle, current, current);
    }

    private static IReadOnlyDictionary<string, string> Read(LcmCache cache, IRnGenericRec rnGenericRec) =>
        StringFieldSnapshotting.ReadAlternatives(cache, rnGenericRec.Title);
}
