// <auto-generated>Produced by SIL.Motif.Generator emit. Do not hand-edit.</auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.LCModel;
using SIL.LCModel.Core.KernelInterfaces;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;

namespace SIL.Motif.Runner.Operations;

public static class StTxtParaContentsOperationKinds
{
    public const string Set = "analysis/stTxtPara/setContents";
    public const string Clear = "analysis/stTxtPara/clearContents";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(Set);
        OperationKindRegistry.Register(Clear);
        OperationHandlerRegistry.Register(Set, new StTxtParaContentsHandler(false));
        OperationHandlerRegistry.Register(Clear, new StTxtParaContentsHandler(true));
    }
}

internal sealed class StTxtParaContentsHandler(bool clear) : IOperationHandler
{
    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation,
        List<CanonicalId> touchedTargets)
    {
        var kind = clear ? StTxtParaContentsOperationKinds.Clear : StTxtParaContentsOperationKinds.Set;
        var after = operation.After ?? throw new InvalidOperationException($"'{kind}' requires after.");
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, clear ? new[] { "ws" } : new[] { "ws", "text" }, kind);
        var ws = ClosedPayloadParsing.GetRequiredString(after, "ws", kind);
        var text = clear ? string.Empty : ClosedPayloadParsing.GetRequiredString(after, "text", kind);
        var (id, stTxtPara) = TargetResolution.Resolve<IStTxtPara>(cache, operation, kind);
        var before = Read(cache, stTxtPara);
        stTxtPara.Contents = StringFieldLowering.Create(cache, ws, text, kind);
        touchedTargets.Add(id);
        return new ExpectedEffect(id, SnapshotFields.StTxtParaContents, before, Read(cache, stTxtPara));
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var kind = clear ? StTxtParaContentsOperationKinds.Clear : StTxtParaContentsOperationKinds.Set;
        var (id, stTxtPara) = TargetResolution.Resolve<IStTxtPara>(cache, operation, kind);
        var current = Read(cache, stTxtPara);
        return new ExpectedEffect(id, SnapshotFields.StTxtParaContents, current, current);
    }

    private static IReadOnlyDictionary<string, string> Read(LcmCache cache, IStTxtPara stTxtPara) =>
        StringFieldSnapshotting.ReadAlternatives(cache, stTxtPara.Contents);
}
