<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIL.Motif.Contract\SIL.Motif.Contract.csproj" />
    <ProjectReference Include="..\SIL.Motif.Model\SIL.Motif.Model.csproj" />
    <ProjectReference Include="..\SIL.Motif.Runner\SIL.Motif.Runner.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SIL.LCModel" Version="$(SilLCModelPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SIL.WritingSystems" Version="$(SilLibPalasoVersion)" />
    <PackageReference Include="SIL.Core" Version="$(SilLibPalasoVersion)" />
    <PackageReference Include="SIL.Core.Desktop" Version="$(SilCoreDesktopVersion)" />
    <PackageReference Include="SIL.Lexicon" Version="$(SilLexiconVersion)" />
  </ItemGroup>

</Project>
