// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   This delete kind is intentionally limited to the redundant zero-affix entry graph.
// </auto-generated>
namespace SIL.Motif.Runner.Operations;

public static partial class RetireRedundantZeroAffixOperationKinds
{
    public const string DeleteGraph = "lexical/lexEntry/deleteRedundantZeroAffixGraph";
}