// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: FsFeatStrucType.Features (rel/seq FsFeatDefn, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>FsFeatStrucType.Features</c> operation kinds.</summary>
public static class FsFeatStrucTypeFeaturesOperationKinds
{
    public const string AddRefFeatures = "grammar/fsFeatStrucType/addRefFeatures";
    public const string RemoveRefFeatures = "grammar/fsFeatStrucType/removeRefFeatures";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefFeatures);
        OperationKindRegistry.Register(RemoveRefFeatures);
        OperationHandlerRegistry.Register(AddRefFeatures, FsFeatStrucTypeFeaturesAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefFeatures, FsFeatStrucTypeFeaturesRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="FsFeatStrucTypeFeaturesOperationKinds.AddRefFeatures"/>
/// and <see cref="FsFeatStrucTypeFeaturesOperationKinds.RemoveRefFeatures"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class FsFeatStrucTypeFeaturesMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="FsFeatStrucTypeFeaturesOperationKinds.AddRefFeatures"/>: resolves the
/// referenced IFsFeatDefn and adds it to <c>fsFeatStrucType.FeaturesRS</c> (a no-op if already
/// present).</summary>
public static class FsFeatStrucTypeFeaturesAddRefLowering
{
    public static void Apply(LcmCache cache, IFsFeatStrucType fsFeatStrucType, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IFsFeatDefn>(
            cache, fsFeatStrucType.FeaturesRS, memberId, FsFeatStrucTypeFeaturesOperationKinds.AddRefFeatures);
}

/// <summary>Lowers <see cref="FsFeatStrucTypeFeaturesOperationKinds.RemoveRefFeatures"/>: resolves the
/// referenced IFsFeatDefn and removes it from <c>fsFeatStrucType.FeaturesRS</c> (a no-op if
/// absent).</summary>
public static class FsFeatStrucTypeFeaturesRemoveRefLowering
{
    public static void Apply(LcmCache cache, IFsFeatStrucType fsFeatStrucType, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IFsFeatDefn>(
            cache, fsFeatStrucType.FeaturesRS, memberId, FsFeatStrucTypeFeaturesOperationKinds.RemoveRefFeatures);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="FsFeatStrucTypeFeaturesOperationKinds.AddRefFeatures"/> operation.</summary>
internal sealed class FsFeatStrucTypeFeaturesAddRefHandler : IOperationHandler
{
    internal static readonly FsFeatStrucTypeFeaturesAddRefHandler Instance = new();
    private FsFeatStrucTypeFeaturesAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatStrucTypeFeaturesOperationKinds.AddRefFeatures}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatStrucTypeFeaturesOperationKinds.AddRefFeatures}' requires 'after'.");
        }

        var memberId = FsFeatStrucTypeFeaturesMemberPayload.Parse(after, FsFeatStrucTypeFeaturesOperationKinds.AddRefFeatures);

        var (id, fsFeatStrucType) = TargetResolution.Resolve<IFsFeatStrucType>(cache, operation, FsFeatStrucTypeFeaturesOperationKinds.AddRefFeatures);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(fsFeatStrucType.FeaturesRS);
        FsFeatStrucTypeFeaturesAddRefLowering.Apply(cache, fsFeatStrucType, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(fsFeatStrucType.FeaturesRS);

        return new ExpectedEffect(id, SnapshotFields.FsFeatStrucTypeFeatures, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsFeatStrucType) = TargetResolution.Resolve<IFsFeatStrucType>(cache, operation, FsFeatStrucTypeFeaturesOperationKinds.AddRefFeatures);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(fsFeatStrucType.FeaturesRS);
        return new ExpectedEffect(id, SnapshotFields.FsFeatStrucTypeFeatures, current, current);
    }
}

/// <summary>The <see cref="FsFeatStrucTypeFeaturesOperationKinds.RemoveRefFeatures"/> counterpart to
/// <see cref="FsFeatStrucTypeFeaturesAddRefHandler"/>.</summary>
internal sealed class FsFeatStrucTypeFeaturesRemoveRefHandler : IOperationHandler
{
    internal static readonly FsFeatStrucTypeFeaturesRemoveRefHandler Instance = new();
    private FsFeatStrucTypeFeaturesRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatStrucTypeFeaturesOperationKinds.RemoveRefFeatures}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{FsFeatStrucTypeFeaturesOperationKinds.RemoveRefFeatures}' requires 'after'.");
        }

        var memberId = FsFeatStrucTypeFeaturesMemberPayload.Parse(after, FsFeatStrucTypeFeaturesOperationKinds.RemoveRefFeatures);

        var (id, fsFeatStrucType) = TargetResolution.Resolve<IFsFeatStrucType>(cache, operation, FsFeatStrucTypeFeaturesOperationKinds.RemoveRefFeatures);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(fsFeatStrucType.FeaturesRS);
        FsFeatStrucTypeFeaturesRemoveRefLowering.Apply(cache, fsFeatStrucType, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(fsFeatStrucType.FeaturesRS);

        return new ExpectedEffect(id, SnapshotFields.FsFeatStrucTypeFeatures, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, fsFeatStrucType) = TargetResolution.Resolve<IFsFeatStrucType>(cache, operation, FsFeatStrucTypeFeaturesOperationKinds.RemoveRefFeatures);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(fsFeatStrucType.FeaturesRS);
        return new ExpectedEffect(id, SnapshotFields.FsFeatStrucTypeFeatures, current, current);
    }
}
