// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: LexEntryRef.ComponentLexemes (rel/seq CmObject, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>LexEntryRef.ComponentLexemes</c> operation kinds.</summary>
public static class LexEntryRefComponentLexemesOperationKinds
{
    public const string AddRefComponentLexemes = "lexical/lexEntryRef/addRefComponentLexemes";
    public const string RemoveRefComponentLexemes = "lexical/lexEntryRef/removeRefComponentLexemes";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefComponentLexemes);
        OperationKindRegistry.Register(RemoveRefComponentLexemes);
        OperationHandlerRegistry.Register(AddRefComponentLexemes, LexEntryRefComponentLexemesAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefComponentLexemes, LexEntryRefComponentLexemesRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="LexEntryRefComponentLexemesOperationKinds.AddRefComponentLexemes"/>
/// and <see cref="LexEntryRefComponentLexemesOperationKinds.RemoveRefComponentLexemes"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class LexEntryRefComponentLexemesMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="LexEntryRefComponentLexemesOperationKinds.AddRefComponentLexemes"/>: resolves the
/// referenced ICmObject and adds it to <c>lexEntryRef.ComponentLexemesRS</c> (a no-op if already
/// present).</summary>
public static class LexEntryRefComponentLexemesAddRefLowering
{
    public static void Apply(LcmCache cache, ILexEntryRef lexEntryRef, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<ICmObject>(
            cache, lexEntryRef.ComponentLexemesRS, memberId, LexEntryRefComponentLexemesOperationKinds.AddRefComponentLexemes);
}

/// <summary>Lowers <see cref="LexEntryRefComponentLexemesOperationKinds.RemoveRefComponentLexemes"/>: resolves the
/// referenced ICmObject and removes it from <c>lexEntryRef.ComponentLexemesRS</c> (a no-op if
/// absent).</summary>
public static class LexEntryRefComponentLexemesRemoveRefLowering
{
    public static void Apply(LcmCache cache, ILexEntryRef lexEntryRef, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<ICmObject>(
            cache, lexEntryRef.ComponentLexemesRS, memberId, LexEntryRefComponentLexemesOperationKinds.RemoveRefComponentLexemes);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="LexEntryRefComponentLexemesOperationKinds.AddRefComponentLexemes"/> operation.</summary>
internal sealed class LexEntryRefComponentLexemesAddRefHandler : IOperationHandler
{
    internal static readonly LexEntryRefComponentLexemesAddRefHandler Instance = new();
    private LexEntryRefComponentLexemesAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryRefComponentLexemesOperationKinds.AddRefComponentLexemes}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryRefComponentLexemesOperationKinds.AddRefComponentLexemes}' requires 'after'.");
        }

        var memberId = LexEntryRefComponentLexemesMemberPayload.Parse(after, LexEntryRefComponentLexemesOperationKinds.AddRefComponentLexemes);

        var (id, lexEntryRef) = TargetResolution.Resolve<ILexEntryRef>(cache, operation, LexEntryRefComponentLexemesOperationKinds.AddRefComponentLexemes);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.ComponentLexemesRS);
        LexEntryRefComponentLexemesAddRefLowering.Apply(cache, lexEntryRef, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.ComponentLexemesRS);

        return new ExpectedEffect(id, SnapshotFields.LexEntryRefComponentLexemes, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntryRef) = TargetResolution.Resolve<ILexEntryRef>(cache, operation, LexEntryRefComponentLexemesOperationKinds.AddRefComponentLexemes);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.ComponentLexemesRS);
        return new ExpectedEffect(id, SnapshotFields.LexEntryRefComponentLexemes, current, current);
    }
}

/// <summary>The <see cref="LexEntryRefComponentLexemesOperationKinds.RemoveRefComponentLexemes"/> counterpart to
/// <see cref="LexEntryRefComponentLexemesAddRefHandler"/>.</summary>
internal sealed class LexEntryRefComponentLexemesRemoveRefHandler : IOperationHandler
{
    internal static readonly LexEntryRefComponentLexemesRemoveRefHandler Instance = new();
    private LexEntryRefComponentLexemesRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryRefComponentLexemesOperationKinds.RemoveRefComponentLexemes}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryRefComponentLexemesOperationKinds.RemoveRefComponentLexemes}' requires 'after'.");
        }

        var memberId = LexEntryRefComponentLexemesMemberPayload.Parse(after, LexEntryRefComponentLexemesOperationKinds.RemoveRefComponentLexemes);

        var (id, lexEntryRef) = TargetResolution.Resolve<ILexEntryRef>(cache, operation, LexEntryRefComponentLexemesOperationKinds.RemoveRefComponentLexemes);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.ComponentLexemesRS);
        LexEntryRefComponentLexemesRemoveRefLowering.Apply(cache, lexEntryRef, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.ComponentLexemesRS);

        return new ExpectedEffect(id, SnapshotFields.LexEntryRefComponentLexemes, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntryRef) = TargetResolution.Resolve<ILexEntryRef>(cache, operation, LexEntryRefComponentLexemesOperationKinds.RemoveRefComponentLexemes);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.ComponentLexemesRS);
        return new ExpectedEffect(id, SnapshotFields.LexEntryRefComponentLexemes, current, current);
    }
}
