// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: LexEntryRef.VariantEntryTypes (rel/seq LexEntryType, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>LexEntryRef.VariantEntryTypes</c> operation kinds.</summary>
public static class LexEntryRefVariantEntryTypesOperationKinds
{
    public const string AddRefVariantEntryTypes = "lexical/lexEntryRef/addRefVariantEntryTypes";
    public const string RemoveRefVariantEntryTypes = "lexical/lexEntryRef/removeRefVariantEntryTypes";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefVariantEntryTypes);
        OperationKindRegistry.Register(RemoveRefVariantEntryTypes);
        OperationHandlerRegistry.Register(AddRefVariantEntryTypes, LexEntryRefVariantEntryTypesAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefVariantEntryTypes, LexEntryRefVariantEntryTypesRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="LexEntryRefVariantEntryTypesOperationKinds.AddRefVariantEntryTypes"/>
/// and <see cref="LexEntryRefVariantEntryTypesOperationKinds.RemoveRefVariantEntryTypes"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class LexEntryRefVariantEntryTypesMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="LexEntryRefVariantEntryTypesOperationKinds.AddRefVariantEntryTypes"/>: resolves the
/// referenced ILexEntryType and adds it to <c>lexEntryRef.VariantEntryTypesRS</c> (a no-op if already
/// present).</summary>
public static class LexEntryRefVariantEntryTypesAddRefLowering
{
    public static void Apply(LcmCache cache, ILexEntryRef lexEntryRef, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<ILexEntryType>(
            cache, lexEntryRef.VariantEntryTypesRS, memberId, LexEntryRefVariantEntryTypesOperationKinds.AddRefVariantEntryTypes);
}

/// <summary>Lowers <see cref="LexEntryRefVariantEntryTypesOperationKinds.RemoveRefVariantEntryTypes"/>: resolves the
/// referenced ILexEntryType and removes it from <c>lexEntryRef.VariantEntryTypesRS</c> (a no-op if
/// absent).</summary>
public static class LexEntryRefVariantEntryTypesRemoveRefLowering
{
    public static void Apply(LcmCache cache, ILexEntryRef lexEntryRef, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<ILexEntryType>(
            cache, lexEntryRef.VariantEntryTypesRS, memberId, LexEntryRefVariantEntryTypesOperationKinds.RemoveRefVariantEntryTypes);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="LexEntryRefVariantEntryTypesOperationKinds.AddRefVariantEntryTypes"/> operation.</summary>
internal sealed class LexEntryRefVariantEntryTypesAddRefHandler : IOperationHandler
{
    internal static readonly LexEntryRefVariantEntryTypesAddRefHandler Instance = new();
    private LexEntryRefVariantEntryTypesAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryRefVariantEntryTypesOperationKinds.AddRefVariantEntryTypes}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryRefVariantEntryTypesOperationKinds.AddRefVariantEntryTypes}' requires 'after'.");
        }

        var memberId = LexEntryRefVariantEntryTypesMemberPayload.Parse(after, LexEntryRefVariantEntryTypesOperationKinds.AddRefVariantEntryTypes);

        var (id, lexEntryRef) = TargetResolution.Resolve<ILexEntryRef>(cache, operation, LexEntryRefVariantEntryTypesOperationKinds.AddRefVariantEntryTypes);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.VariantEntryTypesRS);
        LexEntryRefVariantEntryTypesAddRefLowering.Apply(cache, lexEntryRef, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.VariantEntryTypesRS);

        return new ExpectedEffect(id, SnapshotFields.LexEntryRefVariantEntryTypes, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntryRef) = TargetResolution.Resolve<ILexEntryRef>(cache, operation, LexEntryRefVariantEntryTypesOperationKinds.AddRefVariantEntryTypes);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.VariantEntryTypesRS);
        return new ExpectedEffect(id, SnapshotFields.LexEntryRefVariantEntryTypes, current, current);
    }
}

/// <summary>The <see cref="LexEntryRefVariantEntryTypesOperationKinds.RemoveRefVariantEntryTypes"/> counterpart to
/// <see cref="LexEntryRefVariantEntryTypesAddRefHandler"/>.</summary>
internal sealed class LexEntryRefVariantEntryTypesRemoveRefHandler : IOperationHandler
{
    internal static readonly LexEntryRefVariantEntryTypesRemoveRefHandler Instance = new();
    private LexEntryRefVariantEntryTypesRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryRefVariantEntryTypesOperationKinds.RemoveRefVariantEntryTypes}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{LexEntryRefVariantEntryTypesOperationKinds.RemoveRefVariantEntryTypes}' requires 'after'.");
        }

        var memberId = LexEntryRefVariantEntryTypesMemberPayload.Parse(after, LexEntryRefVariantEntryTypesOperationKinds.RemoveRefVariantEntryTypes);

        var (id, lexEntryRef) = TargetResolution.Resolve<ILexEntryRef>(cache, operation, LexEntryRefVariantEntryTypesOperationKinds.RemoveRefVariantEntryTypes);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.VariantEntryTypesRS);
        LexEntryRefVariantEntryTypesRemoveRefLowering.Apply(cache, lexEntryRef, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.VariantEntryTypesRS);

        return new ExpectedEffect(id, SnapshotFields.LexEntryRefVariantEntryTypes, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, lexEntryRef) = TargetResolution.Resolve<ILexEntryRef>(cache, operation, LexEntryRefVariantEntryTypesOperationKinds.RemoveRefVariantEntryTypes);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(lexEntryRef.VariantEntryTypesRS);
        return new ExpectedEffect(id, SnapshotFields.LexEntryRefVariantEntryTypes, current, current);
    }
}
