// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoAffixAllomorph.Position (rel/seq PhEnvironment, addRef|removeRef emitted;
//   `move` emitted with identity-relative placement).
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the generated ordered sequence <c>MoAffixAllomorph.Position</c> operation kinds.</summary>
public static class MoAffixAllomorphPositionOperationKinds
{
    public const string AddRefPosition = "grammar/moAffixAllomorph/addRefPosition";
    public const string RemoveRefPosition = "grammar/moAffixAllomorph/removeRefPosition";
    public const string MovePosition = "grammar/moAffixAllomorph/movePosition";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefPosition);
        OperationKindRegistry.Register(RemoveRefPosition);
        OperationHandlerRegistry.Register(AddRefPosition, MoAffixAllomorphPositionAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefPosition, MoAffixAllomorphPositionRemoveRefHandler.Instance);
        OperationKindRegistry.Register(MovePosition);
        OperationHandlerRegistry.Register(MovePosition, MoAffixAllomorphPositionMoveHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoAffixAllomorphPositionOperationKinds.AddRefPosition"/>
/// and <see cref="MoAffixAllomorphPositionOperationKinds.RemoveRefPosition"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoAffixAllomorphPositionMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoAffixAllomorphPositionOperationKinds.AddRefPosition"/> by inserting the
/// referenced member at its declared identity-relative placement.</summary>
public static class MoAffixAllomorphPositionAddRefLowering
{
    public static void Apply(LcmCache cache, IMoAffixAllomorph moAffixAllomorph, CanonicalId memberId,
        Placement? placement) =>
        ReferenceSequenceFieldLowering.ApplyAddRef<IPhEnvironment>(
            cache, moAffixAllomorph.PositionRS, memberId, placement,
            MoAffixAllomorphPositionOperationKinds.AddRefPosition);
}

/// <summary>Lowers <see cref="MoAffixAllomorphPositionOperationKinds.RemoveRefPosition"/>: resolves the
/// referenced IPhEnvironment and removes it from <c>moAffixAllomorph.PositionRS</c> (a no-op if
/// absent).</summary>
public static class MoAffixAllomorphPositionRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoAffixAllomorph moAffixAllomorph, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPhEnvironment>(
            cache, moAffixAllomorph.PositionRS, memberId, MoAffixAllomorphPositionOperationKinds.RemoveRefPosition);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoAffixAllomorphPositionOperationKinds.AddRefPosition"/> operation.</summary>
internal sealed class MoAffixAllomorphPositionAddRefHandler : IOperationHandler
{
    internal static readonly MoAffixAllomorphPositionAddRefHandler Instance = new();
    private MoAffixAllomorphPositionAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPositionOperationKinds.AddRefPosition}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPositionOperationKinds.AddRefPosition}' requires 'after'.");
        }

        var memberId = MoAffixAllomorphPositionMemberPayload.Parse(after, MoAffixAllomorphPositionOperationKinds.AddRefPosition);

        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPositionOperationKinds.AddRefPosition);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PositionRS);
        MoAffixAllomorphPositionAddRefLowering.Apply(cache, moAffixAllomorph, memberId, operation.Placement);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PositionRS);

        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPosition, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPositionOperationKinds.AddRefPosition);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PositionRS);
        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPosition, current, current);
    }
}

/// <summary>The <see cref="MoAffixAllomorphPositionOperationKinds.RemoveRefPosition"/> counterpart to
/// <see cref="MoAffixAllomorphPositionAddRefHandler"/>.</summary>
internal sealed class MoAffixAllomorphPositionRemoveRefHandler : IOperationHandler
{
    internal static readonly MoAffixAllomorphPositionRemoveRefHandler Instance = new();
    private MoAffixAllomorphPositionRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPositionOperationKinds.RemoveRefPosition}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPositionOperationKinds.RemoveRefPosition}' requires 'after'.");
        }

        var memberId = MoAffixAllomorphPositionMemberPayload.Parse(after, MoAffixAllomorphPositionOperationKinds.RemoveRefPosition);
        if (operation.Placement is not null)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPositionOperationKinds.RemoveRefPosition}' cannot carry placement; use its move kind.");

        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPositionOperationKinds.RemoveRefPosition);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PositionRS);
        MoAffixAllomorphPositionRemoveRefLowering.Apply(cache, moAffixAllomorph, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PositionRS);

        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPosition, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPositionOperationKinds.RemoveRefPosition);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PositionRS);
        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPosition, current, current);
    }
}

/// <summary>Lowers the ordered sequence move by resolving the member id within the target sequence.</summary>
public static class MoAffixAllomorphPositionMoveLowering
{
    public static void Apply(IMoAffixAllomorph moAffixAllomorph, CanonicalId memberId, Placement placement) =>
        ReferenceSequenceFieldLowering.ApplyMove(
            moAffixAllomorph.PositionRS, memberId, placement, MoAffixAllomorphPositionOperationKinds.MovePosition);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoAffixAllomorphPositionOperationKinds.MovePosition"/> operation.</summary>
internal sealed class MoAffixAllomorphPositionMoveHandler : IOperationHandler
{
    internal static readonly MoAffixAllomorphPositionMoveHandler Instance = new();
    private MoAffixAllomorphPositionMoveHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPositionOperationKinds.MovePosition}' requires 'target'.");
        if (operation.After is not { } after)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPositionOperationKinds.MovePosition}' requires 'after'.");
        if (operation.Placement is not { } placement)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{MoAffixAllomorphPositionOperationKinds.MovePosition}' requires 'placement'.");

        var memberId = MoAffixAllomorphPositionMemberPayload.Parse(after, MoAffixAllomorphPositionOperationKinds.MovePosition);
        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPositionOperationKinds.MovePosition);
        touchedTargets.Add(id);
        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PositionRS);
        MoAffixAllomorphPositionMoveLowering.Apply(moAffixAllomorph, memberId, placement);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PositionRS);
        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPosition, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAffixAllomorph) = TargetResolution.Resolve<IMoAffixAllomorph>(cache, operation, MoAffixAllomorphPositionOperationKinds.MovePosition);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAffixAllomorph.PositionRS);
        return new ExpectedEffect(id, SnapshotFields.MoAffixAllomorphPosition, current, current);
    }
}
