// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoAlloAdhocProhib.RestOfAllos (rel/seq MoForm, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoAlloAdhocProhib.RestOfAllos</c> operation kinds.</summary>
public static class MoAlloAdhocProhibRestOfAllosOperationKinds
{
    public const string AddRefRestOfAllos = "grammar/moAlloAdhocProhib/addRefRestOfAllos";
    public const string RemoveRefRestOfAllos = "grammar/moAlloAdhocProhib/removeRefRestOfAllos";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefRestOfAllos);
        OperationKindRegistry.Register(RemoveRefRestOfAllos);
        OperationHandlerRegistry.Register(AddRefRestOfAllos, MoAlloAdhocProhibRestOfAllosAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefRestOfAllos, MoAlloAdhocProhibRestOfAllosRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoAlloAdhocProhibRestOfAllosOperationKinds.AddRefRestOfAllos"/>
/// and <see cref="MoAlloAdhocProhibRestOfAllosOperationKinds.RemoveRefRestOfAllos"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoAlloAdhocProhibRestOfAllosMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoAlloAdhocProhibRestOfAllosOperationKinds.AddRefRestOfAllos"/>: resolves the
/// referenced IMoForm and adds it to <c>moAlloAdhocProhib.RestOfAllosRS</c> (a no-op if already
/// present).</summary>
public static class MoAlloAdhocProhibRestOfAllosAddRefLowering
{
    public static void Apply(LcmCache cache, IMoAlloAdhocProhib moAlloAdhocProhib, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IMoForm>(
            cache, moAlloAdhocProhib.RestOfAllosRS, memberId, MoAlloAdhocProhibRestOfAllosOperationKinds.AddRefRestOfAllos);
}

/// <summary>Lowers <see cref="MoAlloAdhocProhibRestOfAllosOperationKinds.RemoveRefRestOfAllos"/>: resolves the
/// referenced IMoForm and removes it from <c>moAlloAdhocProhib.RestOfAllosRS</c> (a no-op if
/// absent).</summary>
public static class MoAlloAdhocProhibRestOfAllosRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoAlloAdhocProhib moAlloAdhocProhib, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IMoForm>(
            cache, moAlloAdhocProhib.RestOfAllosRS, memberId, MoAlloAdhocProhibRestOfAllosOperationKinds.RemoveRefRestOfAllos);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoAlloAdhocProhibRestOfAllosOperationKinds.AddRefRestOfAllos"/> operation.</summary>
internal sealed class MoAlloAdhocProhibRestOfAllosAddRefHandler : IOperationHandler
{
    internal static readonly MoAlloAdhocProhibRestOfAllosAddRefHandler Instance = new();
    private MoAlloAdhocProhibRestOfAllosAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibRestOfAllosOperationKinds.AddRefRestOfAllos}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibRestOfAllosOperationKinds.AddRefRestOfAllos}' requires 'after'.");
        }

        var memberId = MoAlloAdhocProhibRestOfAllosMemberPayload.Parse(after, MoAlloAdhocProhibRestOfAllosOperationKinds.AddRefRestOfAllos);

        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibRestOfAllosOperationKinds.AddRefRestOfAllos);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.RestOfAllosRS);
        MoAlloAdhocProhibRestOfAllosAddRefLowering.Apply(cache, moAlloAdhocProhib, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.RestOfAllosRS);

        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibRestOfAllos, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibRestOfAllosOperationKinds.AddRefRestOfAllos);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.RestOfAllosRS);
        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibRestOfAllos, current, current);
    }
}

/// <summary>The <see cref="MoAlloAdhocProhibRestOfAllosOperationKinds.RemoveRefRestOfAllos"/> counterpart to
/// <see cref="MoAlloAdhocProhibRestOfAllosAddRefHandler"/>.</summary>
internal sealed class MoAlloAdhocProhibRestOfAllosRemoveRefHandler : IOperationHandler
{
    internal static readonly MoAlloAdhocProhibRestOfAllosRemoveRefHandler Instance = new();
    private MoAlloAdhocProhibRestOfAllosRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibRestOfAllosOperationKinds.RemoveRefRestOfAllos}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibRestOfAllosOperationKinds.RemoveRefRestOfAllos}' requires 'after'.");
        }

        var memberId = MoAlloAdhocProhibRestOfAllosMemberPayload.Parse(after, MoAlloAdhocProhibRestOfAllosOperationKinds.RemoveRefRestOfAllos);

        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibRestOfAllosOperationKinds.RemoveRefRestOfAllos);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.RestOfAllosRS);
        MoAlloAdhocProhibRestOfAllosRemoveRefLowering.Apply(cache, moAlloAdhocProhib, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.RestOfAllosRS);

        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibRestOfAllos, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibRestOfAllosOperationKinds.RemoveRefRestOfAllos);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.RestOfAllosRS);
        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibRestOfAllos, current, current);
    }
}
