// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoAlloAdhocProhib.Allomorphs (rel/seq MoForm, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoAlloAdhocProhib.Allomorphs</c> operation kinds.</summary>
public static class MoAlloAdhocProhibAllomorphsOperationKinds
{
    public const string AddRefAllomorphs = "grammar/moAlloAdhocProhib/addRefAllomorphs";
    public const string RemoveRefAllomorphs = "grammar/moAlloAdhocProhib/removeRefAllomorphs";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefAllomorphs);
        OperationKindRegistry.Register(RemoveRefAllomorphs);
        OperationHandlerRegistry.Register(AddRefAllomorphs, MoAlloAdhocProhibAllomorphsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefAllomorphs, MoAlloAdhocProhibAllomorphsRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoAlloAdhocProhibAllomorphsOperationKinds.AddRefAllomorphs"/>
/// and <see cref="MoAlloAdhocProhibAllomorphsOperationKinds.RemoveRefAllomorphs"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoAlloAdhocProhibAllomorphsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoAlloAdhocProhibAllomorphsOperationKinds.AddRefAllomorphs"/>: resolves the
/// referenced IMoForm and adds it to <c>moAlloAdhocProhib.AllomorphsRS</c> (a no-op if already
/// present).</summary>
public static class MoAlloAdhocProhibAllomorphsAddRefLowering
{
    public static void Apply(LcmCache cache, IMoAlloAdhocProhib moAlloAdhocProhib, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IMoForm>(
            cache, moAlloAdhocProhib.AllomorphsRS, memberId, MoAlloAdhocProhibAllomorphsOperationKinds.AddRefAllomorphs);
}

/// <summary>Lowers <see cref="MoAlloAdhocProhibAllomorphsOperationKinds.RemoveRefAllomorphs"/>: resolves the
/// referenced IMoForm and removes it from <c>moAlloAdhocProhib.AllomorphsRS</c> (a no-op if
/// absent).</summary>
public static class MoAlloAdhocProhibAllomorphsRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoAlloAdhocProhib moAlloAdhocProhib, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IMoForm>(
            cache, moAlloAdhocProhib.AllomorphsRS, memberId, MoAlloAdhocProhibAllomorphsOperationKinds.RemoveRefAllomorphs);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoAlloAdhocProhibAllomorphsOperationKinds.AddRefAllomorphs"/> operation.</summary>
internal sealed class MoAlloAdhocProhibAllomorphsAddRefHandler : IOperationHandler
{
    internal static readonly MoAlloAdhocProhibAllomorphsAddRefHandler Instance = new();
    private MoAlloAdhocProhibAllomorphsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibAllomorphsOperationKinds.AddRefAllomorphs}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibAllomorphsOperationKinds.AddRefAllomorphs}' requires 'after'.");
        }

        var memberId = MoAlloAdhocProhibAllomorphsMemberPayload.Parse(after, MoAlloAdhocProhibAllomorphsOperationKinds.AddRefAllomorphs);

        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibAllomorphsOperationKinds.AddRefAllomorphs);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.AllomorphsRS);
        MoAlloAdhocProhibAllomorphsAddRefLowering.Apply(cache, moAlloAdhocProhib, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.AllomorphsRS);

        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibAllomorphs, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibAllomorphsOperationKinds.AddRefAllomorphs);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.AllomorphsRS);
        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibAllomorphs, current, current);
    }
}

/// <summary>The <see cref="MoAlloAdhocProhibAllomorphsOperationKinds.RemoveRefAllomorphs"/> counterpart to
/// <see cref="MoAlloAdhocProhibAllomorphsAddRefHandler"/>.</summary>
internal sealed class MoAlloAdhocProhibAllomorphsRemoveRefHandler : IOperationHandler
{
    internal static readonly MoAlloAdhocProhibAllomorphsRemoveRefHandler Instance = new();
    private MoAlloAdhocProhibAllomorphsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibAllomorphsOperationKinds.RemoveRefAllomorphs}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoAlloAdhocProhibAllomorphsOperationKinds.RemoveRefAllomorphs}' requires 'after'.");
        }

        var memberId = MoAlloAdhocProhibAllomorphsMemberPayload.Parse(after, MoAlloAdhocProhibAllomorphsOperationKinds.RemoveRefAllomorphs);

        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibAllomorphsOperationKinds.RemoveRefAllomorphs);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.AllomorphsRS);
        MoAlloAdhocProhibAllomorphsRemoveRefLowering.Apply(cache, moAlloAdhocProhib, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.AllomorphsRS);

        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibAllomorphs, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moAlloAdhocProhib) = TargetResolution.Resolve<IMoAlloAdhocProhib>(cache, operation, MoAlloAdhocProhibAllomorphsOperationKinds.RemoveRefAllomorphs);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moAlloAdhocProhib.AllomorphsRS);
        return new ExpectedEffect(id, SnapshotFields.MoAlloAdhocProhibAllomorphs, current, current);
    }
}
