// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInflAffixTemplate.PrefixSlots (rel/seq MoInflAffixSlot, addRef|removeRef emitted;
//   `move` emitted with identity-relative placement).
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the generated ordered sequence <c>MoInflAffixTemplate.PrefixSlots</c> operation kinds.</summary>
public static class MoInflAffixTemplatePrefixSlotsOperationKinds
{
    public const string AddRefPrefixSlots = "grammar/moInflAffixTemplate/addRefPrefixSlots";
    public const string RemoveRefPrefixSlots = "grammar/moInflAffixTemplate/removeRefPrefixSlots";
    public const string MovePrefixSlots = "grammar/moInflAffixTemplate/movePrefixSlots";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefPrefixSlots);
        OperationKindRegistry.Register(RemoveRefPrefixSlots);
        OperationHandlerRegistry.Register(AddRefPrefixSlots, MoInflAffixTemplatePrefixSlotsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefPrefixSlots, MoInflAffixTemplatePrefixSlotsRemoveRefHandler.Instance);
        OperationKindRegistry.Register(MovePrefixSlots);
        OperationHandlerRegistry.Register(MovePrefixSlots, MoInflAffixTemplatePrefixSlotsMoveHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoInflAffixTemplatePrefixSlotsOperationKinds.AddRefPrefixSlots"/>
/// and <see cref="MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoInflAffixTemplatePrefixSlotsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoInflAffixTemplatePrefixSlotsOperationKinds.AddRefPrefixSlots"/> by inserting the
/// referenced member at its declared identity-relative placement.</summary>
public static class MoInflAffixTemplatePrefixSlotsAddRefLowering
{
    public static void Apply(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate, CanonicalId memberId,
        Placement? placement) =>
        ReferenceSequenceFieldLowering.ApplyAddRef<IMoInflAffixSlot>(
            cache, moInflAffixTemplate.PrefixSlotsRS, memberId, placement,
            MoInflAffixTemplatePrefixSlotsOperationKinds.AddRefPrefixSlots);
}

/// <summary>Lowers <see cref="MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots"/>: resolves the
/// referenced IMoInflAffixSlot and removes it from <c>moInflAffixTemplate.PrefixSlotsRS</c> (a no-op if
/// absent).</summary>
public static class MoInflAffixTemplatePrefixSlotsRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoInflAffixTemplate moInflAffixTemplate, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IMoInflAffixSlot>(
            cache, moInflAffixTemplate.PrefixSlotsRS, memberId, MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffixTemplatePrefixSlotsOperationKinds.AddRefPrefixSlots"/> operation.</summary>
internal sealed class MoInflAffixTemplatePrefixSlotsAddRefHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplatePrefixSlotsAddRefHandler Instance = new();
    private MoInflAffixTemplatePrefixSlotsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplatePrefixSlotsOperationKinds.AddRefPrefixSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplatePrefixSlotsOperationKinds.AddRefPrefixSlots}' requires 'after'.");
        }

        var memberId = MoInflAffixTemplatePrefixSlotsMemberPayload.Parse(after, MoInflAffixTemplatePrefixSlotsOperationKinds.AddRefPrefixSlots);

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplatePrefixSlotsOperationKinds.AddRefPrefixSlots);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.PrefixSlotsRS);
        MoInflAffixTemplatePrefixSlotsAddRefLowering.Apply(cache, moInflAffixTemplate, memberId, operation.Placement);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.PrefixSlotsRS);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplatePrefixSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplatePrefixSlotsOperationKinds.AddRefPrefixSlots);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.PrefixSlotsRS);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplatePrefixSlots, current, current);
    }
}

/// <summary>The <see cref="MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots"/> counterpart to
/// <see cref="MoInflAffixTemplatePrefixSlotsAddRefHandler"/>.</summary>
internal sealed class MoInflAffixTemplatePrefixSlotsRemoveRefHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplatePrefixSlotsRemoveRefHandler Instance = new();
    private MoInflAffixTemplatePrefixSlotsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots}' requires 'after'.");
        }

        var memberId = MoInflAffixTemplatePrefixSlotsMemberPayload.Parse(after, MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots);
        if (operation.Placement is not null)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots}' cannot carry placement; use its move kind.");

        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.PrefixSlotsRS);
        MoInflAffixTemplatePrefixSlotsRemoveRefLowering.Apply(cache, moInflAffixTemplate, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.PrefixSlotsRS);

        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplatePrefixSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplatePrefixSlotsOperationKinds.RemoveRefPrefixSlots);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.PrefixSlotsRS);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplatePrefixSlots, current, current);
    }
}

/// <summary>Lowers the ordered sequence move by resolving the member id within the target sequence.</summary>
public static class MoInflAffixTemplatePrefixSlotsMoveLowering
{
    public static void Apply(IMoInflAffixTemplate moInflAffixTemplate, CanonicalId memberId, Placement placement) =>
        ReferenceSequenceFieldLowering.ApplyMove(
            moInflAffixTemplate.PrefixSlotsRS, memberId, placement, MoInflAffixTemplatePrefixSlotsOperationKinds.MovePrefixSlots);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInflAffixTemplatePrefixSlotsOperationKinds.MovePrefixSlots"/> operation.</summary>
internal sealed class MoInflAffixTemplatePrefixSlotsMoveHandler : IOperationHandler
{
    internal static readonly MoInflAffixTemplatePrefixSlotsMoveHandler Instance = new();
    private MoInflAffixTemplatePrefixSlotsMoveHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplatePrefixSlotsOperationKinds.MovePrefixSlots}' requires 'target'.");
        if (operation.After is not { } after)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplatePrefixSlotsOperationKinds.MovePrefixSlots}' requires 'after'.");
        if (operation.Placement is not { } placement)
            throw new InvalidOperationException($"Operation '{operation.OperationId.Value}' of kind '{MoInflAffixTemplatePrefixSlotsOperationKinds.MovePrefixSlots}' requires 'placement'.");

        var memberId = MoInflAffixTemplatePrefixSlotsMemberPayload.Parse(after, MoInflAffixTemplatePrefixSlotsOperationKinds.MovePrefixSlots);
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplatePrefixSlotsOperationKinds.MovePrefixSlots);
        touchedTargets.Add(id);
        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.PrefixSlotsRS);
        MoInflAffixTemplatePrefixSlotsMoveLowering.Apply(moInflAffixTemplate, memberId, placement);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.PrefixSlotsRS);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplatePrefixSlots, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInflAffixTemplate) = TargetResolution.Resolve<IMoInflAffixTemplate>(cache, operation, MoInflAffixTemplatePrefixSlotsOperationKinds.MovePrefixSlots);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInflAffixTemplate.PrefixSlotsRS);
        return new ExpectedEffect(id, SnapshotFields.MoInflAffixTemplatePrefixSlots, current, current);
    }
}
