// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoInsertPhones.Content (rel/seq PhTerminalUnit, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoInsertPhones.Content</c> operation kinds.</summary>
public static class MoInsertPhonesContentOperationKinds
{
    public const string AddRefContent = "grammar/moInsertPhones/addRefContent";
    public const string RemoveRefContent = "grammar/moInsertPhones/removeRefContent";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefContent);
        OperationKindRegistry.Register(RemoveRefContent);
        OperationHandlerRegistry.Register(AddRefContent, MoInsertPhonesContentAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefContent, MoInsertPhonesContentRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoInsertPhonesContentOperationKinds.AddRefContent"/>
/// and <see cref="MoInsertPhonesContentOperationKinds.RemoveRefContent"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoInsertPhonesContentMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoInsertPhonesContentOperationKinds.AddRefContent"/>: resolves the
/// referenced IPhTerminalUnit and adds it to <c>moInsertPhones.ContentRS</c> (a no-op if already
/// present).</summary>
public static class MoInsertPhonesContentAddRefLowering
{
    public static void Apply(LcmCache cache, IMoInsertPhones moInsertPhones, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IPhTerminalUnit>(
            cache, moInsertPhones.ContentRS, memberId, MoInsertPhonesContentOperationKinds.AddRefContent);
}

/// <summary>Lowers <see cref="MoInsertPhonesContentOperationKinds.RemoveRefContent"/>: resolves the
/// referenced IPhTerminalUnit and removes it from <c>moInsertPhones.ContentRS</c> (a no-op if
/// absent).</summary>
public static class MoInsertPhonesContentRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoInsertPhones moInsertPhones, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPhTerminalUnit>(
            cache, moInsertPhones.ContentRS, memberId, MoInsertPhonesContentOperationKinds.RemoveRefContent);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoInsertPhonesContentOperationKinds.AddRefContent"/> operation.</summary>
internal sealed class MoInsertPhonesContentAddRefHandler : IOperationHandler
{
    internal static readonly MoInsertPhonesContentAddRefHandler Instance = new();
    private MoInsertPhonesContentAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInsertPhonesContentOperationKinds.AddRefContent}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInsertPhonesContentOperationKinds.AddRefContent}' requires 'after'.");
        }

        var memberId = MoInsertPhonesContentMemberPayload.Parse(after, MoInsertPhonesContentOperationKinds.AddRefContent);

        var (id, moInsertPhones) = TargetResolution.Resolve<IMoInsertPhones>(cache, operation, MoInsertPhonesContentOperationKinds.AddRefContent);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInsertPhones.ContentRS);
        MoInsertPhonesContentAddRefLowering.Apply(cache, moInsertPhones, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInsertPhones.ContentRS);

        return new ExpectedEffect(id, SnapshotFields.MoInsertPhonesContent, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInsertPhones) = TargetResolution.Resolve<IMoInsertPhones>(cache, operation, MoInsertPhonesContentOperationKinds.AddRefContent);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInsertPhones.ContentRS);
        return new ExpectedEffect(id, SnapshotFields.MoInsertPhonesContent, current, current);
    }
}

/// <summary>The <see cref="MoInsertPhonesContentOperationKinds.RemoveRefContent"/> counterpart to
/// <see cref="MoInsertPhonesContentAddRefHandler"/>.</summary>
internal sealed class MoInsertPhonesContentRemoveRefHandler : IOperationHandler
{
    internal static readonly MoInsertPhonesContentRemoveRefHandler Instance = new();
    private MoInsertPhonesContentRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInsertPhonesContentOperationKinds.RemoveRefContent}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoInsertPhonesContentOperationKinds.RemoveRefContent}' requires 'after'.");
        }

        var memberId = MoInsertPhonesContentMemberPayload.Parse(after, MoInsertPhonesContentOperationKinds.RemoveRefContent);

        var (id, moInsertPhones) = TargetResolution.Resolve<IMoInsertPhones>(cache, operation, MoInsertPhonesContentOperationKinds.RemoveRefContent);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInsertPhones.ContentRS);
        MoInsertPhonesContentRemoveRefLowering.Apply(cache, moInsertPhones, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInsertPhones.ContentRS);

        return new ExpectedEffect(id, SnapshotFields.MoInsertPhonesContent, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moInsertPhones) = TargetResolution.Resolve<IMoInsertPhones>(cache, operation, MoInsertPhonesContentOperationKinds.RemoveRefContent);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moInsertPhones.ContentRS);
        return new ExpectedEffect(id, SnapshotFields.MoInsertPhonesContent, current, current);
    }
}
