// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: MoMorphAdhocProhib.RestOfMorphs (rel/seq MoMorphSynAnalysis, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>MoMorphAdhocProhib.RestOfMorphs</c> operation kinds.</summary>
public static class MoMorphAdhocProhibRestOfMorphsOperationKinds
{
    public const string AddRefRestOfMorphs = "grammar/moMorphAdhocProhib/addRefRestOfMorphs";
    public const string RemoveRefRestOfMorphs = "grammar/moMorphAdhocProhib/removeRefRestOfMorphs";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefRestOfMorphs);
        OperationKindRegistry.Register(RemoveRefRestOfMorphs);
        OperationHandlerRegistry.Register(AddRefRestOfMorphs, MoMorphAdhocProhibRestOfMorphsAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefRestOfMorphs, MoMorphAdhocProhibRestOfMorphsRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="MoMorphAdhocProhibRestOfMorphsOperationKinds.AddRefRestOfMorphs"/>
/// and <see cref="MoMorphAdhocProhibRestOfMorphsOperationKinds.RemoveRefRestOfMorphs"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class MoMorphAdhocProhibRestOfMorphsMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="MoMorphAdhocProhibRestOfMorphsOperationKinds.AddRefRestOfMorphs"/>: resolves the
/// referenced IMoMorphSynAnalysis and adds it to <c>moMorphAdhocProhib.RestOfMorphsRS</c> (a no-op if already
/// present).</summary>
public static class MoMorphAdhocProhibRestOfMorphsAddRefLowering
{
    public static void Apply(LcmCache cache, IMoMorphAdhocProhib moMorphAdhocProhib, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IMoMorphSynAnalysis>(
            cache, moMorphAdhocProhib.RestOfMorphsRS, memberId, MoMorphAdhocProhibRestOfMorphsOperationKinds.AddRefRestOfMorphs);
}

/// <summary>Lowers <see cref="MoMorphAdhocProhibRestOfMorphsOperationKinds.RemoveRefRestOfMorphs"/>: resolves the
/// referenced IMoMorphSynAnalysis and removes it from <c>moMorphAdhocProhib.RestOfMorphsRS</c> (a no-op if
/// absent).</summary>
public static class MoMorphAdhocProhibRestOfMorphsRemoveRefLowering
{
    public static void Apply(LcmCache cache, IMoMorphAdhocProhib moMorphAdhocProhib, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IMoMorphSynAnalysis>(
            cache, moMorphAdhocProhib.RestOfMorphsRS, memberId, MoMorphAdhocProhibRestOfMorphsOperationKinds.RemoveRefRestOfMorphs);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="MoMorphAdhocProhibRestOfMorphsOperationKinds.AddRefRestOfMorphs"/> operation.</summary>
internal sealed class MoMorphAdhocProhibRestOfMorphsAddRefHandler : IOperationHandler
{
    internal static readonly MoMorphAdhocProhibRestOfMorphsAddRefHandler Instance = new();
    private MoMorphAdhocProhibRestOfMorphsAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoMorphAdhocProhibRestOfMorphsOperationKinds.AddRefRestOfMorphs}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoMorphAdhocProhibRestOfMorphsOperationKinds.AddRefRestOfMorphs}' requires 'after'.");
        }

        var memberId = MoMorphAdhocProhibRestOfMorphsMemberPayload.Parse(after, MoMorphAdhocProhibRestOfMorphsOperationKinds.AddRefRestOfMorphs);

        var (id, moMorphAdhocProhib) = TargetResolution.Resolve<IMoMorphAdhocProhib>(cache, operation, MoMorphAdhocProhibRestOfMorphsOperationKinds.AddRefRestOfMorphs);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moMorphAdhocProhib.RestOfMorphsRS);
        MoMorphAdhocProhibRestOfMorphsAddRefLowering.Apply(cache, moMorphAdhocProhib, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moMorphAdhocProhib.RestOfMorphsRS);

        return new ExpectedEffect(id, SnapshotFields.MoMorphAdhocProhibRestOfMorphs, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moMorphAdhocProhib) = TargetResolution.Resolve<IMoMorphAdhocProhib>(cache, operation, MoMorphAdhocProhibRestOfMorphsOperationKinds.AddRefRestOfMorphs);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moMorphAdhocProhib.RestOfMorphsRS);
        return new ExpectedEffect(id, SnapshotFields.MoMorphAdhocProhibRestOfMorphs, current, current);
    }
}

/// <summary>The <see cref="MoMorphAdhocProhibRestOfMorphsOperationKinds.RemoveRefRestOfMorphs"/> counterpart to
/// <see cref="MoMorphAdhocProhibRestOfMorphsAddRefHandler"/>.</summary>
internal sealed class MoMorphAdhocProhibRestOfMorphsRemoveRefHandler : IOperationHandler
{
    internal static readonly MoMorphAdhocProhibRestOfMorphsRemoveRefHandler Instance = new();
    private MoMorphAdhocProhibRestOfMorphsRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoMorphAdhocProhibRestOfMorphsOperationKinds.RemoveRefRestOfMorphs}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{MoMorphAdhocProhibRestOfMorphsOperationKinds.RemoveRefRestOfMorphs}' requires 'after'.");
        }

        var memberId = MoMorphAdhocProhibRestOfMorphsMemberPayload.Parse(after, MoMorphAdhocProhibRestOfMorphsOperationKinds.RemoveRefRestOfMorphs);

        var (id, moMorphAdhocProhib) = TargetResolution.Resolve<IMoMorphAdhocProhib>(cache, operation, MoMorphAdhocProhibRestOfMorphsOperationKinds.RemoveRefRestOfMorphs);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moMorphAdhocProhib.RestOfMorphsRS);
        MoMorphAdhocProhibRestOfMorphsRemoveRefLowering.Apply(cache, moMorphAdhocProhib, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moMorphAdhocProhib.RestOfMorphsRS);

        return new ExpectedEffect(id, SnapshotFields.MoMorphAdhocProhibRestOfMorphs, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, moMorphAdhocProhib) = TargetResolution.Resolve<IMoMorphAdhocProhib>(cache, operation, MoMorphAdhocProhibRestOfMorphsOperationKinds.RemoveRefRestOfMorphs);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(moMorphAdhocProhib.RestOfMorphsRS);
        return new ExpectedEffect(id, SnapshotFields.MoMorphAdhocProhibRestOfMorphs, current, current);
    }
}
