// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhSegmentRule.Disabled (basic Boolean, Verbs=set|clear).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhSegmentRule.Disabled</c> operation kinds.</summary>
public static class PhSegmentRuleDisabledOperationKinds
{
    public const string SetDisabled = "grammar/phSegmentRule/setDisabled";
    public const string ClearDisabled = "grammar/phSegmentRule/clearDisabled";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(SetDisabled);
        OperationKindRegistry.Register(ClearDisabled);
        OperationHandlerRegistry.Register(SetDisabled, PhSegmentRuleDisabledSetHandler.Instance);
        OperationHandlerRegistry.Register(ClearDisabled, PhSegmentRuleDisabledClearHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhSegmentRuleDisabledOperationKinds.SetDisabled"/>:
/// <c>{ "value": true|false }</c>. Closed: any other property is rejected.</summary>
public static class PhSegmentRuleDisabledSetPayload
{
    private static readonly string[] AllowedProperties = { "value" };

    public static bool Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhSegmentRuleDisabledOperationKinds.SetDisabled);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhSegmentRuleDisabledOperationKinds.SetDisabled);

        return ClosedPayloadParsing.GetRequiredBoolean(after, "value", PhSegmentRuleDisabledOperationKinds.SetDisabled);
    }
}

/// <summary>The <c>after</c> payload for <see cref="PhSegmentRuleDisabledOperationKinds.ClearDisabled"/>:
/// <c>{}</c>. Closed: any property at all is rejected — there is exactly one value to clear.</summary>
public static class PhSegmentRuleDisabledClearPayload
{
    private static readonly string[] AllowedProperties = Array.Empty<string>();

    public static void Parse(JsonElement after)
    {
        ClosedPayloadParsing.RequireObject(after, PhSegmentRuleDisabledOperationKinds.ClearDisabled);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, PhSegmentRuleDisabledOperationKinds.ClearDisabled);
    }
}

/// <summary>Lowers <see cref="PhSegmentRuleDisabledOperationKinds.SetDisabled"/>: the one LibLCM
/// write it performs, <c>phSegmentRule.Disabled = value</c>.</summary>
public static class PhSegmentRuleDisabledSetLowering
{
    public static void Apply(IPhSegmentRule phSegmentRule, bool value) => phSegmentRule.Disabled = value;
}

/// <summary>Lowers <see cref="PhSegmentRuleDisabledOperationKinds.ClearDisabled"/>: resets
/// <c>phSegmentRule.Disabled</c> to <c>false</c>.</summary>
public static class PhSegmentRuleDisabledClearLowering
{
    public static void Apply(IPhSegmentRule phSegmentRule) => phSegmentRule.Disabled = false;
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhSegmentRuleDisabledOperationKinds.SetDisabled"/> operation.</summary>
internal sealed class PhSegmentRuleDisabledSetHandler : IOperationHandler
{
    internal static readonly PhSegmentRuleDisabledSetHandler Instance = new();
    private PhSegmentRuleDisabledSetHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleDisabledOperationKinds.SetDisabled}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleDisabledOperationKinds.SetDisabled}' requires 'after'.");
        }

        var desired = PhSegmentRuleDisabledSetPayload.Parse(after);

        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleDisabledOperationKinds.SetDisabled);
        touchedTargets.Add(id);

        var before = ReadField(cache, phSegmentRule);
        if (!desired) RegularRuleActivationGuard.RequireComplete(phSegmentRule);
                PhSegmentRuleDisabledSetLowering.Apply(phSegmentRule, desired);
        var afterValue = ReadField(cache, phSegmentRule);

        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleDisabled, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleDisabledOperationKinds.SetDisabled);
        var current = ReadField(cache, phSegmentRule);
        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleDisabled, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhSegmentRule phSegmentRule) =>
        PhSegmentRuleSnapshotter.Snapshot(cache, phSegmentRule).AlternativesFields
            .TryGetValue(SnapshotFields.PhSegmentRuleDisabled, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}

/// <summary>The <see cref="PhSegmentRuleDisabledOperationKinds.ClearDisabled"/> counterpart to
/// <see cref="PhSegmentRuleDisabledSetHandler"/>.</summary>
internal sealed class PhSegmentRuleDisabledClearHandler : IOperationHandler
{
    internal static readonly PhSegmentRuleDisabledClearHandler Instance = new();
    private PhSegmentRuleDisabledClearHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleDisabledOperationKinds.ClearDisabled}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSegmentRuleDisabledOperationKinds.ClearDisabled}' requires 'after'.");
        }

        PhSegmentRuleDisabledClearPayload.Parse(after);

        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleDisabledOperationKinds.ClearDisabled);
        touchedTargets.Add(id);

        var before = ReadField(cache, phSegmentRule);
        RegularRuleActivationGuard.RequireComplete(phSegmentRule);
                PhSegmentRuleDisabledClearLowering.Apply(phSegmentRule);
        var afterValue = ReadField(cache, phSegmentRule);

        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleDisabled, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSegmentRule) = TargetResolution.Resolve<IPhSegmentRule>(cache, operation, PhSegmentRuleDisabledOperationKinds.ClearDisabled);
        var current = ReadField(cache, phSegmentRule);
        return new ExpectedEffect(id, SnapshotFields.PhSegmentRuleDisabled, current, current);
    }

    private static IReadOnlyDictionary<string, string> ReadField(LcmCache cache, IPhSegmentRule phSegmentRule) =>
        PhSegmentRuleSnapshotter.Snapshot(cache, phSegmentRule).AlternativesFields
            .TryGetValue(SnapshotFields.PhSegmentRuleDisabled, out var alternatives)
            ? alternatives
            : new Dictionary<string, string>();
}
