// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhSimpleContextNC.PlusConstr (rel/seq PhFeatureConstraint, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhSimpleContextNC.PlusConstr</c> operation kinds.</summary>
public static class PhSimpleContextNCPlusConstrOperationKinds
{
    public const string AddRefPlusConstr = "grammar/phSimpleContextNC/addRefPlusConstr";
    public const string RemoveRefPlusConstr = "grammar/phSimpleContextNC/removeRefPlusConstr";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefPlusConstr);
        OperationKindRegistry.Register(RemoveRefPlusConstr);
        OperationHandlerRegistry.Register(AddRefPlusConstr, PhSimpleContextNCPlusConstrAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefPlusConstr, PhSimpleContextNCPlusConstrRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="PhSimpleContextNCPlusConstrOperationKinds.AddRefPlusConstr"/>
/// and <see cref="PhSimpleContextNCPlusConstrOperationKinds.RemoveRefPlusConstr"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PhSimpleContextNCPlusConstrMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="PhSimpleContextNCPlusConstrOperationKinds.AddRefPlusConstr"/>: resolves the
/// referenced IPhFeatureConstraint and adds it to <c>phSimpleContextNC.PlusConstrRS</c> (a no-op if already
/// present).</summary>
public static class PhSimpleContextNCPlusConstrAddRefLowering
{
    public static void Apply(LcmCache cache, IPhSimpleContextNC phSimpleContextNC, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IPhFeatureConstraint>(
            cache, phSimpleContextNC.PlusConstrRS, memberId, PhSimpleContextNCPlusConstrOperationKinds.AddRefPlusConstr);
}

/// <summary>Lowers <see cref="PhSimpleContextNCPlusConstrOperationKinds.RemoveRefPlusConstr"/>: resolves the
/// referenced IPhFeatureConstraint and removes it from <c>phSimpleContextNC.PlusConstrRS</c> (a no-op if
/// absent).</summary>
public static class PhSimpleContextNCPlusConstrRemoveRefLowering
{
    public static void Apply(LcmCache cache, IPhSimpleContextNC phSimpleContextNC, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPhFeatureConstraint>(
            cache, phSimpleContextNC.PlusConstrRS, memberId, PhSimpleContextNCPlusConstrOperationKinds.RemoveRefPlusConstr);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhSimpleContextNCPlusConstrOperationKinds.AddRefPlusConstr"/> operation.</summary>
internal sealed class PhSimpleContextNCPlusConstrAddRefHandler : IOperationHandler
{
    internal static readonly PhSimpleContextNCPlusConstrAddRefHandler Instance = new();
    private PhSimpleContextNCPlusConstrAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextNCPlusConstrOperationKinds.AddRefPlusConstr}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextNCPlusConstrOperationKinds.AddRefPlusConstr}' requires 'after'.");
        }

        var memberId = PhSimpleContextNCPlusConstrMemberPayload.Parse(after, PhSimpleContextNCPlusConstrOperationKinds.AddRefPlusConstr);

        var (id, phSimpleContextNC) = TargetResolution.Resolve<IPhSimpleContextNC>(cache, operation, PhSimpleContextNCPlusConstrOperationKinds.AddRefPlusConstr);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.PlusConstrRS);
        PhSimpleContextNCPlusConstrAddRefLowering.Apply(cache, phSimpleContextNC, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.PlusConstrRS);

        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextNCPlusConstr, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSimpleContextNC) = TargetResolution.Resolve<IPhSimpleContextNC>(cache, operation, PhSimpleContextNCPlusConstrOperationKinds.AddRefPlusConstr);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.PlusConstrRS);
        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextNCPlusConstr, current, current);
    }
}

/// <summary>The <see cref="PhSimpleContextNCPlusConstrOperationKinds.RemoveRefPlusConstr"/> counterpart to
/// <see cref="PhSimpleContextNCPlusConstrAddRefHandler"/>.</summary>
internal sealed class PhSimpleContextNCPlusConstrRemoveRefHandler : IOperationHandler
{
    internal static readonly PhSimpleContextNCPlusConstrRemoveRefHandler Instance = new();
    private PhSimpleContextNCPlusConstrRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextNCPlusConstrOperationKinds.RemoveRefPlusConstr}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextNCPlusConstrOperationKinds.RemoveRefPlusConstr}' requires 'after'.");
        }

        var memberId = PhSimpleContextNCPlusConstrMemberPayload.Parse(after, PhSimpleContextNCPlusConstrOperationKinds.RemoveRefPlusConstr);

        var (id, phSimpleContextNC) = TargetResolution.Resolve<IPhSimpleContextNC>(cache, operation, PhSimpleContextNCPlusConstrOperationKinds.RemoveRefPlusConstr);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.PlusConstrRS);
        PhSimpleContextNCPlusConstrRemoveRefLowering.Apply(cache, phSimpleContextNC, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.PlusConstrRS);

        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextNCPlusConstr, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSimpleContextNC) = TargetResolution.Resolve<IPhSimpleContextNC>(cache, operation, PhSimpleContextNCPlusConstrOperationKinds.RemoveRefPlusConstr);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.PlusConstrRS);
        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextNCPlusConstr, current, current);
    }
}
