// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: PhSimpleContextNC.MinusConstr (rel/seq PhFeatureConstraint, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>PhSimpleContextNC.MinusConstr</c> operation kinds.</summary>
public static class PhSimpleContextNCMinusConstrOperationKinds
{
    public const string AddRefMinusConstr = "grammar/phSimpleContextNC/addRefMinusConstr";
    public const string RemoveRefMinusConstr = "grammar/phSimpleContextNC/removeRefMinusConstr";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefMinusConstr);
        OperationKindRegistry.Register(RemoveRefMinusConstr);
        OperationHandlerRegistry.Register(AddRefMinusConstr, PhSimpleContextNCMinusConstrAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefMinusConstr, PhSimpleContextNCMinusConstrRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="PhSimpleContextNCMinusConstrOperationKinds.AddRefMinusConstr"/>
/// and <see cref="PhSimpleContextNCMinusConstrOperationKinds.RemoveRefMinusConstr"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class PhSimpleContextNCMinusConstrMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="PhSimpleContextNCMinusConstrOperationKinds.AddRefMinusConstr"/>: resolves the
/// referenced IPhFeatureConstraint and adds it to <c>phSimpleContextNC.MinusConstrRS</c> (a no-op if already
/// present).</summary>
public static class PhSimpleContextNCMinusConstrAddRefLowering
{
    public static void Apply(LcmCache cache, IPhSimpleContextNC phSimpleContextNC, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<IPhFeatureConstraint>(
            cache, phSimpleContextNC.MinusConstrRS, memberId, PhSimpleContextNCMinusConstrOperationKinds.AddRefMinusConstr);
}

/// <summary>Lowers <see cref="PhSimpleContextNCMinusConstrOperationKinds.RemoveRefMinusConstr"/>: resolves the
/// referenced IPhFeatureConstraint and removes it from <c>phSimpleContextNC.MinusConstrRS</c> (a no-op if
/// absent).</summary>
public static class PhSimpleContextNCMinusConstrRemoveRefLowering
{
    public static void Apply(LcmCache cache, IPhSimpleContextNC phSimpleContextNC, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<IPhFeatureConstraint>(
            cache, phSimpleContextNC.MinusConstrRS, memberId, PhSimpleContextNCMinusConstrOperationKinds.RemoveRefMinusConstr);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="PhSimpleContextNCMinusConstrOperationKinds.AddRefMinusConstr"/> operation.</summary>
internal sealed class PhSimpleContextNCMinusConstrAddRefHandler : IOperationHandler
{
    internal static readonly PhSimpleContextNCMinusConstrAddRefHandler Instance = new();
    private PhSimpleContextNCMinusConstrAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextNCMinusConstrOperationKinds.AddRefMinusConstr}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextNCMinusConstrOperationKinds.AddRefMinusConstr}' requires 'after'.");
        }

        var memberId = PhSimpleContextNCMinusConstrMemberPayload.Parse(after, PhSimpleContextNCMinusConstrOperationKinds.AddRefMinusConstr);

        var (id, phSimpleContextNC) = TargetResolution.Resolve<IPhSimpleContextNC>(cache, operation, PhSimpleContextNCMinusConstrOperationKinds.AddRefMinusConstr);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.MinusConstrRS);
        PhSimpleContextNCMinusConstrAddRefLowering.Apply(cache, phSimpleContextNC, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.MinusConstrRS);

        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextNCMinusConstr, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSimpleContextNC) = TargetResolution.Resolve<IPhSimpleContextNC>(cache, operation, PhSimpleContextNCMinusConstrOperationKinds.AddRefMinusConstr);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.MinusConstrRS);
        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextNCMinusConstr, current, current);
    }
}

/// <summary>The <see cref="PhSimpleContextNCMinusConstrOperationKinds.RemoveRefMinusConstr"/> counterpart to
/// <see cref="PhSimpleContextNCMinusConstrAddRefHandler"/>.</summary>
internal sealed class PhSimpleContextNCMinusConstrRemoveRefHandler : IOperationHandler
{
    internal static readonly PhSimpleContextNCMinusConstrRemoveRefHandler Instance = new();
    private PhSimpleContextNCMinusConstrRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextNCMinusConstrOperationKinds.RemoveRefMinusConstr}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{PhSimpleContextNCMinusConstrOperationKinds.RemoveRefMinusConstr}' requires 'after'.");
        }

        var memberId = PhSimpleContextNCMinusConstrMemberPayload.Parse(after, PhSimpleContextNCMinusConstrOperationKinds.RemoveRefMinusConstr);

        var (id, phSimpleContextNC) = TargetResolution.Resolve<IPhSimpleContextNC>(cache, operation, PhSimpleContextNCMinusConstrOperationKinds.RemoveRefMinusConstr);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.MinusConstrRS);
        PhSimpleContextNCMinusConstrRemoveRefLowering.Apply(cache, phSimpleContextNC, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.MinusConstrRS);

        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextNCMinusConstr, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, phSimpleContextNC) = TargetResolution.Resolve<IPhSimpleContextNC>(cache, operation, PhSimpleContextNCMinusConstrOperationKinds.RemoveRefMinusConstr);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(phSimpleContextNC.MinusConstrRS);
        return new ExpectedEffect(id, SnapshotFields.PhSimpleContextNCMinusConstr, current, current);
    }
}
