// <auto-generated>
//   Produced by SIL.Motif.Generator's `emit` command.
//   Do NOT hand-edit. Rerun `dotnet run --project src/SIL.Motif.Generator -- emit` after a
//   manifest or MasterLCModel.xml change, and check in the result.
//
//   Source: ReversalIndexEntry.Senses (rel/seq LexSense, addRef|removeRef emitted;
//   `move` deferred -- see ReferenceCollectionFieldEmitter.cs (SIL.Motif.Generator) remarks).
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using SIL.Motif.Contract.Ids;
using SIL.Motif.Contract.Model;
using SIL.Motif.Contract.Parsing;
using SIL.Motif.Model.Effects;
using SIL.Motif.Model.Snapshot;
using SIL.Motif.Runner.Snapshotting;
using SIL.LCModel;

namespace SIL.Motif.Runner.Operations;

/// <summary>Names the two <c>ReversalIndexEntry.Senses</c> operation kinds.</summary>
public static class ReversalIndexEntrySensesOperationKinds
{
    public const string AddRefSenses = "lexical/reversalIndexEntry/addRefSenses";
    public const string RemoveRefSenses = "lexical/reversalIndexEntry/removeRefSenses";

    [ModuleInitializer]
    internal static void Register()
    {
        OperationKindRegistry.Register(AddRefSenses);
        OperationKindRegistry.Register(RemoveRefSenses);
        OperationHandlerRegistry.Register(AddRefSenses, ReversalIndexEntrySensesAddRefHandler.Instance);
        OperationHandlerRegistry.Register(RemoveRefSenses, ReversalIndexEntrySensesRemoveRefHandler.Instance);
    }
}

/// <summary>The <c>after</c> payload for both <see cref="ReversalIndexEntrySensesOperationKinds.AddRefSenses"/>
/// and <see cref="ReversalIndexEntrySensesOperationKinds.RemoveRefSenses"/>:
/// <c>{ "member": "&lt;canonicalId&gt;" }</c>. Closed: any other property is rejected.</summary>
public static class ReversalIndexEntrySensesMemberPayload
{
    private static readonly string[] AllowedProperties = { "member" };

    public static CanonicalId Parse(JsonElement after, string kind)
    {
        ClosedPayloadParsing.RequireObject(after, kind);
        ClosedPayloadParsing.RejectUnknownProperties(after, AllowedProperties, kind);

        return ClosedPayloadParsing.GetRequiredCanonicalId(after, "member", kind);
    }
}

/// <summary>Lowers <see cref="ReversalIndexEntrySensesOperationKinds.AddRefSenses"/>: resolves the
/// referenced ILexSense and adds it to <c>reversalIndexEntry.SensesRS</c> (a no-op if already
/// present).</summary>
public static class ReversalIndexEntrySensesAddRefLowering
{
    public static void Apply(LcmCache cache, IReversalIndexEntry reversalIndexEntry, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyAddRef<ILexSense>(
            cache, reversalIndexEntry.SensesRS, memberId, ReversalIndexEntrySensesOperationKinds.AddRefSenses);
}

/// <summary>Lowers <see cref="ReversalIndexEntrySensesOperationKinds.RemoveRefSenses"/>: resolves the
/// referenced ILexSense and removes it from <c>reversalIndexEntry.SensesRS</c> (a no-op if
/// absent).</summary>
public static class ReversalIndexEntrySensesRemoveRefLowering
{
    public static void Apply(LcmCache cache, IReversalIndexEntry reversalIndexEntry, CanonicalId memberId) =>
        ReferenceCollectionFieldLowering.ApplyRemoveRef<ILexSense>(
            cache, reversalIndexEntry.SensesRS, memberId, ReversalIndexEntrySensesOperationKinds.RemoveRefSenses);
}

/// <summary>Resolves, snapshots, lowers, and re-snapshots one
/// <see cref="ReversalIndexEntrySensesOperationKinds.AddRefSenses"/> operation.</summary>
internal sealed class ReversalIndexEntrySensesAddRefHandler : IOperationHandler
{
    internal static readonly ReversalIndexEntrySensesAddRefHandler Instance = new();
    private ReversalIndexEntrySensesAddRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{ReversalIndexEntrySensesOperationKinds.AddRefSenses}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{ReversalIndexEntrySensesOperationKinds.AddRefSenses}' requires 'after'.");
        }

        var memberId = ReversalIndexEntrySensesMemberPayload.Parse(after, ReversalIndexEntrySensesOperationKinds.AddRefSenses);

        var (id, reversalIndexEntry) = TargetResolution.Resolve<IReversalIndexEntry>(cache, operation, ReversalIndexEntrySensesOperationKinds.AddRefSenses);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(reversalIndexEntry.SensesRS);
        ReversalIndexEntrySensesAddRefLowering.Apply(cache, reversalIndexEntry, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(reversalIndexEntry.SensesRS);

        return new ExpectedEffect(id, SnapshotFields.ReversalIndexEntrySenses, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, reversalIndexEntry) = TargetResolution.Resolve<IReversalIndexEntry>(cache, operation, ReversalIndexEntrySensesOperationKinds.AddRefSenses);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(reversalIndexEntry.SensesRS);
        return new ExpectedEffect(id, SnapshotFields.ReversalIndexEntrySenses, current, current);
    }
}

/// <summary>The <see cref="ReversalIndexEntrySensesOperationKinds.RemoveRefSenses"/> counterpart to
/// <see cref="ReversalIndexEntrySensesAddRefHandler"/>.</summary>
internal sealed class ReversalIndexEntrySensesRemoveRefHandler : IOperationHandler
{
    internal static readonly ReversalIndexEntrySensesRemoveRefHandler Instance = new();
    private ReversalIndexEntrySensesRemoveRefHandler() { }

    public ExpectedEffect ApplyAndCaptureEffect(LcmCache cache, OperationEnvelope operation, List<CanonicalId> touchedTargets)
    {
        if (operation.Target is not { })
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{ReversalIndexEntrySensesOperationKinds.RemoveRefSenses}' requires 'target'.");
        }

        if (operation.After is not { } after)
        {
            throw new InvalidOperationException(
                $"Operation '{operation.OperationId.Value}' of kind '{ReversalIndexEntrySensesOperationKinds.RemoveRefSenses}' requires 'after'.");
        }

        var memberId = ReversalIndexEntrySensesMemberPayload.Parse(after, ReversalIndexEntrySensesOperationKinds.RemoveRefSenses);

        var (id, reversalIndexEntry) = TargetResolution.Resolve<IReversalIndexEntry>(cache, operation, ReversalIndexEntrySensesOperationKinds.RemoveRefSenses);
        touchedTargets.Add(id);

        var before = ReferenceSequenceFieldSnapshotting.ReadAlternatives(reversalIndexEntry.SensesRS);
        ReversalIndexEntrySensesRemoveRefLowering.Apply(cache, reversalIndexEntry, memberId);
        var afterValue = ReferenceSequenceFieldSnapshotting.ReadAlternatives(reversalIndexEntry.SensesRS);

        return new ExpectedEffect(id, SnapshotFields.ReversalIndexEntrySenses, before, afterValue);
    }

    public ExpectedEffect ReadCurrentFootprint(LcmCache cache, OperationEnvelope operation)
    {
        var (id, reversalIndexEntry) = TargetResolution.Resolve<IReversalIndexEntry>(cache, operation, ReversalIndexEntrySensesOperationKinds.RemoveRefSenses);
        var current = ReferenceSequenceFieldSnapshotting.ReadAlternatives(reversalIndexEntry.SensesRS);
        return new ExpectedEffect(id, SnapshotFields.ReversalIndexEntrySenses, current, current);
    }
}
